gMonFrontPic_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/front.4bpp.lz"

gMonPalette_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/normal.gbapal.lz"

gMonBackPic_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/back.4bpp.lz"

gMonShinyPalette_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/shiny.gbapal.lz"

gMonIcon_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/icon.4bpp"

gMonFootprint_Pokemon_000::
	.incbin "graphics/pokemon/pokemon_000/footprint.1bpp"

gMonFrontPic_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/front.4bpp.lz"

gMonPalette_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/normal.gbapal.lz"

gMonBackPic_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/back.4bpp.lz"

gMonShinyPalette_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/shiny.gbapal.lz"

gMonIcon_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/icon.4bpp"

gMonFootprint_Chapebaya::
	.incbin "graphics/pokemon/chapebaya/footprint.1bpp"

gMonFrontPic_Denpecha::
	.incbin "graphics/pokemon/denpecha/front.4bpp.lz"

gMonPalette_Denpecha::
	.incbin "graphics/pokemon/denpecha/normal.gbapal.lz"

gMonBackPic_Denpecha::
	.incbin "graphics/pokemon/denpecha/back.4bpp.lz"

gMonShinyPalette_Denpecha::
	.incbin "graphics/pokemon/denpecha/shiny.gbapal.lz"

gMonIcon_Denpecha::
	.incbin "graphics/pokemon/denpecha/icon.4bpp"

gMonFootprint_Denpecha::
	.incbin "graphics/pokemon/denpecha/footprint.1bpp"

gMonFrontPic_Denfrota::
	.incbin "graphics/pokemon/denfrota/front.4bpp.lz"

gMonPalette_Denfrota::
	.incbin "graphics/pokemon/denfrota/normal.gbapal.lz"

gMonBackPic_Denfrota::
	.incbin "graphics/pokemon/denfrota/back.4bpp.lz"

gMonShinyPalette_Denfrota::
	.incbin "graphics/pokemon/denfrota/shiny.gbapal.lz"

gMonIcon_Denfrota::
	.incbin "graphics/pokemon/denfrota/icon.4bpp"

gMonFootprint_Denfrota::
	.incbin "graphics/pokemon/denfrota/footprint.1bpp"

gMonFrontPic_Coalchu::
	.incbin "graphics/pokemon/coalchu/front.4bpp.lz"

gMonPalette_Coalchu::
	.incbin "graphics/pokemon/coalchu/normal.gbapal.lz"

gMonBackPic_Coalchu::
	.incbin "graphics/pokemon/coalchu/back.4bpp.lz"

gMonShinyPalette_Coalchu::
	.incbin "graphics/pokemon/coalchu/shiny.gbapal.lz"

gMonIcon_Coalchu::
	.incbin "graphics/pokemon/coalchu/icon.4bpp"

gMonFootprint_Coalchu::
	.incbin "graphics/pokemon/coalchu/footprint.1bpp"

gMonFrontPic_Rallama::
	.incbin "graphics/pokemon/rallama/front.4bpp.lz"

gMonPalette_Rallama::
	.incbin "graphics/pokemon/rallama/normal.gbapal.lz"

gMonBackPic_Rallama::
	.incbin "graphics/pokemon/rallama/back.4bpp.lz"

gMonShinyPalette_Rallama::
	.incbin "graphics/pokemon/rallama/shiny.gbapal.lz"

gMonIcon_Rallama::
	.incbin "graphics/pokemon/rallama/icon.4bpp"

gMonFootprint_Rallama::
	.incbin "graphics/pokemon/rallama/footprint.1bpp"

gMonFrontPic_Roellama::
	.incbin "graphics/pokemon/roellama/front.4bpp.lz"

gMonPalette_Roellama::
	.incbin "graphics/pokemon/roellama/normal.gbapal.lz"

gMonBackPic_Roellama::
	.incbin "graphics/pokemon/roellama/back.4bpp.lz"

gMonShinyPalette_Roellama::
	.incbin "graphics/pokemon/roellama/shiny.gbapal.lz"

gMonIcon_Roellama::
	.incbin "graphics/pokemon/roellama/icon.4bpp"

gMonFootprint_Roellama::
	.incbin "graphics/pokemon/roellama/footprint.1bpp"

gMonFrontPic_Todad::
	.incbin "graphics/pokemon/todad/front.4bpp.lz"

gMonPalette_Todad::
	.incbin "graphics/pokemon/todad/normal.gbapal.lz"

gMonBackPic_Todad::
	.incbin "graphics/pokemon/todad/back.4bpp.lz"

gMonShinyPalette_Todad::
	.incbin "graphics/pokemon/todad/shiny.gbapal.lz"

gMonIcon_Todad::
	.incbin "graphics/pokemon/todad/icon.4bpp"

gMonFootprint_Todad::
	.incbin "graphics/pokemon/todad/footprint.1bpp"

gMonFrontPic_Shroad::
	.incbin "graphics/pokemon/shroad/front.4bpp.lz"

gMonPalette_Shroad::
	.incbin "graphics/pokemon/shroad/normal.gbapal.lz"

gMonBackPic_Shroad::
	.incbin "graphics/pokemon/shroad/back.4bpp.lz"

gMonShinyPalette_Shroad::
	.incbin "graphics/pokemon/shroad/shiny.gbapal.lz"

gMonIcon_Shroad::
	.incbin "graphics/pokemon/shroad/icon.4bpp"

gMonFootprint_Shroad::
	.incbin "graphics/pokemon/shroad/footprint.1bpp"

gMonFrontPic_Bultoad::
	.incbin "graphics/pokemon/bultoad/front.4bpp.lz"

gMonPalette_Bultoad::
	.incbin "graphics/pokemon/bultoad/normal.gbapal.lz"

gMonBackPic_Bultoad::
	.incbin "graphics/pokemon/bultoad/back.4bpp.lz"

gMonShinyPalette_Bultoad::
	.incbin "graphics/pokemon/bultoad/shiny.gbapal.lz"

gMonIcon_Bultoad::
	.incbin "graphics/pokemon/bultoad/icon.4bpp"

gMonFootprint_Bultoad::
	.incbin "graphics/pokemon/bultoad/footprint.1bpp"

gMonFrontPic_Larvet::
	.incbin "graphics/pokemon/larvet/front.4bpp.lz"

gMonPalette_Larvet::
	.incbin "graphics/pokemon/larvet/normal.gbapal.lz"

gMonBackPic_Larvet::
	.incbin "graphics/pokemon/larvet/back.4bpp.lz"

gMonShinyPalette_Larvet::
	.incbin "graphics/pokemon/larvet/shiny.gbapal.lz"

gMonIcon_Larvet::
	.incbin "graphics/pokemon/larvet/icon.4bpp"

gMonFootprint_Larvet::
	.incbin "graphics/pokemon/larvet/footprint.1bpp"

gMonFrontPic_Morfade::
	.incbin "graphics/pokemon/morfade/front.4bpp.lz"

gMonPalette_Morfade::
	.incbin "graphics/pokemon/morfade/normal.gbapal.lz"

gMonBackPic_Morfade::
	.incbin "graphics/pokemon/morfade/back.4bpp.lz"

gMonShinyPalette_Morfade::
	.incbin "graphics/pokemon/morfade/shiny.gbapal.lz"

gMonIcon_Morfade::
	.incbin "graphics/pokemon/morfade/icon.4bpp"

gMonFootprint_Morfade::
	.incbin "graphics/pokemon/morfade/footprint.1bpp"

gMonFrontPic_Eyefly::
	.incbin "graphics/pokemon/eyefly/front.4bpp.lz"

gMonPalette_Eyefly::
	.incbin "graphics/pokemon/eyefly/normal.gbapal.lz"

gMonBackPic_Eyefly::
	.incbin "graphics/pokemon/eyefly/back.4bpp.lz"

gMonShinyPalette_Eyefly::
	.incbin "graphics/pokemon/eyefly/shiny.gbapal.lz"

gMonIcon_Eyefly::
	.incbin "graphics/pokemon/eyefly/icon.4bpp"

gMonFootprint_Eyefly::
	.incbin "graphics/pokemon/eyefly/footprint.1bpp"

gMonFrontPic_Drosofly::
	.incbin "graphics/pokemon/drosofly/front.4bpp.lz"

gMonPalette_Drosofly::
	.incbin "graphics/pokemon/drosofly/normal.gbapal.lz"

gMonBackPic_Drosofly::
	.incbin "graphics/pokemon/drosofly/back.4bpp.lz"

gMonShinyPalette_Drosofly::
	.incbin "graphics/pokemon/drosofly/shiny.gbapal.lz"

gMonIcon_Drosofly::
	.incbin "graphics/pokemon/drosofly/icon.4bpp"

gMonFootprint_Drosofly::
	.incbin "graphics/pokemon/drosofly/footprint.1bpp"

gMonFrontPic_Metagaster::
	.incbin "graphics/pokemon/metagaster/front.4bpp.lz"

gMonPalette_Metagaster::
	.incbin "graphics/pokemon/metagaster/normal.gbapal.lz"

gMonBackPic_Metagaster::
	.incbin "graphics/pokemon/metagaster/back.4bpp.lz"

gMonShinyPalette_Metagaster::
	.incbin "graphics/pokemon/metagaster/shiny.gbapal.lz"

gMonIcon_Metagaster::
	.incbin "graphics/pokemon/metagaster/icon.4bpp"

gMonFootprint_Metagaster::
	.incbin "graphics/pokemon/metagaster/footprint.1bpp"

gMonFrontPic_Phylafly::
	.incbin "graphics/pokemon/phylafly/front.4bpp.lz"

gMonPalette_Phylafly::
	.incbin "graphics/pokemon/phylafly/normal.gbapal.lz"

gMonBackPic_Phylafly::
	.incbin "graphics/pokemon/phylafly/back.4bpp.lz"

gMonShinyPalette_Phylafly::
	.incbin "graphics/pokemon/phylafly/shiny.gbapal.lz"

gMonIcon_Phylafly::
	.incbin "graphics/pokemon/phylafly/icon.4bpp"

gMonFootprint_Phylafly::
	.incbin "graphics/pokemon/phylafly/footprint.1bpp"

gMonFrontPic_Ornlil::
	.incbin "graphics/pokemon/ornlil/front.4bpp.lz"

gMonPalette_Ornlil::
	.incbin "graphics/pokemon/ornlil/normal.gbapal.lz"

gMonBackPic_Ornlil::
	.incbin "graphics/pokemon/ornlil/back.4bpp.lz"

gMonShinyPalette_Ornlil::
	.incbin "graphics/pokemon/ornlil/shiny.gbapal.lz"

gMonIcon_Ornlil::
	.incbin "graphics/pokemon/ornlil/icon.4bpp"

gMonFootprint_Ornlil::
	.incbin "graphics/pokemon/ornlil/footprint.1bpp"

gMonFrontPic_Wasoo::
	.incbin "graphics/pokemon/wasoo/front.4bpp.lz"

gMonPalette_Wasoo::
	.incbin "graphics/pokemon/wasoo/normal.gbapal.lz"

gMonBackPic_Wasoo::
	.incbin "graphics/pokemon/wasoo/back.4bpp.lz"

gMonShinyPalette_Wasoo::
	.incbin "graphics/pokemon/wasoo/shiny.gbapal.lz"

gMonIcon_Wasoo::
	.incbin "graphics/pokemon/wasoo/icon.4bpp"

gMonFootprint_Wasoo::
	.incbin "graphics/pokemon/wasoo/footprint.1bpp"

gMonFrontPic_Volateo::
	.incbin "graphics/pokemon/volateo/front.4bpp.lz"

gMonPalette_Volateo::
	.incbin "graphics/pokemon/volateo/normal.gbapal.lz"

gMonBackPic_Volateo::
	.incbin "graphics/pokemon/volateo/back.4bpp.lz"

gMonShinyPalette_Volateo::
	.incbin "graphics/pokemon/volateo/shiny.gbapal.lz"

gMonIcon_Volateo::
	.incbin "graphics/pokemon/volateo/icon.4bpp"

gMonFootprint_Volateo::
	.incbin "graphics/pokemon/volateo/footprint.1bpp"

gMonFrontPic_Batoka::
	.incbin "graphics/pokemon/batoka/front.4bpp.lz"

gMonPalette_Batoka::
	.incbin "graphics/pokemon/batoka/normal.gbapal.lz"

gMonBackPic_Batoka::
	.incbin "graphics/pokemon/batoka/back.4bpp.lz"

gMonShinyPalette_Batoka::
	.incbin "graphics/pokemon/batoka/shiny.gbapal.lz"

gMonIcon_Batoka::
	.incbin "graphics/pokemon/batoka/icon.4bpp"

gMonFootprint_Batoka::
	.incbin "graphics/pokemon/batoka/footprint.1bpp"

gMonFrontPic_Mouspid::
	.incbin "graphics/pokemon/mouspid/front.4bpp.lz"

gMonPalette_Mouspid::
	.incbin "graphics/pokemon/mouspid/normal.gbapal.lz"

gMonBackPic_Mouspid::
	.incbin "graphics/pokemon/mouspid/back.4bpp.lz"

gMonShinyPalette_Mouspid::
	.incbin "graphics/pokemon/mouspid/shiny.gbapal.lz"

gMonIcon_Mouspid::
	.incbin "graphics/pokemon/mouspid/icon.4bpp"

gMonFootprint_Mouspid::
	.incbin "graphics/pokemon/mouspid/footprint.1bpp"

gMonFrontPic_Turkur::
	.incbin "graphics/pokemon/turkur/front.4bpp.lz"

gMonPalette_Turkur::
	.incbin "graphics/pokemon/turkur/normal.gbapal.lz"

gMonBackPic_Turkur::
	.incbin "graphics/pokemon/turkur/back.4bpp.lz"

gMonShinyPalette_Turkur::
	.incbin "graphics/pokemon/turkur/shiny.gbapal.lz"

gMonIcon_Turkur::
	.incbin "graphics/pokemon/turkur/icon.4bpp"

gMonFootprint_Turkur::
	.incbin "graphics/pokemon/turkur/footprint.1bpp"

gMonFrontPic_Peakur::
	.incbin "graphics/pokemon/peakur/front.4bpp.lz"

gMonPalette_Peakur::
	.incbin "graphics/pokemon/peakur/normal.gbapal.lz"

gMonBackPic_Peakur::
	.incbin "graphics/pokemon/peakur/back.4bpp.lz"

gMonShinyPalette_Peakur::
	.incbin "graphics/pokemon/peakur/shiny.gbapal.lz"

gMonIcon_Peakur::
	.incbin "graphics/pokemon/peakur/icon.4bpp"

gMonFootprint_Peakur::
	.incbin "graphics/pokemon/peakur/footprint.1bpp"

gMonFrontPic_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/front.4bpp.lz"

gMonPalette_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/normal.gbapal.lz"

gMonBackPic_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/back.4bpp.lz"

gMonShinyPalette_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/shiny.gbapal.lz"

gMonIcon_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/icon.4bpp"

gMonFootprint_Chuk_Txu::
	.incbin "graphics/pokemon/chuk_txu/footprint.1bpp"

gMonFrontPic_Leeckey::
	.incbin "graphics/pokemon/leeckey/front.4bpp.lz"

gMonPalette_Leeckey::
	.incbin "graphics/pokemon/leeckey/normal.gbapal.lz"

gMonBackPic_Leeckey::
	.incbin "graphics/pokemon/leeckey/back.4bpp.lz"

gMonShinyPalette_Leeckey::
	.incbin "graphics/pokemon/leeckey/shiny.gbapal.lz"

gMonIcon_Leeckey::
	.incbin "graphics/pokemon/leeckey/icon.4bpp"

gMonFootprint_Leeckey::
	.incbin "graphics/pokemon/leeckey/footprint.1bpp"

gMonFrontPic_Covolts::
	.incbin "graphics/pokemon/covolts/front.4bpp.lz"

gMonPalette_Covolts::
	.incbin "graphics/pokemon/covolts/normal.gbapal.lz"

gMonBackPic_Covolts::
	.incbin "graphics/pokemon/covolts/back.4bpp.lz"

gMonShinyPalette_Covolts::
	.incbin "graphics/pokemon/covolts/shiny.gbapal.lz"

gMonIcon_Covolts::
	.incbin "graphics/pokemon/covolts/icon.4bpp"

gMonFootprint_Covolts::
	.incbin "graphics/pokemon/covolts/footprint.1bpp"

gMonFrontPic_Lucivots::
	.incbin "graphics/pokemon/lucivots/front.4bpp.lz"

gMonPalette_Lucivots::
	.incbin "graphics/pokemon/lucivots/normal.gbapal.lz"

gMonBackPic_Lucivots::
	.incbin "graphics/pokemon/lucivots/back.4bpp.lz"

gMonShinyPalette_Lucivots::
	.incbin "graphics/pokemon/lucivots/shiny.gbapal.lz"

gMonIcon_Lucivots::
	.incbin "graphics/pokemon/lucivots/icon.4bpp"

gMonFootprint_Lucivots::
	.incbin "graphics/pokemon/lucivots/footprint.1bpp"

gMonFrontPic_Nole::
	.incbin "graphics/pokemon/nole/front.4bpp.lz"

gMonPalette_Nole::
	.incbin "graphics/pokemon/nole/normal.gbapal.lz"

gMonBackPic_Nole::
	.incbin "graphics/pokemon/nole/back.4bpp.lz"

gMonShinyPalette_Nole::
	.incbin "graphics/pokemon/nole/shiny.gbapal.lz"

gMonIcon_Nole::
	.incbin "graphics/pokemon/nole/icon.4bpp"

gMonFootprint_Nole::
	.incbin "graphics/pokemon/nole/footprint.1bpp"

gMonFrontPic_Groundoe::
	.incbin "graphics/pokemon/groundoe/front.4bpp.lz"

gMonPalette_Groundoe::
	.incbin "graphics/pokemon/groundoe/normal.gbapal.lz"

gMonBackPic_Groundoe::
	.incbin "graphics/pokemon/groundoe/back.4bpp.lz"

gMonShinyPalette_Groundoe::
	.incbin "graphics/pokemon/groundoe/shiny.gbapal.lz"

gMonIcon_Groundoe::
	.incbin "graphics/pokemon/groundoe/icon.4bpp"

gMonFootprint_Groundoe::
	.incbin "graphics/pokemon/groundoe/footprint.1bpp"

gMonFrontPic_Urtiga::
	.incbin "graphics/pokemon/urtiga/front.4bpp.lz"

gMonPalette_Urtiga::
	.incbin "graphics/pokemon/urtiga/normal.gbapal.lz"

gMonBackPic_Urtiga::
	.incbin "graphics/pokemon/urtiga/back.4bpp.lz"

gMonShinyPalette_Urtiga::
	.incbin "graphics/pokemon/urtiga/shiny.gbapal.lz"

gMonIcon_Urtiga::
	.incbin "graphics/pokemon/urtiga/icon.4bpp"

gMonFootprint_Urtiga::
	.incbin "graphics/pokemon/urtiga/footprint.1bpp"

gMonFrontPic_Urtigere::
	.incbin "graphics/pokemon/urtigere/front.4bpp.lz"

gMonPalette_Urtigere::
	.incbin "graphics/pokemon/urtigere/normal.gbapal.lz"

gMonBackPic_Urtigere::
	.incbin "graphics/pokemon/urtigere/back.4bpp.lz"

gMonShinyPalette_Urtigere::
	.incbin "graphics/pokemon/urtigere/shiny.gbapal.lz"

gMonIcon_Urtigere::
	.incbin "graphics/pokemon/urtigere/icon.4bpp"

gMonFootprint_Urtigere::
	.incbin "graphics/pokemon/urtigere/footprint.1bpp"

gMonFrontPic_Venogena::
	.incbin "graphics/pokemon/venogena/front.4bpp.lz"

gMonPalette_Venogena::
	.incbin "graphics/pokemon/venogena/normal.gbapal.lz"

gMonBackPic_Venogena::
	.incbin "graphics/pokemon/venogena/back.4bpp.lz"

gMonShinyPalette_Venogena::
	.incbin "graphics/pokemon/venogena/shiny.gbapal.lz"

gMonIcon_Venogena::
	.incbin "graphics/pokemon/venogena/icon.4bpp"

gMonFootprint_Venogena::
	.incbin "graphics/pokemon/venogena/footprint.1bpp"

gMonFrontPic_Urtigo::
	.incbin "graphics/pokemon/urtigo/front.4bpp.lz"

gMonPalette_Urtigo::
	.incbin "graphics/pokemon/urtigo/normal.gbapal.lz"

gMonBackPic_Urtigo::
	.incbin "graphics/pokemon/urtigo/back.4bpp.lz"

gMonShinyPalette_Urtigo::
	.incbin "graphics/pokemon/urtigo/shiny.gbapal.lz"

gMonIcon_Urtigo::
	.incbin "graphics/pokemon/urtigo/icon.4bpp"

gMonFootprint_Urtigo::
	.incbin "graphics/pokemon/urtigo/footprint.1bpp"

gMonFrontPic_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/front.4bpp.lz"

gMonPalette_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/normal.gbapal.lz"

gMonBackPic_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/back.4bpp.lz"

gMonShinyPalette_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/shiny.gbapal.lz"

gMonIcon_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/icon.4bpp"

gMonFootprint_Urtigoro::
	.incbin "graphics/pokemon/urtigoro/footprint.1bpp"

gMonFrontPic_Venogeno::
	.incbin "graphics/pokemon/venogeno/front.4bpp.lz"

gMonPalette_Venogeno::
	.incbin "graphics/pokemon/venogeno/normal.gbapal.lz"

gMonBackPic_Venogeno::
	.incbin "graphics/pokemon/venogeno/back.4bpp.lz"

gMonShinyPalette_Venogeno::
	.incbin "graphics/pokemon/venogeno/shiny.gbapal.lz"

gMonIcon_Venogeno::
	.incbin "graphics/pokemon/venogeno/icon.4bpp"

gMonFootprint_Venogeno::
	.incbin "graphics/pokemon/venogeno/footprint.1bpp"

gMonFrontPic_Amairi::
	.incbin "graphics/pokemon/amairi/front.4bpp.lz"

gMonPalette_Amairi::
	.incbin "graphics/pokemon/amairi/normal.gbapal.lz"

gMonBackPic_Amairi::
	.incbin "graphics/pokemon/amairi/back.4bpp.lz"

gMonShinyPalette_Amairi::
	.incbin "graphics/pokemon/amairi/shiny.gbapal.lz"

gMonIcon_Amairi::
	.incbin "graphics/pokemon/amairi/icon.4bpp"

gMonFootprint_Amairi::
	.incbin "graphics/pokemon/amairi/footprint.1bpp"

gMonFrontPic_Ograiri::
	.incbin "graphics/pokemon/ograiri/front.4bpp.lz"

gMonPalette_Ograiri::
	.incbin "graphics/pokemon/ograiri/normal.gbapal.lz"

gMonBackPic_Ograiri::
	.incbin "graphics/pokemon/ograiri/back.4bpp.lz"

gMonShinyPalette_Ograiri::
	.incbin "graphics/pokemon/ograiri/shiny.gbapal.lz"

gMonIcon_Ograiri::
	.incbin "graphics/pokemon/ograiri/icon.4bpp"

gMonFootprint_Ograiri::
	.incbin "graphics/pokemon/ograiri/footprint.1bpp"

gMonFrontPic_Hormig::
	.incbin "graphics/pokemon/hormig/front.4bpp.lz"

gMonPalette_Hormig::
	.incbin "graphics/pokemon/hormig/normal.gbapal.lz"

gMonBackPic_Hormig::
	.incbin "graphics/pokemon/hormig/back.4bpp.lz"

gMonShinyPalette_Hormig::
	.incbin "graphics/pokemon/hormig/shiny.gbapal.lz"

gMonIcon_Hormig::
	.incbin "graphics/pokemon/hormig/icon.4bpp"

gMonFootprint_Hormig::
	.incbin "graphics/pokemon/hormig/footprint.1bpp"

gMonFrontPic_Llamose::
	.incbin "graphics/pokemon/llamose/front.4bpp.lz"

gMonPalette_Llamose::
	.incbin "graphics/pokemon/llamose/normal.gbapal.lz"

gMonBackPic_Llamose::
	.incbin "graphics/pokemon/llamose/back.4bpp.lz"

gMonShinyPalette_Llamose::
	.incbin "graphics/pokemon/llamose/shiny.gbapal.lz"

gMonIcon_Llamose::
	.incbin "graphics/pokemon/llamose/icon.4bpp"

gMonFootprint_Llamose::
	.incbin "graphics/pokemon/llamose/footprint.1bpp"

gMonFrontPic_Fatte::
	.incbin "graphics/pokemon/fatte/front.4bpp.lz"

gMonPalette_Fatte::
	.incbin "graphics/pokemon/fatte/normal.gbapal.lz"

gMonBackPic_Fatte::
	.incbin "graphics/pokemon/fatte/back.4bpp.lz"

gMonShinyPalette_Fatte::
	.incbin "graphics/pokemon/fatte/shiny.gbapal.lz"

gMonIcon_Fatte::
	.incbin "graphics/pokemon/fatte/icon.4bpp"

gMonFootprint_Fatte::
	.incbin "graphics/pokemon/fatte/footprint.1bpp"

gMonFrontPic_Glotten::
	.incbin "graphics/pokemon/glotten/front.4bpp.lz"

gMonPalette_Glotten::
	.incbin "graphics/pokemon/glotten/normal.gbapal.lz"

gMonBackPic_Glotten::
	.incbin "graphics/pokemon/glotten/back.4bpp.lz"

gMonShinyPalette_Glotten::
	.incbin "graphics/pokemon/glotten/shiny.gbapal.lz"

gMonIcon_Glotten::
	.incbin "graphics/pokemon/glotten/icon.4bpp"

gMonFootprint_Glotten::
	.incbin "graphics/pokemon/glotten/footprint.1bpp"

gMonFrontPic_Stulo::
	.incbin "graphics/pokemon/stulo/front.4bpp.lz"

gMonPalette_Stulo::
	.incbin "graphics/pokemon/stulo/normal.gbapal.lz"

gMonBackPic_Stulo::
	.incbin "graphics/pokemon/stulo/back.4bpp.lz"

gMonShinyPalette_Stulo::
	.incbin "graphics/pokemon/stulo/shiny.gbapal.lz"

gMonIcon_Stulo::
	.incbin "graphics/pokemon/stulo/icon.4bpp"

gMonFootprint_Stulo::
	.incbin "graphics/pokemon/stulo/footprint.1bpp"

gMonFrontPic_Fungio::
	.incbin "graphics/pokemon/fungio/front.4bpp.lz"

gMonPalette_Fungio::
	.incbin "graphics/pokemon/fungio/normal.gbapal.lz"

gMonBackPic_Fungio::
	.incbin "graphics/pokemon/fungio/back.4bpp.lz"

gMonShinyPalette_Fungio::
	.incbin "graphics/pokemon/fungio/shiny.gbapal.lz"

gMonIcon_Fungio::
	.incbin "graphics/pokemon/fungio/icon.4bpp"

gMonFootprint_Fungio::
	.incbin "graphics/pokemon/fungio/footprint.1bpp"

gMonFrontPic_Semilleto::
	.incbin "graphics/pokemon/semilleto/front.4bpp.lz"

gMonPalette_Semilleto::
	.incbin "graphics/pokemon/semilleto/normal.gbapal.lz"

gMonBackPic_Semilleto::
	.incbin "graphics/pokemon/semilleto/back.4bpp.lz"

gMonShinyPalette_Semilleto::
	.incbin "graphics/pokemon/semilleto/shiny.gbapal.lz"

gMonIcon_Semilleto::
	.incbin "graphics/pokemon/semilleto/icon.4bpp"

gMonFootprint_Semilleto::
	.incbin "graphics/pokemon/semilleto/footprint.1bpp"

gMonFrontPic_Flocepan::
	.incbin "graphics/pokemon/flocepan/front.4bpp.lz"

gMonPalette_Flocepan::
	.incbin "graphics/pokemon/flocepan/normal.gbapal.lz"

gMonBackPic_Flocepan::
	.incbin "graphics/pokemon/flocepan/back.4bpp.lz"

gMonShinyPalette_Flocepan::
	.incbin "graphics/pokemon/flocepan/shiny.gbapal.lz"

gMonIcon_Flocepan::
	.incbin "graphics/pokemon/flocepan/icon.4bpp"

gMonFootprint_Flocepan::
	.incbin "graphics/pokemon/flocepan/footprint.1bpp"

gMonFrontPic_Arquidea::
	.incbin "graphics/pokemon/arquidea/front.4bpp.lz"

gMonPalette_Arquidea::
	.incbin "graphics/pokemon/arquidea/normal.gbapal.lz"

gMonBackPic_Arquidea::
	.incbin "graphics/pokemon/arquidea/back.4bpp.lz"

gMonShinyPalette_Arquidea::
	.incbin "graphics/pokemon/arquidea/shiny.gbapal.lz"

gMonIcon_Arquidea::
	.incbin "graphics/pokemon/arquidea/icon.4bpp"

gMonFootprint_Arquidea::
	.incbin "graphics/pokemon/arquidea/footprint.1bpp"

gMonFrontPic_Streek::
	.incbin "graphics/pokemon/streek/front.4bpp.lz"

gMonPalette_Streek::
	.incbin "graphics/pokemon/streek/normal.gbapal.lz"

gMonBackPic_Streek::
	.incbin "graphics/pokemon/streek/back.4bpp.lz"

gMonShinyPalette_Streek::
	.incbin "graphics/pokemon/streek/shiny.gbapal.lz"

gMonIcon_Streek::
	.incbin "graphics/pokemon/streek/icon.4bpp"

gMonFootprint_Streek::
	.incbin "graphics/pokemon/streek/footprint.1bpp"

gMonFrontPic_Loggre::
	.incbin "graphics/pokemon/loggre/front.4bpp.lz"

gMonPalette_Loggre::
	.incbin "graphics/pokemon/loggre/normal.gbapal.lz"

gMonBackPic_Loggre::
	.incbin "graphics/pokemon/loggre/back.4bpp.lz"

gMonShinyPalette_Loggre::
	.incbin "graphics/pokemon/loggre/shiny.gbapal.lz"

gMonIcon_Loggre::
	.incbin "graphics/pokemon/loggre/icon.4bpp"

gMonFootprint_Loggre::
	.incbin "graphics/pokemon/loggre/footprint.1bpp"

gMonFrontPic_Capritle::
	.incbin "graphics/pokemon/capritle/front.4bpp.lz"

gMonPalette_Capritle::
	.incbin "graphics/pokemon/capritle/normal.gbapal.lz"

gMonBackPic_Capritle::
	.incbin "graphics/pokemon/capritle/back.4bpp.lz"

gMonShinyPalette_Capritle::
	.incbin "graphics/pokemon/capritle/shiny.gbapal.lz"

gMonIcon_Capritle::
	.incbin "graphics/pokemon/capritle/icon.4bpp"

gMonFootprint_Capritle::
	.incbin "graphics/pokemon/capritle/footprint.1bpp"

gMonFrontPic_Deeretle::
	.incbin "graphics/pokemon/deeretle/front.4bpp.lz"

gMonPalette_Deeretle::
	.incbin "graphics/pokemon/deeretle/normal.gbapal.lz"

gMonBackPic_Deeretle::
	.incbin "graphics/pokemon/deeretle/back.4bpp.lz"

gMonShinyPalette_Deeretle::
	.incbin "graphics/pokemon/deeretle/shiny.gbapal.lz"

gMonIcon_Deeretle::
	.incbin "graphics/pokemon/deeretle/icon.4bpp"

gMonFootprint_Deeretle::
	.incbin "graphics/pokemon/deeretle/footprint.1bpp"

gMonFrontPic_Armorito::
	.incbin "graphics/pokemon/armorito/front.4bpp.lz"

gMonPalette_Armorito::
	.incbin "graphics/pokemon/armorito/normal.gbapal.lz"

gMonBackPic_Armorito::
	.incbin "graphics/pokemon/armorito/back.4bpp.lz"

gMonShinyPalette_Armorito::
	.incbin "graphics/pokemon/armorito/shiny.gbapal.lz"

gMonIcon_Armorito::
	.incbin "graphics/pokemon/armorito/icon.4bpp"

gMonFootprint_Armorito::
	.incbin "graphics/pokemon/armorito/footprint.1bpp"

gMonFrontPic_Armorazo::
	.incbin "graphics/pokemon/armorazo/front.4bpp.lz"

gMonPalette_Armorazo::
	.incbin "graphics/pokemon/armorazo/normal.gbapal.lz"

gMonBackPic_Armorazo::
	.incbin "graphics/pokemon/armorazo/back.4bpp.lz"

gMonShinyPalette_Armorazo::
	.incbin "graphics/pokemon/armorazo/shiny.gbapal.lz"

gMonIcon_Armorazo::
	.incbin "graphics/pokemon/armorazo/icon.4bpp"

gMonFootprint_Armorazo::
	.incbin "graphics/pokemon/armorazo/footprint.1bpp"

gMonFrontPic_Ankori::
	.incbin "graphics/pokemon/ankori/front.4bpp.lz"

gMonPalette_Ankori::
	.incbin "graphics/pokemon/ankori/normal.gbapal.lz"

gMonBackPic_Ankori::
	.incbin "graphics/pokemon/ankori/back.4bpp.lz"

gMonShinyPalette_Ankori::
	.incbin "graphics/pokemon/ankori/shiny.gbapal.lz"

gMonIcon_Ankori::
	.incbin "graphics/pokemon/ankori/icon.4bpp"

gMonFootprint_Ankori::
	.incbin "graphics/pokemon/ankori/footprint.1bpp"

gMonFrontPic_Fureep::
	.incbin "graphics/pokemon/fureep/front.4bpp.lz"

gMonPalette_Fureep::
	.incbin "graphics/pokemon/fureep/normal.gbapal.lz"

gMonBackPic_Fureep::
	.incbin "graphics/pokemon/fureep/back.4bpp.lz"

gMonShinyPalette_Fureep::
	.incbin "graphics/pokemon/fureep/shiny.gbapal.lz"

gMonIcon_Fureep::
	.incbin "graphics/pokemon/fureep/icon.4bpp"

gMonFootprint_Fureep::
	.incbin "graphics/pokemon/fureep/footprint.1bpp"

gMonFrontPic_Pulsul::
	.incbin "graphics/pokemon/pulsul/front.4bpp.lz"

gMonPalette_Pulsul::
	.incbin "graphics/pokemon/pulsul/normal.gbapal.lz"

gMonBackPic_Pulsul::
	.incbin "graphics/pokemon/pulsul/back.4bpp.lz"

gMonShinyPalette_Pulsul::
	.incbin "graphics/pokemon/pulsul/shiny.gbapal.lz"

gMonIcon_Pulsul::
	.incbin "graphics/pokemon/pulsul/icon.4bpp"

gMonFootprint_Pulsul::
	.incbin "graphics/pokemon/pulsul/footprint.1bpp"

gMonFrontPic_Koropul::
	.incbin "graphics/pokemon/koropul/front.4bpp.lz"

gMonPalette_Koropul::
	.incbin "graphics/pokemon/koropul/normal.gbapal.lz"

gMonBackPic_Koropul::
	.incbin "graphics/pokemon/koropul/back.4bpp.lz"

gMonShinyPalette_Koropul::
	.incbin "graphics/pokemon/koropul/shiny.gbapal.lz"

gMonIcon_Koropul::
	.incbin "graphics/pokemon/koropul/icon.4bpp"

gMonFootprint_Koropul::
	.incbin "graphics/pokemon/koropul/footprint.1bpp"

gMonFrontPic_Darkoon::
	.incbin "graphics/pokemon/darkoon/front.4bpp.lz"

gMonPalette_Darkoon::
	.incbin "graphics/pokemon/darkoon/normal.gbapal.lz"

gMonBackPic_Darkoon::
	.incbin "graphics/pokemon/darkoon/back.4bpp.lz"

gMonShinyPalette_Darkoon::
	.incbin "graphics/pokemon/darkoon/shiny.gbapal.lz"

gMonIcon_Darkoon::
	.incbin "graphics/pokemon/darkoon/icon.4bpp"

gMonFootprint_Darkoon::
	.incbin "graphics/pokemon/darkoon/footprint.1bpp"

gMonFrontPic_Huntoon::
	.incbin "graphics/pokemon/huntoon/front.4bpp.lz"

gMonPalette_Huntoon::
	.incbin "graphics/pokemon/huntoon/normal.gbapal.lz"

gMonBackPic_Huntoon::
	.incbin "graphics/pokemon/huntoon/back.4bpp.lz"

gMonShinyPalette_Huntoon::
	.incbin "graphics/pokemon/huntoon/shiny.gbapal.lz"

gMonIcon_Huntoon::
	.incbin "graphics/pokemon/huntoon/icon.4bpp"

gMonFootprint_Huntoon::
	.incbin "graphics/pokemon/huntoon/footprint.1bpp"

gMonFrontPic_Tikika::
	.incbin "graphics/pokemon/tikika/front.4bpp.lz"

gMonPalette_Tikika::
	.incbin "graphics/pokemon/tikika/normal.gbapal.lz"

gMonBackPic_Tikika::
	.incbin "graphics/pokemon/tikika/back.4bpp.lz"

gMonShinyPalette_Tikika::
	.incbin "graphics/pokemon/tikika/shiny.gbapal.lz"

gMonIcon_Tikika::
	.incbin "graphics/pokemon/tikika/icon.4bpp"

gMonFootprint_Tikika::
	.incbin "graphics/pokemon/tikika/footprint.1bpp"

gMonFrontPic_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/front.4bpp.lz"

gMonPalette_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/normal.gbapal.lz"

gMonBackPic_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/back.4bpp.lz"

gMonShinyPalette_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/shiny.gbapal.lz"

gMonIcon_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/icon.4bpp"

gMonFootprint_Tikiriki::
	.incbin "graphics/pokemon/tikiriki/footprint.1bpp"

gMonFrontPic_Poocher::
	.incbin "graphics/pokemon/poocher/front.4bpp.lz"

gMonPalette_Poocher::
	.incbin "graphics/pokemon/poocher/normal.gbapal.lz"

gMonBackPic_Poocher::
	.incbin "graphics/pokemon/poocher/back.4bpp.lz"

gMonShinyPalette_Poocher::
	.incbin "graphics/pokemon/poocher/shiny.gbapal.lz"

gMonIcon_Poocher::
	.incbin "graphics/pokemon/poocher/icon.4bpp"

gMonFootprint_Poocher::
	.incbin "graphics/pokemon/poocher/footprint.1bpp"

gMonFrontPic_Wappy::
	.incbin "graphics/pokemon/wappy/front.4bpp.lz"

gMonPalette_Wappy::
	.incbin "graphics/pokemon/wappy/normal.gbapal.lz"

gMonBackPic_Wappy::
	.incbin "graphics/pokemon/wappy/back.4bpp.lz"

gMonShinyPalette_Wappy::
	.incbin "graphics/pokemon/wappy/shiny.gbapal.lz"

gMonIcon_Wappy::
	.incbin "graphics/pokemon/wappy/icon.4bpp"

gMonFootprint_Wappy::
	.incbin "graphics/pokemon/wappy/footprint.1bpp"

gMonFrontPic_Riwoof::
	.incbin "graphics/pokemon/riwoof/front.4bpp.lz"

gMonPalette_Riwoof::
	.incbin "graphics/pokemon/riwoof/normal.gbapal.lz"

gMonBackPic_Riwoof::
	.incbin "graphics/pokemon/riwoof/back.4bpp.lz"

gMonShinyPalette_Riwoof::
	.incbin "graphics/pokemon/riwoof/shiny.gbapal.lz"

gMonIcon_Riwoof::
	.incbin "graphics/pokemon/riwoof/icon.4bpp"

gMonFootprint_Riwoof::
	.incbin "graphics/pokemon/riwoof/footprint.1bpp"

gMonFrontPic_Ivoro::
	.incbin "graphics/pokemon/ivoro/front.4bpp.lz"

gMonPalette_Ivoro::
	.incbin "graphics/pokemon/ivoro/normal.gbapal.lz"

gMonBackPic_Ivoro::
	.incbin "graphics/pokemon/ivoro/back.4bpp.lz"

gMonShinyPalette_Ivoro::
	.incbin "graphics/pokemon/ivoro/shiny.gbapal.lz"

gMonIcon_Ivoro::
	.incbin "graphics/pokemon/ivoro/icon.4bpp"

gMonFootprint_Ivoro::
	.incbin "graphics/pokemon/ivoro/footprint.1bpp"

gMonFrontPic_Dreamo::
	.incbin "graphics/pokemon/dreamo/front.4bpp.lz"

gMonPalette_Dreamo::
	.incbin "graphics/pokemon/dreamo/normal.gbapal.lz"

gMonBackPic_Dreamo::
	.incbin "graphics/pokemon/dreamo/back.4bpp.lz"

gMonShinyPalette_Dreamo::
	.incbin "graphics/pokemon/dreamo/shiny.gbapal.lz"

gMonIcon_Dreamo::
	.incbin "graphics/pokemon/dreamo/icon.4bpp"

gMonFootprint_Dreamo::
	.incbin "graphics/pokemon/dreamo/footprint.1bpp"

gMonFrontPic_Mammare::
	.incbin "graphics/pokemon/mammare/front.4bpp.lz"

gMonPalette_Mammare::
	.incbin "graphics/pokemon/mammare/normal.gbapal.lz"

gMonBackPic_Mammare::
	.incbin "graphics/pokemon/mammare/back.4bpp.lz"

gMonShinyPalette_Mammare::
	.incbin "graphics/pokemon/mammare/shiny.gbapal.lz"

gMonIcon_Mammare::
	.incbin "graphics/pokemon/mammare/icon.4bpp"

gMonFootprint_Mammare::
	.incbin "graphics/pokemon/mammare/footprint.1bpp"

gMonFrontPic_Kango::
	.incbin "graphics/pokemon/kango/front.4bpp.lz"

gMonPalette_Kango::
	.incbin "graphics/pokemon/kango/normal.gbapal.lz"

gMonBackPic_Kango::
	.incbin "graphics/pokemon/kango/back.4bpp.lz"

gMonShinyPalette_Kango::
	.incbin "graphics/pokemon/kango/shiny.gbapal.lz"

gMonIcon_Kango::
	.incbin "graphics/pokemon/kango/icon.4bpp"

gMonFootprint_Kango::
	.incbin "graphics/pokemon/kango/footprint.1bpp"

gMonFrontPic_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/front.4bpp.lz"

gMonPalette_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/normal.gbapal.lz"

gMonBackPic_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/back.4bpp.lz"

gMonShinyPalette_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/shiny.gbapal.lz"

gMonIcon_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/icon.4bpp"

gMonFootprint_Kinboxo::
	.incbin "graphics/pokemon/kinboxo/footprint.1bpp"

gMonFrontPic_Punchzo::
	.incbin "graphics/pokemon/punchzo/front.4bpp.lz"

gMonPalette_Punchzo::
	.incbin "graphics/pokemon/punchzo/normal.gbapal.lz"

gMonBackPic_Punchzo::
	.incbin "graphics/pokemon/punchzo/back.4bpp.lz"

gMonShinyPalette_Punchzo::
	.incbin "graphics/pokemon/punchzo/shiny.gbapal.lz"

gMonIcon_Punchzo::
	.incbin "graphics/pokemon/punchzo/icon.4bpp"

gMonFootprint_Punchzo::
	.incbin "graphics/pokemon/punchzo/footprint.1bpp"

gMonFrontPic_Fentee::
	.incbin "graphics/pokemon/fentee/front.4bpp.lz"

gMonPalette_Fentee::
	.incbin "graphics/pokemon/fentee/normal.gbapal.lz"

gMonBackPic_Fentee::
	.incbin "graphics/pokemon/fentee/back.4bpp.lz"

gMonShinyPalette_Fentee::
	.incbin "graphics/pokemon/fentee/shiny.gbapal.lz"

gMonIcon_Fentee::
	.incbin "graphics/pokemon/fentee/icon.4bpp"

gMonFootprint_Fentee::
	.incbin "graphics/pokemon/fentee/footprint.1bpp"

gMonFrontPic_Helento::
	.incbin "graphics/pokemon/helento/front.4bpp.lz"

gMonPalette_Helento::
	.incbin "graphics/pokemon/helento/normal.gbapal.lz"

gMonBackPic_Helento::
	.incbin "graphics/pokemon/helento/back.4bpp.lz"

gMonShinyPalette_Helento::
	.incbin "graphics/pokemon/helento/shiny.gbapal.lz"

gMonIcon_Helento::
	.incbin "graphics/pokemon/helento/icon.4bpp"

gMonFootprint_Helento::
	.incbin "graphics/pokemon/helento/footprint.1bpp"

gMonFrontPic_Felechoe::
	.incbin "graphics/pokemon/felechoe/front.4bpp.lz"

gMonPalette_Felechoe::
	.incbin "graphics/pokemon/felechoe/normal.gbapal.lz"

gMonBackPic_Felechoe::
	.incbin "graphics/pokemon/felechoe/back.4bpp.lz"

gMonShinyPalette_Felechoe::
	.incbin "graphics/pokemon/felechoe/shiny.gbapal.lz"

gMonIcon_Felechoe::
	.incbin "graphics/pokemon/felechoe/icon.4bpp"

gMonFootprint_Felechoe::
	.incbin "graphics/pokemon/felechoe/footprint.1bpp"

gMonFrontPic_Pikish::
	.incbin "graphics/pokemon/pikish/front.4bpp.lz"

gMonPalette_Pikish::
	.incbin "graphics/pokemon/pikish/normal.gbapal.lz"

gMonBackPic_Pikish::
	.incbin "graphics/pokemon/pikish/back.4bpp.lz"

gMonShinyPalette_Pikish::
	.incbin "graphics/pokemon/pikish/shiny.gbapal.lz"

gMonIcon_Pikish::
	.incbin "graphics/pokemon/pikish/icon.4bpp"

gMonFootprint_Pikish::
	.incbin "graphics/pokemon/pikish/footprint.1bpp"

gMonFrontPic_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/front.4bpp.lz"

gMonPalette_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/normal.gbapal.lz"

gMonBackPic_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/back.4bpp.lz"

gMonShinyPalette_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/shiny.gbapal.lz"

gMonIcon_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/icon.4bpp"

gMonFootprint_Lionegosh::
	.incbin "graphics/pokemon/lionegosh/footprint.1bpp"

gMonFrontPic_Jonic::
	.incbin "graphics/pokemon/jonic/front.4bpp.lz"

gMonPalette_Jonic::
	.incbin "graphics/pokemon/jonic/normal.gbapal.lz"

gMonBackPic_Jonic::
	.incbin "graphics/pokemon/jonic/back.4bpp.lz"

gMonShinyPalette_Jonic::
	.incbin "graphics/pokemon/jonic/shiny.gbapal.lz"

gMonIcon_Jonic::
	.incbin "graphics/pokemon/jonic/icon.4bpp"

gMonFootprint_Jonic::
	.incbin "graphics/pokemon/jonic/footprint.1bpp"

gMonFrontPic_Doric::
	.incbin "graphics/pokemon/doric/front.4bpp.lz"

gMonPalette_Doric::
	.incbin "graphics/pokemon/doric/normal.gbapal.lz"

gMonBackPic_Doric::
	.incbin "graphics/pokemon/doric/back.4bpp.lz"

gMonShinyPalette_Doric::
	.incbin "graphics/pokemon/doric/shiny.gbapal.lz"

gMonIcon_Doric::
	.incbin "graphics/pokemon/doric/icon.4bpp"

gMonFootprint_Doric::
	.incbin "graphics/pokemon/doric/footprint.1bpp"

gMonFrontPic_Corint::
	.incbin "graphics/pokemon/corint/front.4bpp.lz"

gMonPalette_Corint::
	.incbin "graphics/pokemon/corint/normal.gbapal.lz"

gMonBackPic_Corint::
	.incbin "graphics/pokemon/corint/back.4bpp.lz"

gMonShinyPalette_Corint::
	.incbin "graphics/pokemon/corint/shiny.gbapal.lz"

gMonIcon_Corint::
	.incbin "graphics/pokemon/corint/icon.4bpp"

gMonFootprint_Corint::
	.incbin "graphics/pokemon/corint/footprint.1bpp"

gMonFrontPic_Flachow::
	.incbin "graphics/pokemon/flachow/front.4bpp.lz"

gMonPalette_Flachow::
	.incbin "graphics/pokemon/flachow/normal.gbapal.lz"

gMonBackPic_Flachow::
	.incbin "graphics/pokemon/flachow/back.4bpp.lz"

gMonShinyPalette_Flachow::
	.incbin "graphics/pokemon/flachow/shiny.gbapal.lz"

gMonIcon_Flachow::
	.incbin "graphics/pokemon/flachow/icon.4bpp"

gMonFootprint_Flachow::
	.incbin "graphics/pokemon/flachow/footprint.1bpp"

gMonFrontPic_Furning::
	.incbin "graphics/pokemon/furning/front.4bpp.lz"

gMonPalette_Furning::
	.incbin "graphics/pokemon/furning/normal.gbapal.lz"

gMonBackPic_Furning::
	.incbin "graphics/pokemon/furning/back.4bpp.lz"

gMonShinyPalette_Furning::
	.incbin "graphics/pokemon/furning/shiny.gbapal.lz"

gMonIcon_Furning::
	.incbin "graphics/pokemon/furning/icon.4bpp"

gMonFootprint_Furning::
	.incbin "graphics/pokemon/furning/footprint.1bpp"

gMonFrontPic_Crabix::
	.incbin "graphics/pokemon/crabix/front.4bpp.lz"

gMonPalette_Crabix::
	.incbin "graphics/pokemon/crabix/normal.gbapal.lz"

gMonBackPic_Crabix::
	.incbin "graphics/pokemon/crabix/back.4bpp.lz"

gMonShinyPalette_Crabix::
	.incbin "graphics/pokemon/crabix/shiny.gbapal.lz"

gMonIcon_Crabix::
	.incbin "graphics/pokemon/crabix/icon.4bpp"

gMonFootprint_Crabix::
	.incbin "graphics/pokemon/crabix/footprint.1bpp"

gMonFrontPic_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/front.4bpp.lz"

gMonPalette_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/normal.gbapal.lz"

gMonBackPic_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/back.4bpp.lz"

gMonShinyPalette_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/shiny.gbapal.lz"

gMonIcon_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/icon.4bpp"

gMonFootprint_Dzoibix::
	.incbin "graphics/pokemon/dzoïbix/footprint.1bpp"

gMonFrontPic_Spingen::
	.incbin "graphics/pokemon/spingen/front.4bpp.lz"

gMonPalette_Spingen::
	.incbin "graphics/pokemon/spingen/normal.gbapal.lz"

gMonBackPic_Spingen::
	.incbin "graphics/pokemon/spingen/back.4bpp.lz"

gMonShinyPalette_Spingen::
	.incbin "graphics/pokemon/spingen/shiny.gbapal.lz"

gMonIcon_Spingen::
	.incbin "graphics/pokemon/spingen/icon.4bpp"

gMonFootprint_Spingen::
	.incbin "graphics/pokemon/spingen/footprint.1bpp"

gMonFrontPic_Duosgen::
	.incbin "graphics/pokemon/duosgen/front.4bpp.lz"

gMonPalette_Duosgen::
	.incbin "graphics/pokemon/duosgen/normal.gbapal.lz"

gMonBackPic_Duosgen::
	.incbin "graphics/pokemon/duosgen/back.4bpp.lz"

gMonShinyPalette_Duosgen::
	.incbin "graphics/pokemon/duosgen/shiny.gbapal.lz"

gMonIcon_Duosgen::
	.incbin "graphics/pokemon/duosgen/icon.4bpp"

gMonFootprint_Duosgen::
	.incbin "graphics/pokemon/duosgen/footprint.1bpp"

gMonFrontPic_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/front.4bpp.lz"

gMonPalette_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/normal.gbapal.lz"

gMonBackPic_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/back.4bpp.lz"

gMonShinyPalette_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/shiny.gbapal.lz"

gMonIcon_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/icon.4bpp"

gMonFootprint_Blahdalah::
	.incbin "graphics/pokemon/blahdalah/footprint.1bpp"

gMonFrontPic_Bubel::
	.incbin "graphics/pokemon/bubel/front.4bpp.lz"

gMonPalette_Bubel::
	.incbin "graphics/pokemon/bubel/normal.gbapal.lz"

gMonBackPic_Bubel::
	.incbin "graphics/pokemon/bubel/back.4bpp.lz"

gMonShinyPalette_Bubel::
	.incbin "graphics/pokemon/bubel/shiny.gbapal.lz"

gMonIcon_Bubel::
	.incbin "graphics/pokemon/bubel/icon.4bpp"

gMonFootprint_Bubel::
	.incbin "graphics/pokemon/bubel/footprint.1bpp"

gMonFrontPic_Scentbird::
	.incbin "graphics/pokemon/scentbird/front.4bpp.lz"

gMonPalette_Scentbird::
	.incbin "graphics/pokemon/scentbird/normal.gbapal.lz"

gMonBackPic_Scentbird::
	.incbin "graphics/pokemon/scentbird/back.4bpp.lz"

gMonShinyPalette_Scentbird::
	.incbin "graphics/pokemon/scentbird/shiny.gbapal.lz"

gMonIcon_Scentbird::
	.incbin "graphics/pokemon/scentbird/icon.4bpp"

gMonFootprint_Scentbird::
	.incbin "graphics/pokemon/scentbird/footprint.1bpp"

gMonFrontPic_Norion::
	.incbin "graphics/pokemon/norion/front.4bpp.lz"

gMonPalette_Norion::
	.incbin "graphics/pokemon/norion/normal.gbapal.lz"

gMonBackPic_Norion::
	.incbin "graphics/pokemon/norion/back.4bpp.lz"

gMonShinyPalette_Norion::
	.incbin "graphics/pokemon/norion/shiny.gbapal.lz"

gMonIcon_Norion::
	.incbin "graphics/pokemon/norion/icon.4bpp"

gMonFootprint_Norion::
	.incbin "graphics/pokemon/norion/footprint.1bpp"

gMonFrontPic_Phantan::
	.incbin "graphics/pokemon/phantan/front.4bpp.lz"

gMonPalette_Phantan::
	.incbin "graphics/pokemon/phantan/normal.gbapal.lz"

gMonBackPic_Phantan::
	.incbin "graphics/pokemon/phantan/back.4bpp.lz"

gMonShinyPalette_Phantan::
	.incbin "graphics/pokemon/phantan/shiny.gbapal.lz"

gMonIcon_Phantan::
	.incbin "graphics/pokemon/phantan/icon.4bpp"

gMonFootprint_Phantan::
	.incbin "graphics/pokemon/phantan/footprint.1bpp"

gMonFrontPic_Salama::
	.incbin "graphics/pokemon/salama/front.4bpp.lz"

gMonPalette_Salama::
	.incbin "graphics/pokemon/salama/normal.gbapal.lz"

gMonBackPic_Salama::
	.incbin "graphics/pokemon/salama/back.4bpp.lz"

gMonShinyPalette_Salama::
	.incbin "graphics/pokemon/salama/shiny.gbapal.lz"

gMonIcon_Salama::
	.incbin "graphics/pokemon/salama/icon.4bpp"

gMonFootprint_Salama::
	.incbin "graphics/pokemon/salama/footprint.1bpp"

gMonFrontPic_Mantiga::
	.incbin "graphics/pokemon/mantiga/front.4bpp.lz"

gMonPalette_Mantiga::
	.incbin "graphics/pokemon/mantiga/normal.gbapal.lz"

gMonBackPic_Mantiga::
	.incbin "graphics/pokemon/mantiga/back.4bpp.lz"

gMonShinyPalette_Mantiga::
	.incbin "graphics/pokemon/mantiga/shiny.gbapal.lz"

gMonIcon_Mantiga::
	.incbin "graphics/pokemon/mantiga/icon.4bpp"

gMonFootprint_Mantiga::
	.incbin "graphics/pokemon/mantiga/footprint.1bpp"

gMonFrontPic_Gallum::
	.incbin "graphics/pokemon/gallum/front.4bpp.lz"

gMonPalette_Gallum::
	.incbin "graphics/pokemon/gallum/normal.gbapal.lz"

gMonBackPic_Gallum::
	.incbin "graphics/pokemon/gallum/back.4bpp.lz"

gMonShinyPalette_Gallum::
	.incbin "graphics/pokemon/gallum/shiny.gbapal.lz"

gMonIcon_Gallum::
	.incbin "graphics/pokemon/gallum/icon.4bpp"

gMonFootprint_Gallum::
	.incbin "graphics/pokemon/gallum/footprint.1bpp"

gMonFrontPic_Airdiv::
	.incbin "graphics/pokemon/airdiv/front.4bpp.lz"

gMonPalette_Airdiv::
	.incbin "graphics/pokemon/airdiv/normal.gbapal.lz"

gMonBackPic_Airdiv::
	.incbin "graphics/pokemon/airdiv/back.4bpp.lz"

gMonShinyPalette_Airdiv::
	.incbin "graphics/pokemon/airdiv/shiny.gbapal.lz"

gMonIcon_Airdiv::
	.incbin "graphics/pokemon/airdiv/icon.4bpp"

gMonFootprint_Airdiv::
	.incbin "graphics/pokemon/airdiv/footprint.1bpp"

gMonFrontPic_Gappy::
	.incbin "graphics/pokemon/gappy/front.4bpp.lz"

gMonPalette_Gappy::
	.incbin "graphics/pokemon/gappy/normal.gbapal.lz"

gMonBackPic_Gappy::
	.incbin "graphics/pokemon/gappy/back.4bpp.lz"

gMonShinyPalette_Gappy::
	.incbin "graphics/pokemon/gappy/shiny.gbapal.lz"

gMonIcon_Gappy::
	.incbin "graphics/pokemon/gappy/icon.4bpp"

gMonFootprint_Gappy::
	.incbin "graphics/pokemon/gappy/footprint.1bpp"

gMonFrontPic_Ninnin::
	.incbin "graphics/pokemon/ninnin/front.4bpp.lz"

gMonPalette_Ninnin::
	.incbin "graphics/pokemon/ninnin/normal.gbapal.lz"

gMonBackPic_Ninnin::
	.incbin "graphics/pokemon/ninnin/back.4bpp.lz"

gMonShinyPalette_Ninnin::
	.incbin "graphics/pokemon/ninnin/shiny.gbapal.lz"

gMonIcon_Ninnin::
	.incbin "graphics/pokemon/ninnin/icon.4bpp"

gMonFootprint_Ninnin::
	.incbin "graphics/pokemon/ninnin/footprint.1bpp"

gMonFrontPic_Surhorn::
	.incbin "graphics/pokemon/surhorn/front.4bpp.lz"

gMonPalette_Surhorn::
	.incbin "graphics/pokemon/surhorn/normal.gbapal.lz"

gMonBackPic_Surhorn::
	.incbin "graphics/pokemon/surhorn/back.4bpp.lz"

gMonShinyPalette_Surhorn::
	.incbin "graphics/pokemon/surhorn/shiny.gbapal.lz"

gMonIcon_Surhorn::
	.incbin "graphics/pokemon/surhorn/icon.4bpp"

gMonFootprint_Surhorn::
	.incbin "graphics/pokemon/surhorn/footprint.1bpp"

gMonFrontPic_Shega::
	.incbin "graphics/pokemon/shega/front.4bpp.lz"

gMonPalette_Shega::
	.incbin "graphics/pokemon/shega/normal.gbapal.lz"

gMonBackPic_Shega::
	.incbin "graphics/pokemon/shega/back.4bpp.lz"

gMonShinyPalette_Shega::
	.incbin "graphics/pokemon/shega/shiny.gbapal.lz"

gMonIcon_Shega::
	.incbin "graphics/pokemon/shega/icon.4bpp"

gMonFootprint_Shega::
	.incbin "graphics/pokemon/shega/footprint.1bpp"

gMonFrontPic_Zeeco::
	.incbin "graphics/pokemon/zeeco/front.4bpp.lz"

gMonPalette_Zeeco::
	.incbin "graphics/pokemon/zeeco/normal.gbapal.lz"

gMonBackPic_Zeeco::
	.incbin "graphics/pokemon/zeeco/back.4bpp.lz"

gMonShinyPalette_Zeeco::
	.incbin "graphics/pokemon/zeeco/shiny.gbapal.lz"

gMonIcon_Zeeco::
	.incbin "graphics/pokemon/zeeco/icon.4bpp"

gMonFootprint_Zeeco::
	.incbin "graphics/pokemon/zeeco/footprint.1bpp"

gMonFrontPic_Psirilla::
	.incbin "graphics/pokemon/psirilla/front.4bpp.lz"

gMonPalette_Psirilla::
	.incbin "graphics/pokemon/psirilla/normal.gbapal.lz"

gMonBackPic_Psirilla::
	.incbin "graphics/pokemon/psirilla/back.4bpp.lz"

gMonShinyPalette_Psirilla::
	.incbin "graphics/pokemon/psirilla/shiny.gbapal.lz"

gMonIcon_Psirilla::
	.incbin "graphics/pokemon/psirilla/icon.4bpp"

gMonFootprint_Psirilla::
	.incbin "graphics/pokemon/psirilla/footprint.1bpp"

gMonFrontPic_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/front.4bpp.lz"

gMonPalette_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/normal.gbapal.lz"

gMonBackPic_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/back.4bpp.lz"

gMonShinyPalette_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/shiny.gbapal.lz"

gMonIcon_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/icon.4bpp"

gMonFootprint_Mechcrab::
	.incbin "graphics/pokemon/mechcrab/footprint.1bpp"

gMonFrontPic_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/front.4bpp.lz"

gMonPalette_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/normal.gbapal.lz"

gMonBackPic_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/back.4bpp.lz"

gMonShinyPalette_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/shiny.gbapal.lz"

gMonIcon_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/icon.4bpp"

gMonFootprint_Bobcrab::
	.incbin "graphics/pokemon/bobcrab/footprint.1bpp"

gMonFrontPic_Spiki::
	.incbin "graphics/pokemon/spiki/front.4bpp.lz"

gMonPalette_Spiki::
	.incbin "graphics/pokemon/spiki/normal.gbapal.lz"

gMonBackPic_Spiki::
	.incbin "graphics/pokemon/spiki/back.4bpp.lz"

gMonShinyPalette_Spiki::
	.incbin "graphics/pokemon/spiki/shiny.gbapal.lz"

gMonIcon_Spiki::
	.incbin "graphics/pokemon/spiki/icon.4bpp"

gMonFootprint_Spiki::
	.incbin "graphics/pokemon/spiki/footprint.1bpp"

gMonFrontPic_Eliko::
	.incbin "graphics/pokemon/eliko/front.4bpp.lz"

gMonPalette_Eliko::
	.incbin "graphics/pokemon/eliko/normal.gbapal.lz"

gMonBackPic_Eliko::
	.incbin "graphics/pokemon/eliko/back.4bpp.lz"

gMonShinyPalette_Eliko::
	.incbin "graphics/pokemon/eliko/shiny.gbapal.lz"

gMonIcon_Eliko::
	.incbin "graphics/pokemon/eliko/icon.4bpp"

gMonFootprint_Eliko::
	.incbin "graphics/pokemon/eliko/footprint.1bpp"

gMonFrontPic_Sespiral::
	.incbin "graphics/pokemon/sespiral/front.4bpp.lz"

gMonPalette_Sespiral::
	.incbin "graphics/pokemon/sespiral/normal.gbapal.lz"

gMonBackPic_Sespiral::
	.incbin "graphics/pokemon/sespiral/back.4bpp.lz"

gMonShinyPalette_Sespiral::
	.incbin "graphics/pokemon/sespiral/shiny.gbapal.lz"

gMonIcon_Sespiral::
	.incbin "graphics/pokemon/sespiral/icon.4bpp"

gMonFootprint_Sespiral::
	.incbin "graphics/pokemon/sespiral/footprint.1bpp"

gMonFrontPic_Dendriral::
	.incbin "graphics/pokemon/dendriral/front.4bpp.lz"

gMonPalette_Dendriral::
	.incbin "graphics/pokemon/dendriral/normal.gbapal.lz"

gMonBackPic_Dendriral::
	.incbin "graphics/pokemon/dendriral/back.4bpp.lz"

gMonShinyPalette_Dendriral::
	.incbin "graphics/pokemon/dendriral/shiny.gbapal.lz"

gMonIcon_Dendriral::
	.incbin "graphics/pokemon/dendriral/icon.4bpp"

gMonFootprint_Dendriral::
	.incbin "graphics/pokemon/dendriral/footprint.1bpp"

gMonFrontPic_Vugoo::
	.incbin "graphics/pokemon/vugoo/front.4bpp.lz"

gMonPalette_Vugoo::
	.incbin "graphics/pokemon/vugoo/normal.gbapal.lz"

gMonBackPic_Vugoo::
	.incbin "graphics/pokemon/vugoo/back.4bpp.lz"

gMonShinyPalette_Vugoo::
	.incbin "graphics/pokemon/vugoo/shiny.gbapal.lz"

gMonIcon_Vugoo::
	.incbin "graphics/pokemon/vugoo/icon.4bpp"

gMonFootprint_Vugoo::
	.incbin "graphics/pokemon/vugoo/footprint.1bpp"

gMonFrontPic_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/front.4bpp.lz"

gMonPalette_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/normal.gbapal.lz"

gMonBackPic_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/back.4bpp.lz"

gMonShinyPalette_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/shiny.gbapal.lz"

gMonIcon_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/icon.4bpp"

gMonFootprint_Monkoodu::
	.incbin "graphics/pokemon/monkoodu/footprint.1bpp"

gMonFrontPic_Klevalt::
	.incbin "graphics/pokemon/klevalt/front.4bpp.lz"

gMonPalette_Klevalt::
	.incbin "graphics/pokemon/klevalt/normal.gbapal.lz"

gMonBackPic_Klevalt::
	.incbin "graphics/pokemon/klevalt/back.4bpp.lz"

gMonShinyPalette_Klevalt::
	.incbin "graphics/pokemon/klevalt/shiny.gbapal.lz"

gMonIcon_Klevalt::
	.incbin "graphics/pokemon/klevalt/icon.4bpp"

gMonFootprint_Klevalt::
	.incbin "graphics/pokemon/klevalt/footprint.1bpp"

gMonFrontPic_Klesung::
	.incbin "graphics/pokemon/klesung/front.4bpp.lz"

gMonPalette_Klesung::
	.incbin "graphics/pokemon/klesung/normal.gbapal.lz"

gMonBackPic_Klesung::
	.incbin "graphics/pokemon/klesung/back.4bpp.lz"

gMonShinyPalette_Klesung::
	.incbin "graphics/pokemon/klesung/shiny.gbapal.lz"

gMonIcon_Klesung::
	.incbin "graphics/pokemon/klesung/icon.4bpp"

gMonFootprint_Klesung::
	.incbin "graphics/pokemon/klesung/footprint.1bpp"

gMonFrontPic_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/front.4bpp.lz"

gMonPalette_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/normal.gbapal.lz"

gMonBackPic_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/back.4bpp.lz"

gMonShinyPalette_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/shiny.gbapal.lz"

gMonIcon_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/icon.4bpp"

gMonFootprint_Sikedonke::
	.incbin "graphics/pokemon/sikedonke/footprint.1bpp"

gMonFrontPic_Powergas::
	.incbin "graphics/pokemon/powergas/front.4bpp.lz"

gMonPalette_Powergas::
	.incbin "graphics/pokemon/powergas/normal.gbapal.lz"

gMonBackPic_Powergas::
	.incbin "graphics/pokemon/powergas/back.4bpp.lz"

gMonShinyPalette_Powergas::
	.incbin "graphics/pokemon/powergas/shiny.gbapal.lz"

gMonIcon_Powergas::
	.incbin "graphics/pokemon/powergas/icon.4bpp"

gMonFootprint_Powergas::
	.incbin "graphics/pokemon/powergas/footprint.1bpp"

gMonFrontPic_Pasqall::
	.incbin "graphics/pokemon/pasqall/front.4bpp.lz"

gMonPalette_Pasqall::
	.incbin "graphics/pokemon/pasqall/normal.gbapal.lz"

gMonBackPic_Pasqall::
	.incbin "graphics/pokemon/pasqall/back.4bpp.lz"

gMonShinyPalette_Pasqall::
	.incbin "graphics/pokemon/pasqall/shiny.gbapal.lz"

gMonIcon_Pasqall::
	.incbin "graphics/pokemon/pasqall/icon.4bpp"

gMonFootprint_Pasqall::
	.incbin "graphics/pokemon/pasqall/footprint.1bpp"

gMonFrontPic_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/front.4bpp.lz"

gMonPalette_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/normal.gbapal.lz"

gMonBackPic_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/back.4bpp.lz"

gMonShinyPalette_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/shiny.gbapal.lz"

gMonIcon_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/icon.4bpp"

gMonFootprint_Rocorrodo::
	.incbin "graphics/pokemon/rocorrodo/footprint.1bpp"

gMonFrontPic_Cornodro::
	.incbin "graphics/pokemon/cornodro/front.4bpp.lz"

gMonPalette_Cornodro::
	.incbin "graphics/pokemon/cornodro/normal.gbapal.lz"

gMonBackPic_Cornodro::
	.incbin "graphics/pokemon/cornodro/back.4bpp.lz"

gMonShinyPalette_Cornodro::
	.incbin "graphics/pokemon/cornodro/shiny.gbapal.lz"

gMonIcon_Cornodro::
	.incbin "graphics/pokemon/cornodro/icon.4bpp"

gMonFootprint_Cornodro::
	.incbin "graphics/pokemon/cornodro/footprint.1bpp"

gMonFrontPic_Karidari::
	.incbin "graphics/pokemon/karidari/front.4bpp.lz"

gMonPalette_Karidari::
	.incbin "graphics/pokemon/karidari/normal.gbapal.lz"

gMonBackPic_Karidari::
	.incbin "graphics/pokemon/karidari/back.4bpp.lz"

gMonShinyPalette_Karidari::
	.incbin "graphics/pokemon/karidari/shiny.gbapal.lz"

gMonIcon_Karidari::
	.incbin "graphics/pokemon/karidari/icon.4bpp"

gMonFootprint_Karidari::
	.incbin "graphics/pokemon/karidari/footprint.1bpp"

gMonFrontPic_Captrunke::
	.incbin "graphics/pokemon/captrunke/front.4bpp.lz"

gMonPalette_Captrunke::
	.incbin "graphics/pokemon/captrunke/normal.gbapal.lz"

gMonBackPic_Captrunke::
	.incbin "graphics/pokemon/captrunke/back.4bpp.lz"

gMonShinyPalette_Captrunke::
	.incbin "graphics/pokemon/captrunke/shiny.gbapal.lz"

gMonIcon_Captrunke::
	.incbin "graphics/pokemon/captrunke/icon.4bpp"

gMonFootprint_Captrunke::
	.incbin "graphics/pokemon/captrunke/footprint.1bpp"

gMonFrontPic_Bankedon::
	.incbin "graphics/pokemon/bankedon/front.4bpp.lz"

gMonPalette_Bankedon::
	.incbin "graphics/pokemon/bankedon/normal.gbapal.lz"

gMonBackPic_Bankedon::
	.incbin "graphics/pokemon/bankedon/back.4bpp.lz"

gMonShinyPalette_Bankedon::
	.incbin "graphics/pokemon/bankedon/shiny.gbapal.lz"

gMonIcon_Bankedon::
	.incbin "graphics/pokemon/bankedon/icon.4bpp"

gMonFootprint_Bankedon::
	.incbin "graphics/pokemon/bankedon/footprint.1bpp"

gMonFrontPic_Plures::
	.incbin "graphics/pokemon/plurés/front.4bpp.lz"

gMonPalette_Plures::
	.incbin "graphics/pokemon/plurés/normal.gbapal.lz"

gMonBackPic_Plures::
	.incbin "graphics/pokemon/plurés/back.4bpp.lz"

gMonShinyPalette_Plures::
	.incbin "graphics/pokemon/plurés/shiny.gbapal.lz"

gMonIcon_Plures::
	.incbin "graphics/pokemon/plurés/icon.4bpp"

gMonFootprint_Plures::
	.incbin "graphics/pokemon/plurés/footprint.1bpp"

gMonFrontPic_Dracoon::
	.incbin "graphics/pokemon/dracoon/front.4bpp.lz"

gMonPalette_Dracoon::
	.incbin "graphics/pokemon/dracoon/normal.gbapal.lz"

gMonBackPic_Dracoon::
	.incbin "graphics/pokemon/dracoon/back.4bpp.lz"

gMonShinyPalette_Dracoon::
	.incbin "graphics/pokemon/dracoon/shiny.gbapal.lz"

gMonIcon_Dracoon::
	.incbin "graphics/pokemon/dracoon/icon.4bpp"

gMonFootprint_Dracoon::
	.incbin "graphics/pokemon/dracoon/footprint.1bpp"

gMonFrontPic_Piscy::
	.incbin "graphics/pokemon/piscy/front.4bpp.lz"

gMonPalette_Piscy::
	.incbin "graphics/pokemon/piscy/normal.gbapal.lz"

gMonBackPic_Piscy::
	.incbin "graphics/pokemon/piscy/back.4bpp.lz"

gMonShinyPalette_Piscy::
	.incbin "graphics/pokemon/piscy/shiny.gbapal.lz"

gMonIcon_Piscy::
	.incbin "graphics/pokemon/piscy/icon.4bpp"

gMonFootprint_Piscy::
	.incbin "graphics/pokemon/piscy/footprint.1bpp"

gMonFrontPic_Dolphe::
	.incbin "graphics/pokemon/dolphe/front.4bpp.lz"

gMonPalette_Dolphe::
	.incbin "graphics/pokemon/dolphe/normal.gbapal.lz"

gMonBackPic_Dolphe::
	.incbin "graphics/pokemon/dolphe/back.4bpp.lz"

gMonShinyPalette_Dolphe::
	.incbin "graphics/pokemon/dolphe/shiny.gbapal.lz"

gMonIcon_Dolphe::
	.incbin "graphics/pokemon/dolphe/icon.4bpp"

gMonFootprint_Dolphe::
	.incbin "graphics/pokemon/dolphe/footprint.1bpp"

gMonFrontPic_Prawby::
	.incbin "graphics/pokemon/prawby/front.4bpp.lz"

gMonPalette_Prawby::
	.incbin "graphics/pokemon/prawby/normal.gbapal.lz"

gMonBackPic_Prawby::
	.incbin "graphics/pokemon/prawby/back.4bpp.lz"

gMonShinyPalette_Prawby::
	.incbin "graphics/pokemon/prawby/shiny.gbapal.lz"

gMonIcon_Prawby::
	.incbin "graphics/pokemon/prawby/icon.4bpp"

gMonFootprint_Prawby::
	.incbin "graphics/pokemon/prawby/footprint.1bpp"

gMonFrontPic_Prawking::
	.incbin "graphics/pokemon/prawking/front.4bpp.lz"

gMonPalette_Prawking::
	.incbin "graphics/pokemon/prawking/normal.gbapal.lz"

gMonBackPic_Prawking::
	.incbin "graphics/pokemon/prawking/back.4bpp.lz"

gMonShinyPalette_Prawking::
	.incbin "graphics/pokemon/prawking/shiny.gbapal.lz"

gMonIcon_Prawking::
	.incbin "graphics/pokemon/prawking/icon.4bpp"

gMonFootprint_Prawking::
	.incbin "graphics/pokemon/prawking/footprint.1bpp"

gMonFrontPic_Bethin::
	.incbin "graphics/pokemon/bethin/front.4bpp.lz"

gMonPalette_Bethin::
	.incbin "graphics/pokemon/bethin/normal.gbapal.lz"

gMonBackPic_Bethin::
	.incbin "graphics/pokemon/bethin/back.4bpp.lz"

gMonShinyPalette_Bethin::
	.incbin "graphics/pokemon/bethin/shiny.gbapal.lz"

gMonIcon_Bethin::
	.incbin "graphics/pokemon/bethin/icon.4bpp"

gMonFootprint_Bethin::
	.incbin "graphics/pokemon/bethin/footprint.1bpp"

gMonFrontPic_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/front.4bpp.lz"

gMonPalette_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/normal.gbapal.lz"

gMonBackPic_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/back.4bpp.lz"

gMonShinyPalette_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/shiny.gbapal.lz"

gMonIcon_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/icon.4bpp"

gMonFootprint_Beetespuk::
	.incbin "graphics/pokemon/beetespuk/footprint.1bpp"

gMonFrontPic_Saximau::
	.incbin "graphics/pokemon/saximau/front.4bpp.lz"

gMonPalette_Saximau::
	.incbin "graphics/pokemon/saximau/normal.gbapal.lz"

gMonBackPic_Saximau::
	.incbin "graphics/pokemon/saximau/back.4bpp.lz"

gMonShinyPalette_Saximau::
	.incbin "graphics/pokemon/saximau/shiny.gbapal.lz"

gMonIcon_Saximau::
	.incbin "graphics/pokemon/saximau/icon.4bpp"

gMonFootprint_Saximau::
	.incbin "graphics/pokemon/saximau/footprint.1bpp"

gMonFrontPic_Ektron::
	.incbin "graphics/pokemon/ektron/front.4bpp.lz"

gMonPalette_Ektron::
	.incbin "graphics/pokemon/ektron/normal.gbapal.lz"

gMonBackPic_Ektron::
	.incbin "graphics/pokemon/ektron/back.4bpp.lz"

gMonShinyPalette_Ektron::
	.incbin "graphics/pokemon/ektron/shiny.gbapal.lz"

gMonIcon_Ektron::
	.incbin "graphics/pokemon/ektron/icon.4bpp"

gMonFootprint_Ektron::
	.incbin "graphics/pokemon/ektron/footprint.1bpp"

gMonFrontPic_Garsoom::
	.incbin "graphics/pokemon/garsoom/front.4bpp.lz"

gMonPalette_Garsoom::
	.incbin "graphics/pokemon/garsoom/normal.gbapal.lz"

gMonBackPic_Garsoom::
	.incbin "graphics/pokemon/garsoom/back.4bpp.lz"

gMonShinyPalette_Garsoom::
	.incbin "graphics/pokemon/garsoom/shiny.gbapal.lz"

gMonIcon_Garsoom::
	.incbin "graphics/pokemon/garsoom/icon.4bpp"

gMonFootprint_Garsoom::
	.incbin "graphics/pokemon/garsoom/footprint.1bpp"

gMonFrontPic_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/front.4bpp.lz"

gMonPalette_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/normal.gbapal.lz"

gMonBackPic_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/back.4bpp.lz"

gMonShinyPalette_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/shiny.gbapal.lz"

gMonIcon_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/icon.4bpp"

gMonFootprint_Tejemeje::
	.incbin "graphics/pokemon/tejemeje/footprint.1bpp"

gMonFrontPic_Furran::
	.incbin "graphics/pokemon/furran/front.4bpp.lz"

gMonPalette_Furran::
	.incbin "graphics/pokemon/furran/normal.gbapal.lz"

gMonBackPic_Furran::
	.incbin "graphics/pokemon/furran/back.4bpp.lz"

gMonShinyPalette_Furran::
	.incbin "graphics/pokemon/furran/shiny.gbapal.lz"

gMonIcon_Furran::
	.incbin "graphics/pokemon/furran/icon.4bpp"

gMonFootprint_Furran::
	.incbin "graphics/pokemon/furran/footprint.1bpp"

gMonFrontPic_Thundish::
	.incbin "graphics/pokemon/thundish/front.4bpp.lz"

gMonPalette_Thundish::
	.incbin "graphics/pokemon/thundish/normal.gbapal.lz"

gMonBackPic_Thundish::
	.incbin "graphics/pokemon/thundish/back.4bpp.lz"

gMonShinyPalette_Thundish::
	.incbin "graphics/pokemon/thundish/shiny.gbapal.lz"

gMonIcon_Thundish::
	.incbin "graphics/pokemon/thundish/icon.4bpp"

gMonFootprint_Thundish::
	.incbin "graphics/pokemon/thundish/footprint.1bpp"

gMonFrontPic_Thundran::
	.incbin "graphics/pokemon/thundran/front.4bpp.lz"

gMonPalette_Thundran::
	.incbin "graphics/pokemon/thundran/normal.gbapal.lz"

gMonBackPic_Thundran::
	.incbin "graphics/pokemon/thundran/back.4bpp.lz"

gMonShinyPalette_Thundran::
	.incbin "graphics/pokemon/thundran/shiny.gbapal.lz"

gMonIcon_Thundran::
	.incbin "graphics/pokemon/thundran/icon.4bpp"

gMonFootprint_Thundran::
	.incbin "graphics/pokemon/thundran/footprint.1bpp"

gMonFrontPic_Shacker::
	.incbin "graphics/pokemon/shacker/front.4bpp.lz"

gMonPalette_Shacker::
	.incbin "graphics/pokemon/shacker/normal.gbapal.lz"

gMonBackPic_Shacker::
	.incbin "graphics/pokemon/shacker/back.4bpp.lz"

gMonShinyPalette_Shacker::
	.incbin "graphics/pokemon/shacker/shiny.gbapal.lz"

gMonIcon_Shacker::
	.incbin "graphics/pokemon/shacker/icon.4bpp"

gMonFootprint_Shacker::
	.incbin "graphics/pokemon/shacker/footprint.1bpp"

gMonFrontPic_Eyendy::
	.incbin "graphics/pokemon/eyendy/front.4bpp.lz"

gMonPalette_Eyendy::
	.incbin "graphics/pokemon/eyendy/normal.gbapal.lz"

gMonBackPic_Eyendy::
	.incbin "graphics/pokemon/eyendy/back.4bpp.lz"

gMonShinyPalette_Eyendy::
	.incbin "graphics/pokemon/eyendy/shiny.gbapal.lz"

gMonIcon_Eyendy::
	.incbin "graphics/pokemon/eyendy/icon.4bpp"

gMonFootprint_Eyendy::
	.incbin "graphics/pokemon/eyendy/footprint.1bpp"

gMonFrontPic_Cwabay::
	.incbin "graphics/pokemon/cwabay/front.4bpp.lz"

gMonPalette_Cwabay::
	.incbin "graphics/pokemon/cwabay/normal.gbapal.lz"

gMonBackPic_Cwabay::
	.incbin "graphics/pokemon/cwabay/back.4bpp.lz"

gMonShinyPalette_Cwabay::
	.incbin "graphics/pokemon/cwabay/shiny.gbapal.lz"

gMonIcon_Cwabay::
	.incbin "graphics/pokemon/cwabay/icon.4bpp"

gMonFootprint_Cwabay::
	.incbin "graphics/pokemon/cwabay/footprint.1bpp"

gMonFrontPic_Wetway::
	.incbin "graphics/pokemon/wetway/front.4bpp.lz"

gMonPalette_Wetway::
	.incbin "graphics/pokemon/wetway/normal.gbapal.lz"

gMonBackPic_Wetway::
	.incbin "graphics/pokemon/wetway/back.4bpp.lz"

gMonShinyPalette_Wetway::
	.incbin "graphics/pokemon/wetway/shiny.gbapal.lz"

gMonIcon_Wetway::
	.incbin "graphics/pokemon/wetway/icon.4bpp"

gMonFootprint_Wetway::
	.incbin "graphics/pokemon/wetway/footprint.1bpp"

gMonFrontPic_Joylway::
	.incbin "graphics/pokemon/joylway/front.4bpp.lz"

gMonPalette_Joylway::
	.incbin "graphics/pokemon/joylway/normal.gbapal.lz"

gMonBackPic_Joylway::
	.incbin "graphics/pokemon/joylway/back.4bpp.lz"

gMonShinyPalette_Joylway::
	.incbin "graphics/pokemon/joylway/shiny.gbapal.lz"

gMonIcon_Joylway::
	.incbin "graphics/pokemon/joylway/icon.4bpp"

gMonFootprint_Joylway::
	.incbin "graphics/pokemon/joylway/footprint.1bpp"

gMonFrontPic_Heatway::
	.incbin "graphics/pokemon/heatway/front.4bpp.lz"

gMonPalette_Heatway::
	.incbin "graphics/pokemon/heatway/normal.gbapal.lz"

gMonBackPic_Heatway::
	.incbin "graphics/pokemon/heatway/back.4bpp.lz"

gMonShinyPalette_Heatway::
	.incbin "graphics/pokemon/heatway/shiny.gbapal.lz"

gMonIcon_Heatway::
	.incbin "graphics/pokemon/heatway/icon.4bpp"

gMonFootprint_Heatway::
	.incbin "graphics/pokemon/heatway/footprint.1bpp"

gMonFrontPic_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/front.4bpp.lz"

gMonPalette_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/normal.gbapal.lz"

gMonBackPic_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/back.4bpp.lz"

gMonShinyPalette_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/shiny.gbapal.lz"

gMonIcon_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/icon.4bpp"

gMonFootprint_Arbeluc::
	.incbin "graphics/pokemon/arbeluc/footprint.1bpp"

gMonFrontPic_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/front.4bpp.lz"

gMonPalette_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/normal.gbapal.lz"

gMonBackPic_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/back.4bpp.lz"

gMonShinyPalette_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/shiny.gbapal.lz"

gMonIcon_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/icon.4bpp"

gMonFootprint_Spiraulix::
	.incbin "graphics/pokemon/spiraulix/footprint.1bpp"

gMonFrontPic_Messaurix::
	.incbin "graphics/pokemon/messaurix/front.4bpp.lz"

gMonPalette_Messaurix::
	.incbin "graphics/pokemon/messaurix/normal.gbapal.lz"

gMonBackPic_Messaurix::
	.incbin "graphics/pokemon/messaurix/back.4bpp.lz"

gMonShinyPalette_Messaurix::
	.incbin "graphics/pokemon/messaurix/shiny.gbapal.lz"

gMonIcon_Messaurix::
	.incbin "graphics/pokemon/messaurix/icon.4bpp"

gMonFootprint_Messaurix::
	.incbin "graphics/pokemon/messaurix/footprint.1bpp"

gMonFrontPic_Fishix::
	.incbin "graphics/pokemon/fishix/front.4bpp.lz"

gMonPalette_Fishix::
	.incbin "graphics/pokemon/fishix/normal.gbapal.lz"

gMonBackPic_Fishix::
	.incbin "graphics/pokemon/fishix/back.4bpp.lz"

gMonShinyPalette_Fishix::
	.incbin "graphics/pokemon/fishix/shiny.gbapal.lz"

gMonIcon_Fishix::
	.incbin "graphics/pokemon/fishix/icon.4bpp"

gMonFootprint_Fishix::
	.incbin "graphics/pokemon/fishix/footprint.1bpp"

gMonFrontPic_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/front.4bpp.lz"

gMonPalette_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/normal.gbapal.lz"

gMonBackPic_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/back.4bpp.lz"

gMonShinyPalette_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/shiny.gbapal.lz"

gMonIcon_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/icon.4bpp"

gMonFootprint_Cefasokix::
	.incbin "graphics/pokemon/cefasokix/footprint.1bpp"

gMonFrontPic_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/front.4bpp.lz"

gMonPalette_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/normal.gbapal.lz"

gMonBackPic_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/back.4bpp.lz"

gMonShinyPalette_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/shiny.gbapal.lz"

gMonIcon_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/icon.4bpp"

gMonFootprint_Beakodoron::
	.incbin "graphics/pokemon/beakodoron/footprint.1bpp"

gMonFrontPic_Boultan::
	.incbin "graphics/pokemon/boultan/front.4bpp.lz"

gMonPalette_Boultan::
	.incbin "graphics/pokemon/boultan/normal.gbapal.lz"

gMonBackPic_Boultan::
	.incbin "graphics/pokemon/boultan/back.4bpp.lz"

gMonShinyPalette_Boultan::
	.incbin "graphics/pokemon/boultan/shiny.gbapal.lz"

gMonIcon_Boultan::
	.incbin "graphics/pokemon/boultan/icon.4bpp"

gMonFootprint_Boultan::
	.incbin "graphics/pokemon/boultan/footprint.1bpp"

gMonFrontPic_Bereuga::
	.incbin "graphics/pokemon/bereuga/front.4bpp.lz"

gMonPalette_Bereuga::
	.incbin "graphics/pokemon/bereuga/normal.gbapal.lz"

gMonBackPic_Bereuga::
	.incbin "graphics/pokemon/bereuga/back.4bpp.lz"

gMonShinyPalette_Bereuga::
	.incbin "graphics/pokemon/bereuga/shiny.gbapal.lz"

gMonIcon_Bereuga::
	.incbin "graphics/pokemon/bereuga/icon.4bpp"

gMonFootprint_Bereuga::
	.incbin "graphics/pokemon/bereuga/footprint.1bpp"

gMonFrontPic_Emethe::
	.incbin "graphics/pokemon/emethe/front.4bpp.lz"

gMonPalette_Emethe::
	.incbin "graphics/pokemon/emethe/normal.gbapal.lz"

gMonBackPic_Emethe::
	.incbin "graphics/pokemon/emethe/back.4bpp.lz"

gMonShinyPalette_Emethe::
	.incbin "graphics/pokemon/emethe/shiny.gbapal.lz"

gMonIcon_Emethe::
	.incbin "graphics/pokemon/emethe/icon.4bpp"

gMonFootprint_Emethe::
	.incbin "graphics/pokemon/emethe/footprint.1bpp"

gMonFrontPic_Paratiki::
	.incbin "graphics/pokemon/paratiki/front.4bpp.lz"

gMonPalette_Paratiki::
	.incbin "graphics/pokemon/paratiki/normal.gbapal.lz"

gMonBackPic_Paratiki::
	.incbin "graphics/pokemon/paratiki/back.4bpp.lz"

gMonShinyPalette_Paratiki::
	.incbin "graphics/pokemon/paratiki/shiny.gbapal.lz"

gMonIcon_Paratiki::
	.incbin "graphics/pokemon/paratiki/icon.4bpp"

gMonFootprint_Paratiki::
	.incbin "graphics/pokemon/paratiki/footprint.1bpp"

gMonFrontPic_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/front.4bpp.lz"

gMonPalette_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/normal.gbapal.lz"

gMonBackPic_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/back.4bpp.lz"

gMonShinyPalette_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/shiny.gbapal.lz"

gMonIcon_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/icon.4bpp"

gMonFootprint_Mithedaon::
	.incbin "graphics/pokemon/mithedaon/footprint.1bpp"

gMonFrontPic_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/front.4bpp.lz"

gMonPalette_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/normal.gbapal.lz"

gMonBackPic_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/back.4bpp.lz"

gMonShinyPalette_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/shiny.gbapal.lz"

gMonIcon_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/icon.4bpp"

gMonFootprint_Whirldraon::
	.incbin "graphics/pokemon/whirldraon/footprint.1bpp"

gMonFrontPic_Migthdra::
	.incbin "graphics/pokemon/migthdra/front.4bpp.lz"

gMonPalette_Migthdra::
	.incbin "graphics/pokemon/migthdra/normal.gbapal.lz"

gMonBackPic_Migthdra::
	.incbin "graphics/pokemon/migthdra/back.4bpp.lz"

gMonShinyPalette_Migthdra::
	.incbin "graphics/pokemon/migthdra/shiny.gbapal.lz"

gMonIcon_Migthdra::
	.incbin "graphics/pokemon/migthdra/icon.4bpp"

gMonFootprint_Migthdra::
	.incbin "graphics/pokemon/migthdra/footprint.1bpp"

gMonFrontPic_Zengredse::
	.incbin "graphics/pokemon/zengredse/front.4bpp.lz"

gMonPalette_Zengredse::
	.incbin "graphics/pokemon/zengredse/normal.gbapal.lz"

gMonBackPic_Zengredse::
	.incbin "graphics/pokemon/zengredse/back.4bpp.lz"

gMonShinyPalette_Zengredse::
	.incbin "graphics/pokemon/zengredse/shiny.gbapal.lz"

gMonIcon_Zengredse::
	.incbin "graphics/pokemon/zengredse/icon.4bpp"

gMonFootprint_Zengredse::
	.incbin "graphics/pokemon/zengredse/footprint.1bpp"

gMonFrontPic_Wiami::
	.incbin "graphics/pokemon/wiami/front.4bpp.lz"

gMonPalette_Wiami::
	.incbin "graphics/pokemon/wiami/normal.gbapal.lz"

gMonBackPic_Wiami::
	.incbin "graphics/pokemon/wiami/back.4bpp.lz"

gMonShinyPalette_Wiami::
	.incbin "graphics/pokemon/wiami/shiny.gbapal.lz"

gMonIcon_Wiami::
	.incbin "graphics/pokemon/wiami/icon.4bpp"

gMonFootprint_Wiami::
	.incbin "graphics/pokemon/wiami/footprint.1bpp"

gMonFrontPic_Potac::
	.incbin "graphics/pokemon/potac/front.4bpp.lz"

gMonPalette_Potac::
	.incbin "graphics/pokemon/potac/normal.gbapal.lz"

gMonBackPic_Potac::
	.incbin "graphics/pokemon/potac/back.4bpp.lz"

gMonShinyPalette_Potac::
	.incbin "graphics/pokemon/potac/shiny.gbapal.lz"

gMonIcon_Potac::
	.incbin "graphics/pokemon/potac/icon.4bpp"

gMonFootprint_Potac::
	.incbin "graphics/pokemon/potac/footprint.1bpp"

gMonFrontPic_Tubirato::
	.incbin "graphics/pokemon/tubirato/front.4bpp.lz"

gMonPalette_Tubirato::
	.incbin "graphics/pokemon/tubirato/normal.gbapal.lz"

gMonBackPic_Tubirato::
	.incbin "graphics/pokemon/tubirato/back.4bpp.lz"

gMonShinyPalette_Tubirato::
	.incbin "graphics/pokemon/tubirato/shiny.gbapal.lz"

gMonIcon_Tubirato::
	.incbin "graphics/pokemon/tubirato/icon.4bpp"

gMonFootprint_Tubirato::
	.incbin "graphics/pokemon/tubirato/footprint.1bpp"

gMonFrontPic_Ogritato::
	.incbin "graphics/pokemon/ogritato/front.4bpp.lz"

gMonPalette_Ogritato::
	.incbin "graphics/pokemon/ogritato/normal.gbapal.lz"

gMonBackPic_Ogritato::
	.incbin "graphics/pokemon/ogritato/back.4bpp.lz"

gMonShinyPalette_Ogritato::
	.incbin "graphics/pokemon/ogritato/shiny.gbapal.lz"

gMonIcon_Ogritato::
	.incbin "graphics/pokemon/ogritato/icon.4bpp"

gMonFootprint_Ogritato::
	.incbin "graphics/pokemon/ogritato/footprint.1bpp"

gMonFrontPic_Lavlon::
	.incbin "graphics/pokemon/lavlon/front.4bpp.lz"

gMonPalette_Lavlon::
	.incbin "graphics/pokemon/lavlon/normal.gbapal.lz"

gMonBackPic_Lavlon::
	.incbin "graphics/pokemon/lavlon/back.4bpp.lz"

gMonShinyPalette_Lavlon::
	.incbin "graphics/pokemon/lavlon/shiny.gbapal.lz"

gMonIcon_Lavlon::
	.incbin "graphics/pokemon/lavlon/icon.4bpp"

gMonFootprint_Lavlon::
	.incbin "graphics/pokemon/lavlon/footprint.1bpp"

gMonFrontPic_Magbol::
	.incbin "graphics/pokemon/magbol/front.4bpp.lz"

gMonPalette_Magbol::
	.incbin "graphics/pokemon/magbol/normal.gbapal.lz"

gMonBackPic_Magbol::
	.incbin "graphics/pokemon/magbol/back.4bpp.lz"

gMonShinyPalette_Magbol::
	.incbin "graphics/pokemon/magbol/shiny.gbapal.lz"

gMonIcon_Magbol::
	.incbin "graphics/pokemon/magbol/icon.4bpp"

gMonFootprint_Magbol::
	.incbin "graphics/pokemon/magbol/footprint.1bpp"

gMonFrontPic_Canlava::
	.incbin "graphics/pokemon/canlava/front.4bpp.lz"

gMonPalette_Canlava::
	.incbin "graphics/pokemon/canlava/normal.gbapal.lz"

gMonBackPic_Canlava::
	.incbin "graphics/pokemon/canlava/back.4bpp.lz"

gMonShinyPalette_Canlava::
	.incbin "graphics/pokemon/canlava/shiny.gbapal.lz"

gMonIcon_Canlava::
	.incbin "graphics/pokemon/canlava/icon.4bpp"

gMonFootprint_Canlava::
	.incbin "graphics/pokemon/canlava/footprint.1bpp"

gMonFrontPic_Shelldan::
	.incbin "graphics/pokemon/shelldan/front.4bpp.lz"

gMonPalette_Shelldan::
	.incbin "graphics/pokemon/shelldan/normal.gbapal.lz"

gMonBackPic_Shelldan::
	.incbin "graphics/pokemon/shelldan/back.4bpp.lz"

gMonShinyPalette_Shelldan::
	.incbin "graphics/pokemon/shelldan/shiny.gbapal.lz"

gMonIcon_Shelldan::
	.incbin "graphics/pokemon/shelldan/icon.4bpp"

gMonFootprint_Shelldan::
	.incbin "graphics/pokemon/shelldan/footprint.1bpp"

gMonFrontPic_Licka::
	.incbin "graphics/pokemon/lickä/front.4bpp.lz"

gMonPalette_Licka::
	.incbin "graphics/pokemon/lickä/normal.gbapal.lz"

gMonBackPic_Licka::
	.incbin "graphics/pokemon/lickä/back.4bpp.lz"

gMonShinyPalette_Licka::
	.incbin "graphics/pokemon/lickä/shiny.gbapal.lz"

gMonIcon_Licka::
	.incbin "graphics/pokemon/lickä/icon.4bpp"

gMonFootprint_Licka::
	.incbin "graphics/pokemon/lickä/footprint.1bpp"

gMonFrontPic_Tongrito::
	.incbin "graphics/pokemon/tongrito/front.4bpp.lz"

gMonPalette_Tongrito::
	.incbin "graphics/pokemon/tongrito/normal.gbapal.lz"

gMonBackPic_Tongrito::
	.incbin "graphics/pokemon/tongrito/back.4bpp.lz"

gMonShinyPalette_Tongrito::
	.incbin "graphics/pokemon/tongrito/shiny.gbapal.lz"

gMonIcon_Tongrito::
	.incbin "graphics/pokemon/tongrito/icon.4bpp"

gMonFootprint_Tongrito::
	.incbin "graphics/pokemon/tongrito/footprint.1bpp"

gMonFrontPic_Furbee::
	.incbin "graphics/pokemon/furbee/front.4bpp.lz"

gMonPalette_Furbee::
	.incbin "graphics/pokemon/furbee/normal.gbapal.lz"

gMonBackPic_Furbee::
	.incbin "graphics/pokemon/furbee/back.4bpp.lz"

gMonShinyPalette_Furbee::
	.incbin "graphics/pokemon/furbee/shiny.gbapal.lz"

gMonIcon_Furbee::
	.incbin "graphics/pokemon/furbee/icon.4bpp"

gMonFootprint_Furbee::
	.incbin "graphics/pokemon/furbee/footprint.1bpp"

gMonFrontPic_Morkibia::
	.incbin "graphics/pokemon/morkibia/front.4bpp.lz"

gMonPalette_Morkibia::
	.incbin "graphics/pokemon/morkibia/normal.gbapal.lz"

gMonBackPic_Morkibia::
	.incbin "graphics/pokemon/morkibia/back.4bpp.lz"

gMonShinyPalette_Morkibia::
	.incbin "graphics/pokemon/morkibia/shiny.gbapal.lz"

gMonIcon_Morkibia::
	.incbin "graphics/pokemon/morkibia/icon.4bpp"

gMonFootprint_Morkibia::
	.incbin "graphics/pokemon/morkibia/footprint.1bpp"

gMonFrontPic_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/front.4bpp.lz"

gMonPalette_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/normal.gbapal.lz"

gMonBackPic_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/back.4bpp.lz"

gMonShinyPalette_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/shiny.gbapal.lz"

gMonIcon_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/icon.4bpp"

gMonFootprint_Kiwirawa::
	.incbin "graphics/pokemon/kiwirawa/footprint.1bpp"

gMonFrontPic_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/front.4bpp.lz"

gMonPalette_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/normal.gbapal.lz"

gMonBackPic_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/back.4bpp.lz"

gMonShinyPalette_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/shiny.gbapal.lz"

gMonIcon_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/icon.4bpp"

gMonFootprint_Kiawariwa::
	.incbin "graphics/pokemon/kiawariwa/footprint.1bpp"

gMonFrontPic_Bzby::
	.incbin "graphics/pokemon/bzby/front.4bpp.lz"

gMonPalette_Bzby::
	.incbin "graphics/pokemon/bzby/normal.gbapal.lz"

gMonBackPic_Bzby::
	.incbin "graphics/pokemon/bzby/back.4bpp.lz"

gMonShinyPalette_Bzby::
	.incbin "graphics/pokemon/bzby/shiny.gbapal.lz"

gMonIcon_Bzby::
	.incbin "graphics/pokemon/bzby/icon.4bpp"

gMonFootprint_Bzby::
	.incbin "graphics/pokemon/bzby/footprint.1bpp"

gMonFrontPic_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/front.4bpp.lz"

gMonPalette_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/normal.gbapal.lz"

gMonBackPic_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/back.4bpp.lz"

gMonShinyPalette_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/shiny.gbapal.lz"

gMonIcon_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/icon.4bpp"

gMonFootprint_Kwimbee::
	.incbin "graphics/pokemon/kwimbee/footprint.1bpp"

gMonFrontPic_Verpillar::
	.incbin "graphics/pokemon/verpillar/front.4bpp.lz"

gMonPalette_Verpillar::
	.incbin "graphics/pokemon/verpillar/normal.gbapal.lz"

gMonBackPic_Verpillar::
	.incbin "graphics/pokemon/verpillar/back.4bpp.lz"

gMonShinyPalette_Verpillar::
	.incbin "graphics/pokemon/verpillar/shiny.gbapal.lz"

gMonIcon_Verpillar::
	.incbin "graphics/pokemon/verpillar/icon.4bpp"

gMonFootprint_Verpillar::
	.incbin "graphics/pokemon/verpillar/footprint.1bpp"

gMonFrontPic_Triworn::
	.incbin "graphics/pokemon/triworn/front.4bpp.lz"

gMonPalette_Triworn::
	.incbin "graphics/pokemon/triworn/normal.gbapal.lz"

gMonBackPic_Triworn::
	.incbin "graphics/pokemon/triworn/back.4bpp.lz"

gMonShinyPalette_Triworn::
	.incbin "graphics/pokemon/triworn/shiny.gbapal.lz"

gMonIcon_Triworn::
	.incbin "graphics/pokemon/triworn/icon.4bpp"

gMonFootprint_Triworn::
	.incbin "graphics/pokemon/triworn/footprint.1bpp"

gMonFrontPic_Tostol::
	.incbin "graphics/pokemon/tostol/front.4bpp.lz"

gMonPalette_Tostol::
	.incbin "graphics/pokemon/tostol/normal.gbapal.lz"

gMonBackPic_Tostol::
	.incbin "graphics/pokemon/tostol/back.4bpp.lz"

gMonShinyPalette_Tostol::
	.incbin "graphics/pokemon/tostol/shiny.gbapal.lz"

gMonIcon_Tostol::
	.incbin "graphics/pokemon/tostol/icon.4bpp"

gMonFootprint_Tostol::
	.incbin "graphics/pokemon/tostol/footprint.1bpp"

gMonFrontPic_Eloru::
	.incbin "graphics/pokemon/eloru/front.4bpp.lz"

gMonPalette_Eloru::
	.incbin "graphics/pokemon/eloru/normal.gbapal.lz"

gMonBackPic_Eloru::
	.incbin "graphics/pokemon/eloru/back.4bpp.lz"

gMonShinyPalette_Eloru::
	.incbin "graphics/pokemon/eloru/shiny.gbapal.lz"

gMonIcon_Eloru::
	.incbin "graphics/pokemon/eloru/icon.4bpp"

gMonFootprint_Eloru::
	.incbin "graphics/pokemon/eloru/footprint.1bpp"

gMonFrontPic_Aenguile::
	.incbin "graphics/pokemon/aenguile/front.4bpp.lz"

gMonPalette_Aenguile::
	.incbin "graphics/pokemon/aenguile/normal.gbapal.lz"

gMonBackPic_Aenguile::
	.incbin "graphics/pokemon/aenguile/back.4bpp.lz"

gMonShinyPalette_Aenguile::
	.incbin "graphics/pokemon/aenguile/shiny.gbapal.lz"

gMonIcon_Aenguile::
	.incbin "graphics/pokemon/aenguile/icon.4bpp"

gMonFootprint_Aenguile::
	.incbin "graphics/pokemon/aenguile/footprint.1bpp"

gMonFrontPic_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/front.4bpp.lz"

gMonPalette_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/normal.gbapal.lz"

gMonBackPic_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/back.4bpp.lz"

gMonShinyPalette_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/shiny.gbapal.lz"

gMonIcon_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/icon.4bpp"

gMonFootprint_Gusvolts::
	.incbin "graphics/pokemon/gusvolts/footprint.1bpp"

gMonFrontPic_Airi::
	.incbin "graphics/pokemon/airi/front.4bpp.lz"

gMonPalette_Airi::
	.incbin "graphics/pokemon/airi/normal.gbapal.lz"

gMonBackPic_Airi::
	.incbin "graphics/pokemon/airi/back.4bpp.lz"

gMonShinyPalette_Airi::
	.incbin "graphics/pokemon/airi/shiny.gbapal.lz"

gMonIcon_Airi::
	.incbin "graphics/pokemon/airi/icon.4bpp"

gMonFootprint_Airi::
	.incbin "graphics/pokemon/airi/footprint.1bpp"

gMonFrontPic_Fookid::
	.incbin "graphics/pokemon/fookid/front.4bpp.lz"

gMonPalette_Fookid::
	.incbin "graphics/pokemon/fookid/normal.gbapal.lz"

gMonBackPic_Fookid::
	.incbin "graphics/pokemon/fookid/back.4bpp.lz"

gMonShinyPalette_Fookid::
	.incbin "graphics/pokemon/fookid/shiny.gbapal.lz"

gMonIcon_Fookid::
	.incbin "graphics/pokemon/fookid/icon.4bpp"

gMonFootprint_Fookid::
	.incbin "graphics/pokemon/fookid/footprint.1bpp"

gMonFrontPic_Madnut::
	.incbin "graphics/pokemon/madnut/front.4bpp.lz"

gMonPalette_Madnut::
	.incbin "graphics/pokemon/madnut/normal.gbapal.lz"

gMonBackPic_Madnut::
	.incbin "graphics/pokemon/madnut/back.4bpp.lz"

gMonShinyPalette_Madnut::
	.incbin "graphics/pokemon/madnut/shiny.gbapal.lz"

gMonIcon_Madnut::
	.incbin "graphics/pokemon/madnut/icon.4bpp"

gMonFootprint_Madnut::
	.incbin "graphics/pokemon/madnut/footprint.1bpp"

gMonFrontPic_Woodird::
	.incbin "graphics/pokemon/woodird/front.4bpp.lz"

gMonPalette_Woodird::
	.incbin "graphics/pokemon/woodird/normal.gbapal.lz"

gMonBackPic_Woodird::
	.incbin "graphics/pokemon/woodird/back.4bpp.lz"

gMonShinyPalette_Woodird::
	.incbin "graphics/pokemon/woodird/shiny.gbapal.lz"

gMonIcon_Woodird::
	.incbin "graphics/pokemon/woodird/icon.4bpp"

gMonFootprint_Woodird::
	.incbin "graphics/pokemon/woodird/footprint.1bpp"

gMonFrontPic_Freion::
	.incbin "graphics/pokemon/freion/front.4bpp.lz"

gMonPalette_Freion::
	.incbin "graphics/pokemon/freion/normal.gbapal.lz"

gMonBackPic_Freion::
	.incbin "graphics/pokemon/freion/back.4bpp.lz"

gMonShinyPalette_Freion::
	.incbin "graphics/pokemon/freion/shiny.gbapal.lz"

gMonIcon_Freion::
	.incbin "graphics/pokemon/freion/icon.4bpp"

gMonFootprint_Freion::
	.incbin "graphics/pokemon/freion/footprint.1bpp"

gMonFrontPic_Coronneo::
	.incbin "graphics/pokemon/coronneo/front.4bpp.lz"

gMonPalette_Coronneo::
	.incbin "graphics/pokemon/coronneo/normal.gbapal.lz"

gMonBackPic_Coronneo::
	.incbin "graphics/pokemon/coronneo/back.4bpp.lz"

gMonShinyPalette_Coronneo::
	.incbin "graphics/pokemon/coronneo/shiny.gbapal.lz"

gMonIcon_Coronneo::
	.incbin "graphics/pokemon/coronneo/icon.4bpp"

gMonFootprint_Coronneo::
	.incbin "graphics/pokemon/coronneo/footprint.1bpp"

gMonFrontPic_Teamon::
	.incbin "graphics/pokemon/teamon/front.4bpp.lz"

gMonPalette_Teamon::
	.incbin "graphics/pokemon/teamon/normal.gbapal.lz"

gMonBackPic_Teamon::
	.incbin "graphics/pokemon/teamon/back.4bpp.lz"

gMonShinyPalette_Teamon::
	.incbin "graphics/pokemon/teamon/shiny.gbapal.lz"

gMonIcon_Teamon::
	.incbin "graphics/pokemon/teamon/icon.4bpp"

gMonFootprint_Teamon::
	.incbin "graphics/pokemon/teamon/footprint.1bpp"

gMonFrontPic_Grasspark::
	.incbin "graphics/pokemon/grasspark/front.4bpp.lz"

gMonPalette_Grasspark::
	.incbin "graphics/pokemon/grasspark/normal.gbapal.lz"

gMonBackPic_Grasspark::
	.incbin "graphics/pokemon/grasspark/back.4bpp.lz"

gMonShinyPalette_Grasspark::
	.incbin "graphics/pokemon/grasspark/shiny.gbapal.lz"

gMonIcon_Grasspark::
	.incbin "graphics/pokemon/grasspark/icon.4bpp"

gMonFootprint_Grasspark::
	.incbin "graphics/pokemon/grasspark/footprint.1bpp"

gMonFrontPic_Sooregat::
	.incbin "graphics/pokemon/sooregat/front.4bpp.lz"

gMonPalette_Sooregat::
	.incbin "graphics/pokemon/sooregat/normal.gbapal.lz"

gMonBackPic_Sooregat::
	.incbin "graphics/pokemon/sooregat/back.4bpp.lz"

gMonShinyPalette_Sooregat::
	.incbin "graphics/pokemon/sooregat/shiny.gbapal.lz"

gMonIcon_Sooregat::
	.incbin "graphics/pokemon/sooregat/icon.4bpp"

gMonFootprint_Sooregat::
	.incbin "graphics/pokemon/sooregat/footprint.1bpp"

gMonFrontPic_Frucpao::
	.incbin "graphics/pokemon/frucpao/front.4bpp.lz"

gMonPalette_Frucpao::
	.incbin "graphics/pokemon/frucpao/normal.gbapal.lz"

gMonBackPic_Frucpao::
	.incbin "graphics/pokemon/frucpao/back.4bpp.lz"

gMonShinyPalette_Frucpao::
	.incbin "graphics/pokemon/frucpao/shiny.gbapal.lz"

gMonIcon_Frucpao::
	.incbin "graphics/pokemon/frucpao/icon.4bpp"

gMonFootprint_Frucpao::
	.incbin "graphics/pokemon/frucpao/footprint.1bpp"

gMonFrontPic_Beavon::
	.incbin "graphics/pokemon/beavon/front.4bpp.lz"

gMonPalette_Beavon::
	.incbin "graphics/pokemon/beavon/normal.gbapal.lz"

gMonBackPic_Beavon::
	.incbin "graphics/pokemon/beavon/back.4bpp.lz"

gMonShinyPalette_Beavon::
	.incbin "graphics/pokemon/beavon/shiny.gbapal.lz"

gMonIcon_Beavon::
	.incbin "graphics/pokemon/beavon/icon.4bpp"

gMonFootprint_Beavon::
	.incbin "graphics/pokemon/beavon/footprint.1bpp"

gMonFrontPic_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/front.4bpp.lz"

gMonPalette_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/normal.gbapal.lz"

gMonBackPic_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/back.4bpp.lz"

gMonShinyPalette_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/shiny.gbapal.lz"

gMonIcon_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/icon.4bpp"

gMonFootprint_Umbeavella::
	.incbin "graphics/pokemon/umbeavella/footprint.1bpp"

gMonFrontPic_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/front.4bpp.lz"

gMonPalette_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/normal.gbapal.lz"

gMonBackPic_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/back.4bpp.lz"

gMonShinyPalette_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/shiny.gbapal.lz"

gMonIcon_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/icon.4bpp"

gMonFootprint_Coccnuto::
	.incbin "graphics/pokemon/coccnuto/footprint.1bpp"

gMonFrontPic_Pitdog::
	.incbin "graphics/pokemon/pitdog/front.4bpp.lz"

gMonPalette_Pitdog::
	.incbin "graphics/pokemon/pitdog/normal.gbapal.lz"

gMonBackPic_Pitdog::
	.incbin "graphics/pokemon/pitdog/back.4bpp.lz"

gMonShinyPalette_Pitdog::
	.incbin "graphics/pokemon/pitdog/shiny.gbapal.lz"

gMonIcon_Pitdog::
	.incbin "graphics/pokemon/pitdog/icon.4bpp"

gMonFootprint_Pitdog::
	.incbin "graphics/pokemon/pitdog/footprint.1bpp"

gMonFrontPic_Sproof::
	.incbin "graphics/pokemon/sproof/front.4bpp.lz"

gMonPalette_Sproof::
	.incbin "graphics/pokemon/sproof/normal.gbapal.lz"

gMonBackPic_Sproof::
	.incbin "graphics/pokemon/sproof/back.4bpp.lz"

gMonShinyPalette_Sproof::
	.incbin "graphics/pokemon/sproof/shiny.gbapal.lz"

gMonIcon_Sproof::
	.incbin "graphics/pokemon/sproof/icon.4bpp"

gMonFootprint_Sproof::
	.incbin "graphics/pokemon/sproof/footprint.1bpp"

gMonFrontPic_Peatoof::
	.incbin "graphics/pokemon/peatoof/front.4bpp.lz"

gMonPalette_Peatoof::
	.incbin "graphics/pokemon/peatoof/normal.gbapal.lz"

gMonBackPic_Peatoof::
	.incbin "graphics/pokemon/peatoof/back.4bpp.lz"

gMonShinyPalette_Peatoof::
	.incbin "graphics/pokemon/peatoof/shiny.gbapal.lz"

gMonIcon_Peatoof::
	.incbin "graphics/pokemon/peatoof/icon.4bpp"

gMonFootprint_Peatoof::
	.incbin "graphics/pokemon/peatoof/footprint.1bpp"

gMonFrontPic_Ividigi::
	.incbin "graphics/pokemon/ividigi/front.4bpp.lz"

gMonPalette_Ividigi::
	.incbin "graphics/pokemon/ividigi/normal.gbapal.lz"

gMonBackPic_Ividigi::
	.incbin "graphics/pokemon/ividigi/back.4bpp.lz"

gMonShinyPalette_Ividigi::
	.incbin "graphics/pokemon/ividigi/shiny.gbapal.lz"

gMonIcon_Ividigi::
	.incbin "graphics/pokemon/ividigi/icon.4bpp"

gMonFootprint_Ividigi::
	.incbin "graphics/pokemon/ividigi/footprint.1bpp"

gMonFrontPic_Bongon::
	.incbin "graphics/pokemon/bongon/front.4bpp.lz"

gMonPalette_Bongon::
	.incbin "graphics/pokemon/bongon/normal.gbapal.lz"

gMonBackPic_Bongon::
	.incbin "graphics/pokemon/bongon/back.4bpp.lz"

gMonShinyPalette_Bongon::
	.incbin "graphics/pokemon/bongon/shiny.gbapal.lz"

gMonIcon_Bongon::
	.incbin "graphics/pokemon/bongon/icon.4bpp"

gMonFootprint_Bongon::
	.incbin "graphics/pokemon/bongon/footprint.1bpp"

gMonFrontPic_Thinkower::
	.incbin "graphics/pokemon/thinkower/front.4bpp.lz"

gMonPalette_Thinkower::
	.incbin "graphics/pokemon/thinkower/normal.gbapal.lz"

gMonBackPic_Thinkower::
	.incbin "graphics/pokemon/thinkower/back.4bpp.lz"

gMonShinyPalette_Thinkower::
	.incbin "graphics/pokemon/thinkower/shiny.gbapal.lz"

gMonIcon_Thinkower::
	.incbin "graphics/pokemon/thinkower/icon.4bpp"

gMonFootprint_Thinkower::
	.incbin "graphics/pokemon/thinkower/footprint.1bpp"

gMonFrontPic_Flathinker::
	.incbin "graphics/pokemon/flathinker/front.4bpp.lz"

gMonPalette_Flathinker::
	.incbin "graphics/pokemon/flathinker/normal.gbapal.lz"

gMonBackPic_Flathinker::
	.incbin "graphics/pokemon/flathinker/back.4bpp.lz"

gMonShinyPalette_Flathinker::
	.incbin "graphics/pokemon/flathinker/shiny.gbapal.lz"

gMonIcon_Flathinker::
	.incbin "graphics/pokemon/flathinker/icon.4bpp"

gMonFootprint_Flathinker::
	.incbin "graphics/pokemon/flathinker/footprint.1bpp"

gMonFrontPic_Taermity::
	.incbin "graphics/pokemon/taermity/front.4bpp.lz"

gMonPalette_Taermity::
	.incbin "graphics/pokemon/taermity/normal.gbapal.lz"

gMonBackPic_Taermity::
	.incbin "graphics/pokemon/taermity/back.4bpp.lz"

gMonShinyPalette_Taermity::
	.incbin "graphics/pokemon/taermity/shiny.gbapal.lz"

gMonIcon_Taermity::
	.incbin "graphics/pokemon/taermity/icon.4bpp"

gMonFootprint_Taermity::
	.incbin "graphics/pokemon/taermity/footprint.1bpp"

gMonFrontPic_Racevish::
	.incbin "graphics/pokemon/racevish/front.4bpp.lz"

gMonPalette_Racevish::
	.incbin "graphics/pokemon/racevish/normal.gbapal.lz"

gMonBackPic_Racevish::
	.incbin "graphics/pokemon/racevish/back.4bpp.lz"

gMonShinyPalette_Racevish::
	.incbin "graphics/pokemon/racevish/shiny.gbapal.lz"

gMonIcon_Racevish::
	.incbin "graphics/pokemon/racevish/icon.4bpp"

gMonFootprint_Racevish::
	.incbin "graphics/pokemon/racevish/footprint.1bpp"

gMonFrontPic_Loddish::
	.incbin "graphics/pokemon/loddish/front.4bpp.lz"

gMonPalette_Loddish::
	.incbin "graphics/pokemon/loddish/normal.gbapal.lz"

gMonBackPic_Loddish::
	.incbin "graphics/pokemon/loddish/back.4bpp.lz"

gMonShinyPalette_Loddish::
	.incbin "graphics/pokemon/loddish/shiny.gbapal.lz"

gMonIcon_Loddish::
	.incbin "graphics/pokemon/loddish/icon.4bpp"

gMonFootprint_Loddish::
	.incbin "graphics/pokemon/loddish/footprint.1bpp"

gMonFrontPic_Blosway::
	.incbin "graphics/pokemon/blosway/front.4bpp.lz"

gMonPalette_Blosway::
	.incbin "graphics/pokemon/blosway/normal.gbapal.lz"

gMonBackPic_Blosway::
	.incbin "graphics/pokemon/blosway/back.4bpp.lz"

gMonShinyPalette_Blosway::
	.incbin "graphics/pokemon/blosway/shiny.gbapal.lz"

gMonIcon_Blosway::
	.incbin "graphics/pokemon/blosway/icon.4bpp"

gMonFootprint_Blosway::
	.incbin "graphics/pokemon/blosway/footprint.1bpp"

gMonFrontPic_Indinny::
	.incbin "graphics/pokemon/indinny/front.4bpp.lz"

gMonPalette_Indinny::
	.incbin "graphics/pokemon/indinny/normal.gbapal.lz"

gMonBackPic_Indinny::
	.incbin "graphics/pokemon/indinny/back.4bpp.lz"

gMonShinyPalette_Indinny::
	.incbin "graphics/pokemon/indinny/shiny.gbapal.lz"

gMonIcon_Indinny::
	.incbin "graphics/pokemon/indinny/icon.4bpp"

gMonFootprint_Indinny::
	.incbin "graphics/pokemon/indinny/footprint.1bpp"

gMonFrontPic_Tankoo::
	.incbin "graphics/pokemon/tankoo/front.4bpp.lz"

gMonPalette_Tankoo::
	.incbin "graphics/pokemon/tankoo/normal.gbapal.lz"

gMonBackPic_Tankoo::
	.incbin "graphics/pokemon/tankoo/back.4bpp.lz"

gMonShinyPalette_Tankoo::
	.incbin "graphics/pokemon/tankoo/shiny.gbapal.lz"

gMonIcon_Tankoo::
	.incbin "graphics/pokemon/tankoo/icon.4bpp"

gMonFootprint_Tankoo::
	.incbin "graphics/pokemon/tankoo/footprint.1bpp"

gMonFrontPic_Craprax::
	.incbin "graphics/pokemon/craprax/front.4bpp.lz"

gMonPalette_Craprax::
	.incbin "graphics/pokemon/craprax/normal.gbapal.lz"

gMonBackPic_Craprax::
	.incbin "graphics/pokemon/craprax/back.4bpp.lz"

gMonShinyPalette_Craprax::
	.incbin "graphics/pokemon/craprax/shiny.gbapal.lz"

gMonIcon_Craprax::
	.incbin "graphics/pokemon/craprax/icon.4bpp"

gMonFootprint_Craprax::
	.incbin "graphics/pokemon/craprax/footprint.1bpp"

gMonFrontPic_Magiken::
	.incbin "graphics/pokemon/magiken/front.4bpp.lz"

gMonPalette_Magiken::
	.incbin "graphics/pokemon/magiken/normal.gbapal.lz"

gMonBackPic_Magiken::
	.incbin "graphics/pokemon/magiken/back.4bpp.lz"

gMonShinyPalette_Magiken::
	.incbin "graphics/pokemon/magiken/shiny.gbapal.lz"

gMonIcon_Magiken::
	.incbin "graphics/pokemon/magiken/icon.4bpp"

gMonFootprint_Magiken::
	.incbin "graphics/pokemon/magiken/footprint.1bpp"

gMonFrontPic_Cornscript::
	.incbin "graphics/pokemon/cornscript/front.4bpp.lz"

gMonPalette_Cornscript::
	.incbin "graphics/pokemon/cornscript/normal.gbapal.lz"

gMonBackPic_Cornscript::
	.incbin "graphics/pokemon/cornscript/back.4bpp.lz"

gMonShinyPalette_Cornscript::
	.incbin "graphics/pokemon/cornscript/shiny.gbapal.lz"

gMonIcon_Cornscript::
	.incbin "graphics/pokemon/cornscript/icon.4bpp"

gMonFootprint_Cornscript::
	.incbin "graphics/pokemon/cornscript/footprint.1bpp"

gMonFrontPic_Medrake::
	.incbin "graphics/pokemon/medrake/front.4bpp.lz"

gMonPalette_Medrake::
	.incbin "graphics/pokemon/medrake/normal.gbapal.lz"

gMonBackPic_Medrake::
	.incbin "graphics/pokemon/medrake/back.4bpp.lz"

gMonShinyPalette_Medrake::
	.incbin "graphics/pokemon/medrake/shiny.gbapal.lz"

gMonIcon_Medrake::
	.incbin "graphics/pokemon/medrake/icon.4bpp"

gMonFootprint_Medrake::
	.incbin "graphics/pokemon/medrake/footprint.1bpp"

gMonFrontPic_Zhipo::
	.incbin "graphics/pokemon/zhipo/front.4bpp.lz"

gMonPalette_Zhipo::
	.incbin "graphics/pokemon/zhipo/normal.gbapal.lz"

gMonBackPic_Zhipo::
	.incbin "graphics/pokemon/zhipo/back.4bpp.lz"

gMonShinyPalette_Zhipo::
	.incbin "graphics/pokemon/zhipo/shiny.gbapal.lz"

gMonIcon_Zhipo::
	.incbin "graphics/pokemon/zhipo/icon.4bpp"

gMonFootprint_Zhipo::
	.incbin "graphics/pokemon/zhipo/footprint.1bpp"

gMonFrontPic_Moroberry::
	.incbin "graphics/pokemon/moroberry/front.4bpp.lz"

gMonPalette_Moroberry::
	.incbin "graphics/pokemon/moroberry/normal.gbapal.lz"

gMonBackPic_Moroberry::
	.incbin "graphics/pokemon/moroberry/back.4bpp.lz"

gMonShinyPalette_Moroberry::
	.incbin "graphics/pokemon/moroberry/shiny.gbapal.lz"

gMonIcon_Moroberry::
	.incbin "graphics/pokemon/moroberry/icon.4bpp"

gMonFootprint_Moroberry::
	.incbin "graphics/pokemon/moroberry/footprint.1bpp"

gMonFrontPic_Boongory::
	.incbin "graphics/pokemon/boongory/front.4bpp.lz"

gMonPalette_Boongory::
	.incbin "graphics/pokemon/boongory/normal.gbapal.lz"

gMonBackPic_Boongory::
	.incbin "graphics/pokemon/boongory/back.4bpp.lz"

gMonShinyPalette_Boongory::
	.incbin "graphics/pokemon/boongory/shiny.gbapal.lz"

gMonIcon_Boongory::
	.incbin "graphics/pokemon/boongory/icon.4bpp"

gMonFootprint_Boongory::
	.incbin "graphics/pokemon/boongory/footprint.1bpp"

gMonFrontPic_Bludlop::
	.incbin "graphics/pokemon/bludlop/front.4bpp.lz"

gMonPalette_Bludlop::
	.incbin "graphics/pokemon/bludlop/normal.gbapal.lz"

gMonBackPic_Bludlop::
	.incbin "graphics/pokemon/bludlop/back.4bpp.lz"

gMonShinyPalette_Bludlop::
	.incbin "graphics/pokemon/bludlop/shiny.gbapal.lz"

gMonIcon_Bludlop::
	.incbin "graphics/pokemon/bludlop/icon.4bpp"

gMonFootprint_Bludlop::
	.incbin "graphics/pokemon/bludlop/footprint.1bpp"

gMonFrontPic_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/front.4bpp.lz"

gMonPalette_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/normal.gbapal.lz"

gMonBackPic_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/back.4bpp.lz"

gMonShinyPalette_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/shiny.gbapal.lz"

gMonIcon_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/icon.4bpp"

gMonFootprint_Vamkiri::
	.incbin "graphics/pokemon/vamkiri/footprint.1bpp"

gMonFrontPic_Shelcual::
	.incbin "graphics/pokemon/shelcual/front.4bpp.lz"

gMonPalette_Shelcual::
	.incbin "graphics/pokemon/shelcual/normal.gbapal.lz"

gMonBackPic_Shelcual::
	.incbin "graphics/pokemon/shelcual/back.4bpp.lz"

gMonShinyPalette_Shelcual::
	.incbin "graphics/pokemon/shelcual/shiny.gbapal.lz"

gMonIcon_Shelcual::
	.incbin "graphics/pokemon/shelcual/icon.4bpp"

gMonFootprint_Shelcual::
	.incbin "graphics/pokemon/shelcual/footprint.1bpp"

gMonFrontPic_Grecodale::
	.incbin "graphics/pokemon/grecodale/front.4bpp.lz"

gMonPalette_Grecodale::
	.incbin "graphics/pokemon/grecodale/normal.gbapal.lz"

gMonBackPic_Grecodale::
	.incbin "graphics/pokemon/grecodale/back.4bpp.lz"

gMonShinyPalette_Grecodale::
	.incbin "graphics/pokemon/grecodale/shiny.gbapal.lz"

gMonIcon_Grecodale::
	.incbin "graphics/pokemon/grecodale/icon.4bpp"

gMonFootprint_Grecodale::
	.incbin "graphics/pokemon/grecodale/footprint.1bpp"

gMonFrontPic_Alligrale::
	.incbin "graphics/pokemon/alligrale/front.4bpp.lz"

gMonPalette_Alligrale::
	.incbin "graphics/pokemon/alligrale/normal.gbapal.lz"

gMonBackPic_Alligrale::
	.incbin "graphics/pokemon/alligrale/back.4bpp.lz"

gMonShinyPalette_Alligrale::
	.incbin "graphics/pokemon/alligrale/shiny.gbapal.lz"

gMonIcon_Alligrale::
	.incbin "graphics/pokemon/alligrale/icon.4bpp"

gMonFootprint_Alligrale::
	.incbin "graphics/pokemon/alligrale/footprint.1bpp"

gMonFrontPic_Bellyo::
	.incbin "graphics/pokemon/bellyo/front.4bpp.lz"

gMonPalette_Bellyo::
	.incbin "graphics/pokemon/bellyo/normal.gbapal.lz"

gMonBackPic_Bellyo::
	.incbin "graphics/pokemon/bellyo/back.4bpp.lz"

gMonShinyPalette_Bellyo::
	.incbin "graphics/pokemon/bellyo/shiny.gbapal.lz"

gMonIcon_Bellyo::
	.incbin "graphics/pokemon/bellyo/icon.4bpp"

gMonFootprint_Bellyo::
	.incbin "graphics/pokemon/bellyo/footprint.1bpp"

gMonFrontPic_Drilluk::
	.incbin "graphics/pokemon/drilluk/front.4bpp.lz"

gMonPalette_Drilluk::
	.incbin "graphics/pokemon/drilluk/normal.gbapal.lz"

gMonBackPic_Drilluk::
	.incbin "graphics/pokemon/drilluk/back.4bpp.lz"

gMonShinyPalette_Drilluk::
	.incbin "graphics/pokemon/drilluk/shiny.gbapal.lz"

gMonIcon_Drilluk::
	.incbin "graphics/pokemon/drilluk/icon.4bpp"

gMonFootprint_Drilluk::
	.incbin "graphics/pokemon/drilluk/footprint.1bpp"

gMonFrontPic_Sangai::
	.incbin "graphics/pokemon/sangai/front.4bpp.lz"

gMonPalette_Sangai::
	.incbin "graphics/pokemon/sangai/normal.gbapal.lz"

gMonBackPic_Sangai::
	.incbin "graphics/pokemon/sangai/back.4bpp.lz"

gMonShinyPalette_Sangai::
	.incbin "graphics/pokemon/sangai/shiny.gbapal.lz"

gMonIcon_Sangai::
	.incbin "graphics/pokemon/sangai/icon.4bpp"

gMonFootprint_Sangai::
	.incbin "graphics/pokemon/sangai/footprint.1bpp"

gMonFrontPic_Betal::
	.incbin "graphics/pokemon/betal/front.4bpp.lz"

gMonPalette_Betal::
	.incbin "graphics/pokemon/betal/normal.gbapal.lz"

gMonBackPic_Betal::
	.incbin "graphics/pokemon/betal/back.4bpp.lz"

gMonShinyPalette_Betal::
	.incbin "graphics/pokemon/betal/shiny.gbapal.lz"

gMonIcon_Betal::
	.incbin "graphics/pokemon/betal/icon.4bpp"

gMonFootprint_Betal::
	.incbin "graphics/pokemon/betal/footprint.1bpp"

gMonFrontPic_Deemp::
	.incbin "graphics/pokemon/deemp/front.4bpp.lz"

gMonPalette_Deemp::
	.incbin "graphics/pokemon/deemp/normal.gbapal.lz"

gMonBackPic_Deemp::
	.incbin "graphics/pokemon/deemp/back.4bpp.lz"

gMonShinyPalette_Deemp::
	.incbin "graphics/pokemon/deemp/shiny.gbapal.lz"

gMonIcon_Deemp::
	.incbin "graphics/pokemon/deemp/icon.4bpp"

gMonFootprint_Deemp::
	.incbin "graphics/pokemon/deemp/footprint.1bpp"

gMonFrontPic_Trufkip::
	.incbin "graphics/pokemon/trufkip/front.4bpp.lz"

gMonPalette_Trufkip::
	.incbin "graphics/pokemon/trufkip/normal.gbapal.lz"

gMonBackPic_Trufkip::
	.incbin "graphics/pokemon/trufkip/back.4bpp.lz"

gMonShinyPalette_Trufkip::
	.incbin "graphics/pokemon/trufkip/shiny.gbapal.lz"

gMonIcon_Trufkip::
	.incbin "graphics/pokemon/trufkip/icon.4bpp"

gMonFootprint_Trufkip::
	.incbin "graphics/pokemon/trufkip/footprint.1bpp"

gMonFrontPic_Trufalo::
	.incbin "graphics/pokemon/trufalo/front.4bpp.lz"

gMonPalette_Trufalo::
	.incbin "graphics/pokemon/trufalo/normal.gbapal.lz"

gMonBackPic_Trufalo::
	.incbin "graphics/pokemon/trufalo/back.4bpp.lz"

gMonShinyPalette_Trufalo::
	.incbin "graphics/pokemon/trufalo/shiny.gbapal.lz"

gMonIcon_Trufalo::
	.incbin "graphics/pokemon/trufalo/icon.4bpp"

gMonFootprint_Trufalo::
	.incbin "graphics/pokemon/trufalo/footprint.1bpp"

gMonFrontPic_Burnco::
	.incbin "graphics/pokemon/burnco/front.4bpp.lz"

gMonPalette_Burnco::
	.incbin "graphics/pokemon/burnco/normal.gbapal.lz"

gMonBackPic_Burnco::
	.incbin "graphics/pokemon/burnco/back.4bpp.lz"

gMonShinyPalette_Burnco::
	.incbin "graphics/pokemon/burnco/shiny.gbapal.lz"

gMonIcon_Burnco::
	.incbin "graphics/pokemon/burnco/icon.4bpp"

gMonFootprint_Burnco::
	.incbin "graphics/pokemon/burnco/footprint.1bpp"

gMonFrontPic_Flameco::
	.incbin "graphics/pokemon/flameco/front.4bpp.lz"

gMonPalette_Flameco::
	.incbin "graphics/pokemon/flameco/normal.gbapal.lz"

gMonBackPic_Flameco::
	.incbin "graphics/pokemon/flameco/back.4bpp.lz"

gMonShinyPalette_Flameco::
	.incbin "graphics/pokemon/flameco/shiny.gbapal.lz"

gMonIcon_Flameco::
	.incbin "graphics/pokemon/flameco/icon.4bpp"

gMonFootprint_Flameco::
	.incbin "graphics/pokemon/flameco/footprint.1bpp"

gMonFrontPic_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/front.4bpp.lz"

gMonPalette_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/normal.gbapal.lz"

gMonBackPic_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/back.4bpp.lz"

gMonShinyPalette_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/shiny.gbapal.lz"

gMonIcon_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/icon.4bpp"

gMonFootprint_Hurgoose::
	.incbin "graphics/pokemon/hurgoose/footprint.1bpp"

gMonFrontPic_Donigoni::
	.incbin "graphics/pokemon/donigoni/front.4bpp.lz"

gMonPalette_Donigoni::
	.incbin "graphics/pokemon/donigoni/normal.gbapal.lz"

gMonBackPic_Donigoni::
	.incbin "graphics/pokemon/donigoni/back.4bpp.lz"

gMonShinyPalette_Donigoni::
	.incbin "graphics/pokemon/donigoni/shiny.gbapal.lz"

gMonIcon_Donigoni::
	.incbin "graphics/pokemon/donigoni/icon.4bpp"

gMonFootprint_Donigoni::
	.incbin "graphics/pokemon/donigoni/footprint.1bpp"

gMonFrontPic_Flysh::
	.incbin "graphics/pokemon/flysh/front.4bpp.lz"

gMonPalette_Flysh::
	.incbin "graphics/pokemon/flysh/normal.gbapal.lz"

gMonBackPic_Flysh::
	.incbin "graphics/pokemon/flysh/back.4bpp.lz"

gMonShinyPalette_Flysh::
	.incbin "graphics/pokemon/flysh/shiny.gbapal.lz"

gMonIcon_Flysh::
	.incbin "graphics/pokemon/flysh/icon.4bpp"

gMonFootprint_Flysh::
	.incbin "graphics/pokemon/flysh/footprint.1bpp"

gMonFrontPic_Trodic::
	.incbin "graphics/pokemon/trodic/front.4bpp.lz"

gMonPalette_Trodic::
	.incbin "graphics/pokemon/trodic/normal.gbapal.lz"

gMonBackPic_Trodic::
	.incbin "graphics/pokemon/trodic/back.4bpp.lz"

gMonShinyPalette_Trodic::
	.incbin "graphics/pokemon/trodic/shiny.gbapal.lz"

gMonIcon_Trodic::
	.incbin "graphics/pokemon/trodic/icon.4bpp"

gMonFootprint_Trodic::
	.incbin "graphics/pokemon/trodic/footprint.1bpp"

gMonFrontPic_Tidalo::
	.incbin "graphics/pokemon/tidalo/front.4bpp.lz"

gMonPalette_Tidalo::
	.incbin "graphics/pokemon/tidalo/normal.gbapal.lz"

gMonBackPic_Tidalo::
	.incbin "graphics/pokemon/tidalo/back.4bpp.lz"

gMonShinyPalette_Tidalo::
	.incbin "graphics/pokemon/tidalo/shiny.gbapal.lz"

gMonIcon_Tidalo::
	.incbin "graphics/pokemon/tidalo/icon.4bpp"

gMonFootprint_Tidalo::
	.incbin "graphics/pokemon/tidalo/footprint.1bpp"

gMonFrontPic_Polbear::
	.incbin "graphics/pokemon/polbear/front.4bpp.lz"

gMonPalette_Polbear::
	.incbin "graphics/pokemon/polbear/normal.gbapal.lz"

gMonBackPic_Polbear::
	.incbin "graphics/pokemon/polbear/back.4bpp.lz"

gMonShinyPalette_Polbear::
	.incbin "graphics/pokemon/polbear/shiny.gbapal.lz"

gMonIcon_Polbear::
	.incbin "graphics/pokemon/polbear/icon.4bpp"

gMonFootprint_Polbear::
	.incbin "graphics/pokemon/polbear/footprint.1bpp"

gMonFrontPic_Arbatross::
	.incbin "graphics/pokemon/arbatross/front.4bpp.lz"

gMonPalette_Arbatross::
	.incbin "graphics/pokemon/arbatross/normal.gbapal.lz"

gMonBackPic_Arbatross::
	.incbin "graphics/pokemon/arbatross/back.4bpp.lz"

gMonShinyPalette_Arbatross::
	.incbin "graphics/pokemon/arbatross/shiny.gbapal.lz"

gMonIcon_Arbatross::
	.incbin "graphics/pokemon/arbatross/icon.4bpp"

gMonFootprint_Arbatross::
	.incbin "graphics/pokemon/arbatross/footprint.1bpp"

gMonFrontPic_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/front.4bpp.lz"

gMonPalette_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/normal.gbapal.lz"

gMonBackPic_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/back.4bpp.lz"

gMonShinyPalette_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/shiny.gbapal.lz"

gMonIcon_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/icon.4bpp"

gMonFootprint_Sneetchy::
	.incbin "graphics/pokemon/sneetchy/footprint.1bpp"

gMonFrontPic_Garedar::
	.incbin "graphics/pokemon/garedar/front.4bpp.lz"

gMonPalette_Garedar::
	.incbin "graphics/pokemon/garedar/normal.gbapal.lz"

gMonBackPic_Garedar::
	.incbin "graphics/pokemon/garedar/back.4bpp.lz"

gMonShinyPalette_Garedar::
	.incbin "graphics/pokemon/garedar/shiny.gbapal.lz"

gMonIcon_Garedar::
	.incbin "graphics/pokemon/garedar/icon.4bpp"

gMonFootprint_Garedar::
	.incbin "graphics/pokemon/garedar/footprint.1bpp"

gMonFrontPic_Farizard::
	.incbin "graphics/pokemon/farizard/front.4bpp.lz"

gMonPalette_Farizard::
	.incbin "graphics/pokemon/farizard/normal.gbapal.lz"

gMonBackPic_Farizard::
	.incbin "graphics/pokemon/farizard/back.4bpp.lz"

gMonShinyPalette_Farizard::
	.incbin "graphics/pokemon/farizard/shiny.gbapal.lz"

gMonIcon_Farizard::
	.incbin "graphics/pokemon/farizard/icon.4bpp"

gMonFootprint_Farizard::
	.incbin "graphics/pokemon/farizard/footprint.1bpp"

gMonFrontPic_Dralula::
	.incbin "graphics/pokemon/dralula/front.4bpp.lz"

gMonPalette_Dralula::
	.incbin "graphics/pokemon/dralula/normal.gbapal.lz"

gMonBackPic_Dralula::
	.incbin "graphics/pokemon/dralula/back.4bpp.lz"

gMonShinyPalette_Dralula::
	.incbin "graphics/pokemon/dralula/shiny.gbapal.lz"

gMonIcon_Dralula::
	.incbin "graphics/pokemon/dralula/icon.4bpp"

gMonFootprint_Dralula::
	.incbin "graphics/pokemon/dralula/footprint.1bpp"

gMonFrontPic_Bernardog::
	.incbin "graphics/pokemon/bernardog/front.4bpp.lz"

gMonPalette_Bernardog::
	.incbin "graphics/pokemon/bernardog/normal.gbapal.lz"

gMonBackPic_Bernardog::
	.incbin "graphics/pokemon/bernardog/back.4bpp.lz"

gMonShinyPalette_Bernardog::
	.incbin "graphics/pokemon/bernardog/shiny.gbapal.lz"

gMonIcon_Bernardog::
	.incbin "graphics/pokemon/bernardog/icon.4bpp"

gMonFootprint_Bernardog::
	.incbin "graphics/pokemon/bernardog/footprint.1bpp"

gMonFrontPic_Rescudog::
	.incbin "graphics/pokemon/rescudog/front.4bpp.lz"

gMonPalette_Rescudog::
	.incbin "graphics/pokemon/rescudog/normal.gbapal.lz"

gMonBackPic_Rescudog::
	.incbin "graphics/pokemon/rescudog/back.4bpp.lz"

gMonShinyPalette_Rescudog::
	.incbin "graphics/pokemon/rescudog/shiny.gbapal.lz"

gMonIcon_Rescudog::
	.incbin "graphics/pokemon/rescudog/icon.4bpp"

gMonFootprint_Rescudog::
	.incbin "graphics/pokemon/rescudog/footprint.1bpp"

gMonFrontPic_Emrev::
	.incbin "graphics/pokemon/emrev/front.4bpp.lz"

gMonPalette_Emrev::
	.incbin "graphics/pokemon/emrev/normal.gbapal.lz"

gMonBackPic_Emrev::
	.incbin "graphics/pokemon/emrev/back.4bpp.lz"

gMonShinyPalette_Emrev::
	.incbin "graphics/pokemon/emrev/shiny.gbapal.lz"

gMonIcon_Emrev::
	.incbin "graphics/pokemon/emrev/icon.4bpp"

gMonFootprint_Emrev::
	.incbin "graphics/pokemon/emrev/footprint.1bpp"

gMonFrontPic_Grazilla::
	.incbin "graphics/pokemon/grazilla/front.4bpp.lz"

gMonPalette_Grazilla::
	.incbin "graphics/pokemon/grazilla/normal.gbapal.lz"

gMonBackPic_Grazilla::
	.incbin "graphics/pokemon/grazilla/back.4bpp.lz"

gMonShinyPalette_Grazilla::
	.incbin "graphics/pokemon/grazilla/shiny.gbapal.lz"

gMonIcon_Grazilla::
	.incbin "graphics/pokemon/grazilla/icon.4bpp"

gMonFootprint_Grazilla::
	.incbin "graphics/pokemon/grazilla/footprint.1bpp"

gMonFrontPic_Ninjice::
	.incbin "graphics/pokemon/ninjice/front.4bpp.lz"

gMonPalette_Ninjice::
	.incbin "graphics/pokemon/ninjice/normal.gbapal.lz"

gMonBackPic_Ninjice::
	.incbin "graphics/pokemon/ninjice/back.4bpp.lz"

gMonShinyPalette_Ninjice::
	.incbin "graphics/pokemon/ninjice/shiny.gbapal.lz"

gMonIcon_Ninjice::
	.incbin "graphics/pokemon/ninjice/icon.4bpp"

gMonFootprint_Ninjice::
	.incbin "graphics/pokemon/ninjice/footprint.1bpp"

gMonFrontPic_Aztakle::
	.incbin "graphics/pokemon/aztakle/front.4bpp.lz"

gMonPalette_Aztakle::
	.incbin "graphics/pokemon/aztakle/normal.gbapal.lz"

gMonBackPic_Aztakle::
	.incbin "graphics/pokemon/aztakle/back.4bpp.lz"

gMonShinyPalette_Aztakle::
	.incbin "graphics/pokemon/aztakle/shiny.gbapal.lz"

gMonIcon_Aztakle::
	.incbin "graphics/pokemon/aztakle/icon.4bpp"

gMonFootprint_Aztakle::
	.incbin "graphics/pokemon/aztakle/footprint.1bpp"

gMonFrontPic_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/front.4bpp.lz"

gMonPalette_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/normal.gbapal.lz"

gMonBackPic_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/back.4bpp.lz"

gMonShinyPalette_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/shiny.gbapal.lz"

gMonIcon_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/icon.4bpp"

gMonFootprint_Chinnakle::
	.incbin "graphics/pokemon/chinnakle/footprint.1bpp"

gMonFrontPic_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/front.4bpp.lz"

gMonPalette_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/normal.gbapal.lz"

gMonBackPic_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/back.4bpp.lz"

gMonShinyPalette_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/shiny.gbapal.lz"

gMonIcon_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/icon.4bpp"

gMonFootprint_Jarximaux::
	.incbin "graphics/pokemon/jarximaux/footprint.1bpp"

gMonFrontPic_Etod::
	.incbin "graphics/pokemon/etod/front.4bpp.lz"

gMonPalette_Etod::
	.incbin "graphics/pokemon/etod/normal.gbapal.lz"

gMonBackPic_Etod::
	.incbin "graphics/pokemon/etod/back.4bpp.lz"

gMonShinyPalette_Etod::
	.incbin "graphics/pokemon/etod/shiny.gbapal.lz"

gMonIcon_Etod::
	.incbin "graphics/pokemon/etod/icon.4bpp"

gMonFootprint_Etod::
	.incbin "graphics/pokemon/etod/footprint.1bpp"

gMonFrontPic_Tarsony::
	.incbin "graphics/pokemon/tarsony/front.4bpp.lz"

gMonPalette_Tarsony::
	.incbin "graphics/pokemon/tarsony/normal.gbapal.lz"

gMonBackPic_Tarsony::
	.incbin "graphics/pokemon/tarsony/back.4bpp.lz"

gMonShinyPalette_Tarsony::
	.incbin "graphics/pokemon/tarsony/shiny.gbapal.lz"

gMonIcon_Tarsony::
	.incbin "graphics/pokemon/tarsony/icon.4bpp"

gMonFootprint_Tarsony::
	.incbin "graphics/pokemon/tarsony/footprint.1bpp"

gMonFrontPic_Gurtan::
	.incbin "graphics/pokemon/gurtan/front.4bpp.lz"

gMonPalette_Gurtan::
	.incbin "graphics/pokemon/gurtan/normal.gbapal.lz"

gMonBackPic_Gurtan::
	.incbin "graphics/pokemon/gurtan/back.4bpp.lz"

gMonShinyPalette_Gurtan::
	.incbin "graphics/pokemon/gurtan/shiny.gbapal.lz"

gMonIcon_Gurtan::
	.incbin "graphics/pokemon/gurtan/icon.4bpp"

gMonFootprint_Gurtan::
	.incbin "graphics/pokemon/gurtan/footprint.1bpp"

gMonFrontPic_Conqari::
	.incbin "graphics/pokemon/conqari/front.4bpp.lz"

gMonPalette_Conqari::
	.incbin "graphics/pokemon/conqari/normal.gbapal.lz"

gMonBackPic_Conqari::
	.incbin "graphics/pokemon/conqari/back.4bpp.lz"

gMonShinyPalette_Conqari::
	.incbin "graphics/pokemon/conqari/shiny.gbapal.lz"

gMonIcon_Conqari::
	.incbin "graphics/pokemon/conqari/icon.4bpp"

gMonFootprint_Conqari::
	.incbin "graphics/pokemon/conqari/footprint.1bpp"

gMonFrontPic_Titatoad::
	.incbin "graphics/pokemon/titatoad/front.4bpp.lz"

gMonPalette_Titatoad::
	.incbin "graphics/pokemon/titatoad/normal.gbapal.lz"

gMonBackPic_Titatoad::
	.incbin "graphics/pokemon/titatoad/back.4bpp.lz"

gMonShinyPalette_Titatoad::
	.incbin "graphics/pokemon/titatoad/shiny.gbapal.lz"

gMonIcon_Titatoad::
	.incbin "graphics/pokemon/titatoad/icon.4bpp"

gMonFootprint_Titatoad::
	.incbin "graphics/pokemon/titatoad/footprint.1bpp"

gMonFrontPic_Titafrota::
	.incbin "graphics/pokemon/titafrota/front.4bpp.lz"

gMonPalette_Titafrota::
	.incbin "graphics/pokemon/titafrota/normal.gbapal.lz"

gMonBackPic_Titafrota::
	.incbin "graphics/pokemon/titafrota/back.4bpp.lz"

gMonShinyPalette_Titafrota::
	.incbin "graphics/pokemon/titafrota/shiny.gbapal.lz"

gMonIcon_Titafrota::
	.incbin "graphics/pokemon/titafrota/icon.4bpp"

gMonFootprint_Titafrota::
	.incbin "graphics/pokemon/titafrota/footprint.1bpp"

gMonFrontPic_Titallama::
	.incbin "graphics/pokemon/titallama/front.4bpp.lz"

gMonPalette_Titallama::
	.incbin "graphics/pokemon/titallama/normal.gbapal.lz"

gMonBackPic_Titallama::
	.incbin "graphics/pokemon/titallama/back.4bpp.lz"

gMonShinyPalette_Titallama::
	.incbin "graphics/pokemon/titallama/shiny.gbapal.lz"

gMonIcon_Titallama::
	.incbin "graphics/pokemon/titallama/icon.4bpp"

gMonFootprint_Titallama::
	.incbin "graphics/pokemon/titallama/footprint.1bpp"

gMonFrontPic_Crogronk::
	.incbin "graphics/pokemon/crogronk/front.4bpp.lz"

gMonPalette_Crogronk::
	.incbin "graphics/pokemon/crogronk/normal.gbapal.lz"

gMonBackPic_Crogronk::
	.incbin "graphics/pokemon/crogronk/back.4bpp.lz"

gMonShinyPalette_Crogronk::
	.incbin "graphics/pokemon/crogronk/shiny.gbapal.lz"

gMonIcon_Crogronk::
	.incbin "graphics/pokemon/crogronk/icon.4bpp"

gMonFootprint_Crogronk::
	.incbin "graphics/pokemon/crogronk/footprint.1bpp"

gMonFrontPic_Skankrin::
	.incbin "graphics/pokemon/skankrin/front.4bpp.lz"

gMonPalette_Skankrin::
	.incbin "graphics/pokemon/skankrin/normal.gbapal.lz"

gMonBackPic_Skankrin::
	.incbin "graphics/pokemon/skankrin/back.4bpp.lz"

gMonShinyPalette_Skankrin::
	.incbin "graphics/pokemon/skankrin/shiny.gbapal.lz"

gMonIcon_Skankrin::
	.incbin "graphics/pokemon/skankrin/icon.4bpp"

gMonFootprint_Skankrin::
	.incbin "graphics/pokemon/skankrin/footprint.1bpp"

gMonFrontPic_Baestalix::
	.incbin "graphics/pokemon/baestalix/front.4bpp.lz"

gMonPalette_Baestalix::
	.incbin "graphics/pokemon/baestalix/normal.gbapal.lz"

gMonBackPic_Baestalix::
	.incbin "graphics/pokemon/baestalix/back.4bpp.lz"

gMonShinyPalette_Baestalix::
	.incbin "graphics/pokemon/baestalix/shiny.gbapal.lz"

gMonIcon_Baestalix::
	.incbin "graphics/pokemon/baestalix/icon.4bpp"

gMonFootprint_Baestalix::
	.incbin "graphics/pokemon/baestalix/footprint.1bpp"

gMonFrontPic_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/front.4bpp.lz"

gMonPalette_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/normal.gbapal.lz"

gMonBackPic_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/back.4bpp.lz"

gMonShinyPalette_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/shiny.gbapal.lz"

gMonIcon_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/icon.4bpp"

gMonFootprint_Vivaczo::
	.incbin "graphics/pokemon/vivaczo/footprint.1bpp"

gMonFrontPic_Shaddire::
	.incbin "graphics/pokemon/shaddire/front.4bpp.lz"

gMonPalette_Shaddire::
	.incbin "graphics/pokemon/shaddire/normal.gbapal.lz"

gMonBackPic_Shaddire::
	.incbin "graphics/pokemon/shaddire/back.4bpp.lz"

gMonShinyPalette_Shaddire::
	.incbin "graphics/pokemon/shaddire/shiny.gbapal.lz"

gMonIcon_Shaddire::
	.incbin "graphics/pokemon/shaddire/icon.4bpp"

gMonFootprint_Shaddire::
	.incbin "graphics/pokemon/shaddire/footprint.1bpp"

gMonFrontPic_Mothatura::
	.incbin "graphics/pokemon/mothatura/front.4bpp.lz"

gMonPalette_Mothatura::
	.incbin "graphics/pokemon/mothatura/normal.gbapal.lz"

gMonBackPic_Mothatura::
	.incbin "graphics/pokemon/mothatura/back.4bpp.lz"

gMonShinyPalette_Mothatura::
	.incbin "graphics/pokemon/mothatura/shiny.gbapal.lz"

gMonIcon_Mothatura::
	.incbin "graphics/pokemon/mothatura/icon.4bpp"

gMonFootprint_Mothatura::
	.incbin "graphics/pokemon/mothatura/footprint.1bpp"

gMonFrontPic_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/front.4bpp.lz"

gMonPalette_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/normal.gbapal.lz"

gMonBackPic_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/back.4bpp.lz"

gMonShinyPalette_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/shiny.gbapal.lz"

gMonIcon_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/icon.4bpp"

gMonFootprint_Pokemon_252::
	.incbin "graphics/pokemon/pokemon_252/footprint.1bpp"

gMonFrontPic_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/front.4bpp.lz"

gMonPalette_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/normal.gbapal.lz"

gMonBackPic_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/back.4bpp.lz"

gMonShinyPalette_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/shiny.gbapal.lz"

gMonIcon_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/icon.4bpp"

gMonFootprint_Pokemon_253::
	.incbin "graphics/pokemon/pokemon_253/footprint.1bpp"

gMonFrontPic_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/front.4bpp.lz"

gMonPalette_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/normal.gbapal.lz"

gMonBackPic_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/back.4bpp.lz"

gMonShinyPalette_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/shiny.gbapal.lz"

gMonIcon_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/icon.4bpp"

gMonFootprint_Pokemon_254::
	.incbin "graphics/pokemon/pokemon_254/footprint.1bpp"

gMonFrontPic_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/front.4bpp.lz"

gMonPalette_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/normal.gbapal.lz"

gMonBackPic_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/back.4bpp.lz"

gMonShinyPalette_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/shiny.gbapal.lz"

gMonIcon_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/icon.4bpp"

gMonFootprint_Pokemon_255::
	.incbin "graphics/pokemon/pokemon_255/footprint.1bpp"

gMonFrontPic_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/front.4bpp.lz"

gMonPalette_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/normal.gbapal.lz"

gMonBackPic_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/back.4bpp.lz"

gMonShinyPalette_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/shiny.gbapal.lz"

gMonIcon_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/icon.4bpp"

gMonFootprint_Pokemon_256::
	.incbin "graphics/pokemon/pokemon_256/footprint.1bpp"

gMonFrontPic_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/front.4bpp.lz"

gMonPalette_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/normal.gbapal.lz"

gMonBackPic_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/back.4bpp.lz"

gMonShinyPalette_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/shiny.gbapal.lz"

gMonIcon_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/icon.4bpp"

gMonFootprint_Pokemon_257::
	.incbin "graphics/pokemon/pokemon_257/footprint.1bpp"

gMonFrontPic_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/front.4bpp.lz"

gMonPalette_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/normal.gbapal.lz"

gMonBackPic_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/back.4bpp.lz"

gMonShinyPalette_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/shiny.gbapal.lz"

gMonIcon_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/icon.4bpp"

gMonFootprint_Pokemon_258::
	.incbin "graphics/pokemon/pokemon_258/footprint.1bpp"

gMonFrontPic_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/front.4bpp.lz"

gMonPalette_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/normal.gbapal.lz"

gMonBackPic_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/back.4bpp.lz"

gMonShinyPalette_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/shiny.gbapal.lz"

gMonIcon_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/icon.4bpp"

gMonFootprint_Pokemon_259::
	.incbin "graphics/pokemon/pokemon_259/footprint.1bpp"

gMonFrontPic_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/front.4bpp.lz"

gMonPalette_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/normal.gbapal.lz"

gMonBackPic_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/back.4bpp.lz"

gMonShinyPalette_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/shiny.gbapal.lz"

gMonIcon_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/icon.4bpp"

gMonFootprint_Pokemon_260::
	.incbin "graphics/pokemon/pokemon_260/footprint.1bpp"

gMonFrontPic_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/front.4bpp.lz"

gMonPalette_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/normal.gbapal.lz"

gMonBackPic_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/back.4bpp.lz"

gMonShinyPalette_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/shiny.gbapal.lz"

gMonIcon_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/icon.4bpp"

gMonFootprint_Pokemon_261::
	.incbin "graphics/pokemon/pokemon_261/footprint.1bpp"

gMonFrontPic_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/front.4bpp.lz"

gMonPalette_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/normal.gbapal.lz"

gMonBackPic_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/back.4bpp.lz"

gMonShinyPalette_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/shiny.gbapal.lz"

gMonIcon_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/icon.4bpp"

gMonFootprint_Pokemon_262::
	.incbin "graphics/pokemon/pokemon_262/footprint.1bpp"

gMonFrontPic_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/front.4bpp.lz"

gMonPalette_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/normal.gbapal.lz"

gMonBackPic_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/back.4bpp.lz"

gMonShinyPalette_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/shiny.gbapal.lz"

gMonIcon_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/icon.4bpp"

gMonFootprint_Pokemon_263::
	.incbin "graphics/pokemon/pokemon_263/footprint.1bpp"

gMonFrontPic_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/front.4bpp.lz"

gMonPalette_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/normal.gbapal.lz"

gMonBackPic_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/back.4bpp.lz"

gMonShinyPalette_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/shiny.gbapal.lz"

gMonIcon_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/icon.4bpp"

gMonFootprint_Pokemon_264::
	.incbin "graphics/pokemon/pokemon_264/footprint.1bpp"

gMonFrontPic_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/front.4bpp.lz"

gMonPalette_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/normal.gbapal.lz"

gMonBackPic_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/back.4bpp.lz"

gMonShinyPalette_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/shiny.gbapal.lz"

gMonIcon_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/icon.4bpp"

gMonFootprint_Pokemon_265::
	.incbin "graphics/pokemon/pokemon_265/footprint.1bpp"

gMonFrontPic_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/front.4bpp.lz"

gMonPalette_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/normal.gbapal.lz"

gMonBackPic_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/back.4bpp.lz"

gMonShinyPalette_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/shiny.gbapal.lz"

gMonIcon_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/icon.4bpp"

gMonFootprint_Pokemon_266::
	.incbin "graphics/pokemon/pokemon_266/footprint.1bpp"

gMonFrontPic_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/front.4bpp.lz"

gMonPalette_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/normal.gbapal.lz"

gMonBackPic_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/back.4bpp.lz"

gMonShinyPalette_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/shiny.gbapal.lz"

gMonIcon_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/icon.4bpp"

gMonFootprint_Pokemon_267::
	.incbin "graphics/pokemon/pokemon_267/footprint.1bpp"

gMonFrontPic_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/front.4bpp.lz"

gMonPalette_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/normal.gbapal.lz"

gMonBackPic_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/back.4bpp.lz"

gMonShinyPalette_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/shiny.gbapal.lz"

gMonIcon_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/icon.4bpp"

gMonFootprint_Pokemon_268::
	.incbin "graphics/pokemon/pokemon_268/footprint.1bpp"

gMonFrontPic_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/front.4bpp.lz"

gMonPalette_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/normal.gbapal.lz"

gMonBackPic_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/back.4bpp.lz"

gMonShinyPalette_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/shiny.gbapal.lz"

gMonIcon_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/icon.4bpp"

gMonFootprint_Pokemon_269::
	.incbin "graphics/pokemon/pokemon_269/footprint.1bpp"

gMonFrontPic_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/front.4bpp.lz"

gMonPalette_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/normal.gbapal.lz"

gMonBackPic_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/back.4bpp.lz"

gMonShinyPalette_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/shiny.gbapal.lz"

gMonIcon_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/icon.4bpp"

gMonFootprint_Pokemon_270::
	.incbin "graphics/pokemon/pokemon_270/footprint.1bpp"

gMonFrontPic_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/front.4bpp.lz"

gMonPalette_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/normal.gbapal.lz"

gMonBackPic_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/back.4bpp.lz"

gMonShinyPalette_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/shiny.gbapal.lz"

gMonIcon_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/icon.4bpp"

gMonFootprint_Pokemon_271::
	.incbin "graphics/pokemon/pokemon_271/footprint.1bpp"

gMonFrontPic_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/front.4bpp.lz"

gMonPalette_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/normal.gbapal.lz"

gMonBackPic_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/back.4bpp.lz"

gMonShinyPalette_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/shiny.gbapal.lz"

gMonIcon_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/icon.4bpp"

gMonFootprint_Pokemon_272::
	.incbin "graphics/pokemon/pokemon_272/footprint.1bpp"

gMonFrontPic_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/front.4bpp.lz"

gMonPalette_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/normal.gbapal.lz"

gMonBackPic_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/back.4bpp.lz"

gMonShinyPalette_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/shiny.gbapal.lz"

gMonIcon_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/icon.4bpp"

gMonFootprint_Pokemon_273::
	.incbin "graphics/pokemon/pokemon_273/footprint.1bpp"

gMonFrontPic_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/front.4bpp.lz"

gMonPalette_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/normal.gbapal.lz"

gMonBackPic_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/back.4bpp.lz"

gMonShinyPalette_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/shiny.gbapal.lz"

gMonIcon_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/icon.4bpp"

gMonFootprint_Pokemon_274::
	.incbin "graphics/pokemon/pokemon_274/footprint.1bpp"

gMonFrontPic_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/front.4bpp.lz"

gMonPalette_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/normal.gbapal.lz"

gMonBackPic_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/back.4bpp.lz"

gMonShinyPalette_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/shiny.gbapal.lz"

gMonIcon_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/icon.4bpp"

gMonFootprint_Pokemon_275::
	.incbin "graphics/pokemon/pokemon_275/footprint.1bpp"

gMonFrontPic_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/front.4bpp.lz"

gMonPalette_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/normal.gbapal.lz"

gMonBackPic_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/back.4bpp.lz"

gMonShinyPalette_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/shiny.gbapal.lz"

gMonIcon_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/icon.4bpp"

gMonFootprint_Pokemon_276::
	.incbin "graphics/pokemon/pokemon_276/footprint.1bpp"

gMonFrontPic_Seegg::
	.incbin "graphics/pokemon/seegg/front.4bpp.lz"

gMonPalette_Seegg::
	.incbin "graphics/pokemon/seegg/normal.gbapal.lz"

gMonBackPic_Seegg::
	.incbin "graphics/pokemon/seegg/back.4bpp.lz"

gMonShinyPalette_Seegg::
	.incbin "graphics/pokemon/seegg/shiny.gbapal.lz"

gMonIcon_Seegg::
	.incbin "graphics/pokemon/seegg/icon.4bpp"

gMonFootprint_Seegg::
	.incbin "graphics/pokemon/seegg/footprint.1bpp"

gMonFrontPic_Flowaby::
	.incbin "graphics/pokemon/flowaby/front.4bpp.lz"

gMonPalette_Flowaby::
	.incbin "graphics/pokemon/flowaby/normal.gbapal.lz"

gMonBackPic_Flowaby::
	.incbin "graphics/pokemon/flowaby/back.4bpp.lz"

gMonShinyPalette_Flowaby::
	.incbin "graphics/pokemon/flowaby/shiny.gbapal.lz"

gMonIcon_Flowaby::
	.incbin "graphics/pokemon/flowaby/icon.4bpp"

gMonFootprint_Flowaby::
	.incbin "graphics/pokemon/flowaby/footprint.1bpp"

gMonFrontPic_Jardino::
	.incbin "graphics/pokemon/jardino/front.4bpp.lz"

gMonPalette_Jardino::
	.incbin "graphics/pokemon/jardino/normal.gbapal.lz"

gMonBackPic_Jardino::
	.incbin "graphics/pokemon/jardino/back.4bpp.lz"

gMonShinyPalette_Jardino::
	.incbin "graphics/pokemon/jardino/shiny.gbapal.lz"

gMonIcon_Jardino::
	.incbin "graphics/pokemon/jardino/icon.4bpp"

gMonFootprint_Jardino::
	.incbin "graphics/pokemon/jardino/footprint.1bpp"

gMonFrontPic_Firegg::
	.incbin "graphics/pokemon/firegg/front.4bpp.lz"

gMonPalette_Firegg::
	.incbin "graphics/pokemon/firegg/normal.gbapal.lz"

gMonBackPic_Firegg::
	.incbin "graphics/pokemon/firegg/back.4bpp.lz"

gMonShinyPalette_Firegg::
	.incbin "graphics/pokemon/firegg/shiny.gbapal.lz"

gMonIcon_Firegg::
	.incbin "graphics/pokemon/firegg/icon.4bpp"

gMonFootprint_Firegg::
	.incbin "graphics/pokemon/firegg/footprint.1bpp"

gMonFrontPic_Embaby::
	.incbin "graphics/pokemon/embaby/front.4bpp.lz"

gMonPalette_Embaby::
	.incbin "graphics/pokemon/embaby/normal.gbapal.lz"

gMonBackPic_Embaby::
	.incbin "graphics/pokemon/embaby/back.4bpp.lz"

gMonShinyPalette_Embaby::
	.incbin "graphics/pokemon/embaby/shiny.gbapal.lz"

gMonIcon_Embaby::
	.incbin "graphics/pokemon/embaby/icon.4bpp"

gMonFootprint_Embaby::
	.incbin "graphics/pokemon/embaby/footprint.1bpp"

gMonFrontPic_Tyradino::
	.incbin "graphics/pokemon/tyradino/front.4bpp.lz"

gMonPalette_Tyradino::
	.incbin "graphics/pokemon/tyradino/normal.gbapal.lz"

gMonBackPic_Tyradino::
	.incbin "graphics/pokemon/tyradino/back.4bpp.lz"

gMonShinyPalette_Tyradino::
	.incbin "graphics/pokemon/tyradino/shiny.gbapal.lz"

gMonIcon_Tyradino::
	.incbin "graphics/pokemon/tyradino/icon.4bpp"

gMonFootprint_Tyradino::
	.incbin "graphics/pokemon/tyradino/footprint.1bpp"

gMonFrontPic_Aquegg::
	.incbin "graphics/pokemon/aquegg/front.4bpp.lz"

gMonPalette_Aquegg::
	.incbin "graphics/pokemon/aquegg/normal.gbapal.lz"

gMonBackPic_Aquegg::
	.incbin "graphics/pokemon/aquegg/back.4bpp.lz"

gMonShinyPalette_Aquegg::
	.incbin "graphics/pokemon/aquegg/shiny.gbapal.lz"

gMonIcon_Aquegg::
	.incbin "graphics/pokemon/aquegg/icon.4bpp"

gMonFootprint_Aquegg::
	.incbin "graphics/pokemon/aquegg/footprint.1bpp"

gMonFrontPic_Ornaby::
	.incbin "graphics/pokemon/ornaby/front.4bpp.lz"

gMonPalette_Ornaby::
	.incbin "graphics/pokemon/ornaby/normal.gbapal.lz"

gMonBackPic_Ornaby::
	.incbin "graphics/pokemon/ornaby/back.4bpp.lz"

gMonShinyPalette_Ornaby::
	.incbin "graphics/pokemon/ornaby/shiny.gbapal.lz"

gMonIcon_Ornaby::
	.incbin "graphics/pokemon/ornaby/icon.4bpp"

gMonFootprint_Ornaby::
	.incbin "graphics/pokemon/ornaby/footprint.1bpp"

gMonFrontPic_Oceadino::
	.incbin "graphics/pokemon/oceadino/front.4bpp.lz"

gMonPalette_Oceadino::
	.incbin "graphics/pokemon/oceadino/normal.gbapal.lz"

gMonBackPic_Oceadino::
	.incbin "graphics/pokemon/oceadino/back.4bpp.lz"

gMonShinyPalette_Oceadino::
	.incbin "graphics/pokemon/oceadino/shiny.gbapal.lz"

gMonIcon_Oceadino::
	.incbin "graphics/pokemon/oceadino/icon.4bpp"

gMonFootprint_Oceadino::
	.incbin "graphics/pokemon/oceadino/footprint.1bpp"

gMonFrontPic_Sever::
	.incbin "graphics/pokemon/sever/front.4bpp.lz"

gMonPalette_Sever::
	.incbin "graphics/pokemon/sever/normal.gbapal.lz"

gMonBackPic_Sever::
	.incbin "graphics/pokemon/sever/back.4bpp.lz"

gMonShinyPalette_Sever::
	.incbin "graphics/pokemon/sever/shiny.gbapal.lz"

gMonIcon_Sever::
	.incbin "graphics/pokemon/sever/icon.4bpp"

gMonFootprint_Sever::
	.incbin "graphics/pokemon/sever/footprint.1bpp"

gMonFrontPic_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/front.4bpp.lz"

gMonPalette_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/normal.gbapal.lz"

gMonBackPic_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/back.4bpp.lz"

gMonShinyPalette_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/shiny.gbapal.lz"

gMonIcon_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/icon.4bpp"

gMonFootprint_Ayewiraz::
	.incbin "graphics/pokemon/ayewiraz/footprint.1bpp"

gMonFrontPic_Squirriti::
	.incbin "graphics/pokemon/squirriti/front.4bpp.lz"

gMonPalette_Squirriti::
	.incbin "graphics/pokemon/squirriti/normal.gbapal.lz"

gMonBackPic_Squirriti::
	.incbin "graphics/pokemon/squirriti/back.4bpp.lz"

gMonShinyPalette_Squirriti::
	.incbin "graphics/pokemon/squirriti/shiny.gbapal.lz"

gMonIcon_Squirriti::
	.incbin "graphics/pokemon/squirriti/icon.4bpp"

gMonFootprint_Squirriti::
	.incbin "graphics/pokemon/squirriti/footprint.1bpp"

gMonFrontPic_Acornel::
	.incbin "graphics/pokemon/acornel/front.4bpp.lz"

gMonPalette_Acornel::
	.incbin "graphics/pokemon/acornel/normal.gbapal.lz"

gMonBackPic_Acornel::
	.incbin "graphics/pokemon/acornel/back.4bpp.lz"

gMonShinyPalette_Acornel::
	.incbin "graphics/pokemon/acornel/shiny.gbapal.lz"

gMonIcon_Acornel::
	.incbin "graphics/pokemon/acornel/icon.4bpp"

gMonFootprint_Acornel::
	.incbin "graphics/pokemon/acornel/footprint.1bpp"

gMonFrontPic_Larvly::
	.incbin "graphics/pokemon/larvly/front.4bpp.lz"

gMonPalette_Larvly::
	.incbin "graphics/pokemon/larvly/normal.gbapal.lz"

gMonBackPic_Larvly::
	.incbin "graphics/pokemon/larvly/back.4bpp.lz"

gMonShinyPalette_Larvly::
	.incbin "graphics/pokemon/larvly/shiny.gbapal.lz"

gMonIcon_Larvly::
	.incbin "graphics/pokemon/larvly/icon.4bpp"

gMonFootprint_Larvly::
	.incbin "graphics/pokemon/larvly/footprint.1bpp"

gMonFrontPic_Cricoon::
	.incbin "graphics/pokemon/cricoon/front.4bpp.lz"

gMonPalette_Cricoon::
	.incbin "graphics/pokemon/cricoon/normal.gbapal.lz"

gMonBackPic_Cricoon::
	.incbin "graphics/pokemon/cricoon/back.4bpp.lz"

gMonShinyPalette_Cricoon::
	.incbin "graphics/pokemon/cricoon/shiny.gbapal.lz"

gMonIcon_Cricoon::
	.incbin "graphics/pokemon/cricoon/icon.4bpp"

gMonFootprint_Cricoon::
	.incbin "graphics/pokemon/cricoon/footprint.1bpp"

gMonFrontPic_Cricrit::
	.incbin "graphics/pokemon/cricrit/front.4bpp.lz"

gMonPalette_Cricrit::
	.incbin "graphics/pokemon/cricrit/normal.gbapal.lz"

gMonBackPic_Cricrit::
	.incbin "graphics/pokemon/cricrit/back.4bpp.lz"

gMonShinyPalette_Cricrit::
	.incbin "graphics/pokemon/cricrit/shiny.gbapal.lz"

gMonIcon_Cricrit::
	.incbin "graphics/pokemon/cricrit/icon.4bpp"

gMonFootprint_Cricrit::
	.incbin "graphics/pokemon/cricrit/footprint.1bpp"

gMonFrontPic_Composcoon::
	.incbin "graphics/pokemon/composcoon/front.4bpp.lz"

gMonPalette_Composcoon::
	.incbin "graphics/pokemon/composcoon/normal.gbapal.lz"

gMonBackPic_Composcoon::
	.incbin "graphics/pokemon/composcoon/back.4bpp.lz"

gMonShinyPalette_Composcoon::
	.incbin "graphics/pokemon/composcoon/shiny.gbapal.lz"

gMonIcon_Composcoon::
	.incbin "graphics/pokemon/composcoon/icon.4bpp"

gMonFootprint_Composcoon::
	.incbin "graphics/pokemon/composcoon/footprint.1bpp"

gMonFrontPic_Flynfly::
	.incbin "graphics/pokemon/flynfly/front.4bpp.lz"

gMonPalette_Flynfly::
	.incbin "graphics/pokemon/flynfly/normal.gbapal.lz"

gMonBackPic_Flynfly::
	.incbin "graphics/pokemon/flynfly/back.4bpp.lz"

gMonShinyPalette_Flynfly::
	.incbin "graphics/pokemon/flynfly/shiny.gbapal.lz"

gMonIcon_Flynfly::
	.incbin "graphics/pokemon/flynfly/icon.4bpp"

gMonFootprint_Flynfly::
	.incbin "graphics/pokemon/flynfly/footprint.1bpp"

gMonFrontPic_Weedo::
	.incbin "graphics/pokemon/weedo/front.4bpp.lz"

gMonPalette_Weedo::
	.incbin "graphics/pokemon/weedo/normal.gbapal.lz"

gMonBackPic_Weedo::
	.incbin "graphics/pokemon/weedo/back.4bpp.lz"

gMonShinyPalette_Weedo::
	.incbin "graphics/pokemon/weedo/shiny.gbapal.lz"

gMonIcon_Weedo::
	.incbin "graphics/pokemon/weedo/icon.4bpp"

gMonFootprint_Weedo::
	.incbin "graphics/pokemon/weedo/footprint.1bpp"

gMonFrontPic_Flosea::
	.incbin "graphics/pokemon/flosea/front.4bpp.lz"

gMonPalette_Flosea::
	.incbin "graphics/pokemon/flosea/normal.gbapal.lz"

gMonBackPic_Flosea::
	.incbin "graphics/pokemon/flosea/back.4bpp.lz"

gMonShinyPalette_Flosea::
	.incbin "graphics/pokemon/flosea/shiny.gbapal.lz"

gMonIcon_Flosea::
	.incbin "graphics/pokemon/flosea/icon.4bpp"

gMonFootprint_Flosea::
	.incbin "graphics/pokemon/flosea/footprint.1bpp"

gMonFrontPic_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/front.4bpp.lz"

gMonPalette_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/normal.gbapal.lz"

gMonBackPic_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/back.4bpp.lz"

gMonShinyPalette_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/shiny.gbapal.lz"

gMonIcon_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/icon.4bpp"

gMonFootprint_Weedalgu::
	.incbin "graphics/pokemon/weedalgu/footprint.1bpp"

gMonFrontPic_Cactino::
	.incbin "graphics/pokemon/cactino/front.4bpp.lz"

gMonPalette_Cactino::
	.incbin "graphics/pokemon/cactino/normal.gbapal.lz"

gMonBackPic_Cactino::
	.incbin "graphics/pokemon/cactino/back.4bpp.lz"

gMonShinyPalette_Cactino::
	.incbin "graphics/pokemon/cactino/shiny.gbapal.lz"

gMonIcon_Cactino::
	.incbin "graphics/pokemon/cactino/icon.4bpp"

gMonFootprint_Cactino::
	.incbin "graphics/pokemon/cactino/footprint.1bpp"

gMonFrontPic_Cacutu::
	.incbin "graphics/pokemon/cacutu/front.4bpp.lz"

gMonPalette_Cacutu::
	.incbin "graphics/pokemon/cacutu/normal.gbapal.lz"

gMonBackPic_Cacutu::
	.incbin "graphics/pokemon/cacutu/back.4bpp.lz"

gMonShinyPalette_Cacutu::
	.incbin "graphics/pokemon/cacutu/shiny.gbapal.lz"

gMonIcon_Cacutu::
	.incbin "graphics/pokemon/cacutu/icon.4bpp"

gMonFootprint_Cacutu::
	.incbin "graphics/pokemon/cacutu/footprint.1bpp"

gMonFrontPic_Dessertea::
	.incbin "graphics/pokemon/dessertea/front.4bpp.lz"

gMonPalette_Dessertea::
	.incbin "graphics/pokemon/dessertea/normal.gbapal.lz"

gMonBackPic_Dessertea::
	.incbin "graphics/pokemon/dessertea/back.4bpp.lz"

gMonShinyPalette_Dessertea::
	.incbin "graphics/pokemon/dessertea/shiny.gbapal.lz"

gMonIcon_Dessertea::
	.incbin "graphics/pokemon/dessertea/icon.4bpp"

gMonFootprint_Dessertea::
	.incbin "graphics/pokemon/dessertea/footprint.1bpp"

gMonFrontPic_Gustano::
	.incbin "graphics/pokemon/gustano/front.4bpp.lz"

gMonPalette_Gustano::
	.incbin "graphics/pokemon/gustano/normal.gbapal.lz"

gMonBackPic_Gustano::
	.incbin "graphics/pokemon/gustano/back.4bpp.lz"

gMonShinyPalette_Gustano::
	.incbin "graphics/pokemon/gustano/shiny.gbapal.lz"

gMonIcon_Gustano::
	.incbin "graphics/pokemon/gustano/icon.4bpp"

gMonFootprint_Gustano::
	.incbin "graphics/pokemon/gustano/footprint.1bpp"

gMonFrontPic_Duostano::
	.incbin "graphics/pokemon/duostano/front.4bpp.lz"

gMonPalette_Duostano::
	.incbin "graphics/pokemon/duostano/normal.gbapal.lz"

gMonBackPic_Duostano::
	.incbin "graphics/pokemon/duostano/back.4bpp.lz"

gMonShinyPalette_Duostano::
	.incbin "graphics/pokemon/duostano/shiny.gbapal.lz"

gMonIcon_Duostano::
	.incbin "graphics/pokemon/duostano/icon.4bpp"

gMonFootprint_Duostano::
	.incbin "graphics/pokemon/duostano/footprint.1bpp"

gMonFrontPic_Phico::
	.incbin "graphics/pokemon/phico/front.4bpp.lz"

gMonPalette_Phico::
	.incbin "graphics/pokemon/phico/normal.gbapal.lz"

gMonBackPic_Phico::
	.incbin "graphics/pokemon/phico/back.4bpp.lz"

gMonShinyPalette_Phico::
	.incbin "graphics/pokemon/phico/shiny.gbapal.lz"

gMonIcon_Phico::
	.incbin "graphics/pokemon/phico/icon.4bpp"

gMonFootprint_Phico::
	.incbin "graphics/pokemon/phico/footprint.1bpp"

gMonFrontPic_Reabari::
	.incbin "graphics/pokemon/reabari/front.4bpp.lz"

gMonPalette_Reabari::
	.incbin "graphics/pokemon/reabari/normal.gbapal.lz"

gMonBackPic_Reabari::
	.incbin "graphics/pokemon/reabari/back.4bpp.lz"

gMonShinyPalette_Reabari::
	.incbin "graphics/pokemon/reabari/shiny.gbapal.lz"

gMonIcon_Reabari::
	.incbin "graphics/pokemon/reabari/icon.4bpp"

gMonFootprint_Reabari::
	.incbin "graphics/pokemon/reabari/footprint.1bpp"

gMonFrontPic_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/front.4bpp.lz"

gMonPalette_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/normal.gbapal.lz"

gMonBackPic_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/back.4bpp.lz"

gMonShinyPalette_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/shiny.gbapal.lz"

gMonIcon_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/icon.4bpp"

gMonFootprint_Ruycantor::
	.incbin "graphics/pokemon/ruycantor/footprint.1bpp"

gMonFrontPic_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/front.4bpp.lz"

gMonPalette_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/normal.gbapal.lz"

gMonBackPic_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/back.4bpp.lz"

gMonShinyPalette_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/shiny.gbapal.lz"

gMonIcon_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/icon.4bpp"

gMonFootprint_Strawbaya::
	.incbin "graphics/pokemon/strawbaya/footprint.1bpp"

gMonFrontPic_Dendrock::
	.incbin "graphics/pokemon/dendrock/front.4bpp.lz"

gMonPalette_Dendrock::
	.incbin "graphics/pokemon/dendrock/normal.gbapal.lz"

gMonBackPic_Dendrock::
	.incbin "graphics/pokemon/dendrock/back.4bpp.lz"

gMonShinyPalette_Dendrock::
	.incbin "graphics/pokemon/dendrock/shiny.gbapal.lz"

gMonIcon_Dendrock::
	.incbin "graphics/pokemon/dendrock/icon.4bpp"

gMonFootprint_Dendrock::
	.incbin "graphics/pokemon/dendrock/footprint.1bpp"

gMonFrontPic_Bounny::
	.incbin "graphics/pokemon/bounny/front.4bpp.lz"

gMonPalette_Bounny::
	.incbin "graphics/pokemon/bounny/normal.gbapal.lz"

gMonBackPic_Bounny::
	.incbin "graphics/pokemon/bounny/back.4bpp.lz"

gMonShinyPalette_Bounny::
	.incbin "graphics/pokemon/bounny/shiny.gbapal.lz"

gMonIcon_Bounny::
	.incbin "graphics/pokemon/bounny/icon.4bpp"

gMonFootprint_Bounny::
	.incbin "graphics/pokemon/bounny/footprint.1bpp"

gMonFrontPic_Bolichano::
	.incbin "graphics/pokemon/bolichano/front.4bpp.lz"

gMonPalette_Bolichano::
	.incbin "graphics/pokemon/bolichano/normal.gbapal.lz"

gMonBackPic_Bolichano::
	.incbin "graphics/pokemon/bolichano/back.4bpp.lz"

gMonShinyPalette_Bolichano::
	.incbin "graphics/pokemon/bolichano/shiny.gbapal.lz"

gMonIcon_Bolichano::
	.incbin "graphics/pokemon/bolichano/icon.4bpp"

gMonFootprint_Bolichano::
	.incbin "graphics/pokemon/bolichano/footprint.1bpp"

gMonFrontPic_Pelichen::
	.incbin "graphics/pokemon/pelichen/front.4bpp.lz"

gMonPalette_Pelichen::
	.incbin "graphics/pokemon/pelichen/normal.gbapal.lz"

gMonBackPic_Pelichen::
	.incbin "graphics/pokemon/pelichen/back.4bpp.lz"

gMonShinyPalette_Pelichen::
	.incbin "graphics/pokemon/pelichen/shiny.gbapal.lz"

gMonIcon_Pelichen::
	.incbin "graphics/pokemon/pelichen/icon.4bpp"

gMonFootprint_Pelichen::
	.incbin "graphics/pokemon/pelichen/footprint.1bpp"

gMonFrontPic_Hovebug::
	.incbin "graphics/pokemon/hovebug/front.4bpp.lz"

gMonPalette_Hovebug::
	.incbin "graphics/pokemon/hovebug/normal.gbapal.lz"

gMonBackPic_Hovebug::
	.incbin "graphics/pokemon/hovebug/back.4bpp.lz"

gMonShinyPalette_Hovebug::
	.incbin "graphics/pokemon/hovebug/shiny.gbapal.lz"

gMonIcon_Hovebug::
	.incbin "graphics/pokemon/hovebug/icon.4bpp"

gMonFootprint_Hovebug::
	.incbin "graphics/pokemon/hovebug/footprint.1bpp"

gMonFrontPic_Planebug::
	.incbin "graphics/pokemon/planebug/front.4bpp.lz"

gMonPalette_Planebug::
	.incbin "graphics/pokemon/planebug/normal.gbapal.lz"

gMonBackPic_Planebug::
	.incbin "graphics/pokemon/planebug/back.4bpp.lz"

gMonShinyPalette_Planebug::
	.incbin "graphics/pokemon/planebug/shiny.gbapal.lz"

gMonIcon_Planebug::
	.incbin "graphics/pokemon/planebug/icon.4bpp"

gMonFootprint_Planebug::
	.incbin "graphics/pokemon/planebug/footprint.1bpp"

gMonFrontPic_Colossio::
	.incbin "graphics/pokemon/colossio/front.4bpp.lz"

gMonPalette_Colossio::
	.incbin "graphics/pokemon/colossio/normal.gbapal.lz"

gMonBackPic_Colossio::
	.incbin "graphics/pokemon/colossio/back.4bpp.lz"

gMonShinyPalette_Colossio::
	.incbin "graphics/pokemon/colossio/shiny.gbapal.lz"

gMonIcon_Colossio::
	.incbin "graphics/pokemon/colossio/icon.4bpp"

gMonFootprint_Colossio::
	.incbin "graphics/pokemon/colossio/footprint.1bpp"

gMonFrontPic_Descomune::
	.incbin "graphics/pokemon/descomune/front.4bpp.lz"

gMonPalette_Descomune::
	.incbin "graphics/pokemon/descomune/normal.gbapal.lz"

gMonBackPic_Descomune::
	.incbin "graphics/pokemon/descomune/back.4bpp.lz"

gMonShinyPalette_Descomune::
	.incbin "graphics/pokemon/descomune/shiny.gbapal.lz"

gMonIcon_Descomune::
	.incbin "graphics/pokemon/descomune/icon.4bpp"

gMonFootprint_Descomune::
	.incbin "graphics/pokemon/descomune/footprint.1bpp"

gMonFrontPic_Babos::
	.incbin "graphics/pokemon/babos/front.4bpp.lz"

gMonPalette_Babos::
	.incbin "graphics/pokemon/babos/normal.gbapal.lz"

gMonBackPic_Babos::
	.incbin "graphics/pokemon/babos/back.4bpp.lz"

gMonShinyPalette_Babos::
	.incbin "graphics/pokemon/babos/shiny.gbapal.lz"

gMonIcon_Babos::
	.incbin "graphics/pokemon/babos/icon.4bpp"

gMonFootprint_Babos::
	.incbin "graphics/pokemon/babos/footprint.1bpp"

gMonFrontPic_Osoe::
	.incbin "graphics/pokemon/osoe/front.4bpp.lz"

gMonPalette_Osoe::
	.incbin "graphics/pokemon/osoe/normal.gbapal.lz"

gMonBackPic_Osoe::
	.incbin "graphics/pokemon/osoe/back.4bpp.lz"

gMonShinyPalette_Osoe::
	.incbin "graphics/pokemon/osoe/shiny.gbapal.lz"

gMonIcon_Osoe::
	.incbin "graphics/pokemon/osoe/icon.4bpp"

gMonFootprint_Osoe::
	.incbin "graphics/pokemon/osoe/footprint.1bpp"

gMonFrontPic_Mimikat::
	.incbin "graphics/pokemon/mimikat/front.4bpp.lz"

gMonPalette_Mimikat::
	.incbin "graphics/pokemon/mimikat/normal.gbapal.lz"

gMonBackPic_Mimikat::
	.incbin "graphics/pokemon/mimikat/back.4bpp.lz"

gMonShinyPalette_Mimikat::
	.incbin "graphics/pokemon/mimikat/shiny.gbapal.lz"

gMonIcon_Mimikat::
	.incbin "graphics/pokemon/mimikat/icon.4bpp"

gMonFootprint_Mimikat::
	.incbin "graphics/pokemon/mimikat/footprint.1bpp"

gMonFrontPic_Goduck::
	.incbin "graphics/pokemon/goduck/front.4bpp.lz"

gMonPalette_Goduck::
	.incbin "graphics/pokemon/goduck/normal.gbapal.lz"

gMonBackPic_Goduck::
	.incbin "graphics/pokemon/goduck/back.4bpp.lz"

gMonShinyPalette_Goduck::
	.incbin "graphics/pokemon/goduck/shiny.gbapal.lz"

gMonIcon_Goduck::
	.incbin "graphics/pokemon/goduck/icon.4bpp"

gMonFootprint_Goduck::
	.incbin "graphics/pokemon/goduck/footprint.1bpp"

gMonFrontPic_Dukamid::
	.incbin "graphics/pokemon/dukamid/front.4bpp.lz"

gMonPalette_Dukamid::
	.incbin "graphics/pokemon/dukamid/normal.gbapal.lz"

gMonBackPic_Dukamid::
	.incbin "graphics/pokemon/dukamid/back.4bpp.lz"

gMonShinyPalette_Dukamid::
	.incbin "graphics/pokemon/dukamid/shiny.gbapal.lz"

gMonIcon_Dukamid::
	.incbin "graphics/pokemon/dukamid/icon.4bpp"

gMonFootprint_Dukamid::
	.incbin "graphics/pokemon/dukamid/footprint.1bpp"

gMonFrontPic_Deprip::
	.incbin "graphics/pokemon/deprip/front.4bpp.lz"

gMonPalette_Deprip::
	.incbin "graphics/pokemon/deprip/normal.gbapal.lz"

gMonBackPic_Deprip::
	.incbin "graphics/pokemon/deprip/back.4bpp.lz"

gMonShinyPalette_Deprip::
	.incbin "graphics/pokemon/deprip/shiny.gbapal.lz"

gMonIcon_Deprip::
	.incbin "graphics/pokemon/deprip/icon.4bpp"

gMonFootprint_Deprip::
	.incbin "graphics/pokemon/deprip/footprint.1bpp"

gMonFrontPic_Coalchar::
	.incbin "graphics/pokemon/coalchar/front.4bpp.lz"

gMonPalette_Coalchar::
	.incbin "graphics/pokemon/coalchar/normal.gbapal.lz"

gMonBackPic_Coalchar::
	.incbin "graphics/pokemon/coalchar/back.4bpp.lz"

gMonShinyPalette_Coalchar::
	.incbin "graphics/pokemon/coalchar/shiny.gbapal.lz"

gMonIcon_Coalchar::
	.incbin "graphics/pokemon/coalchar/icon.4bpp"

gMonFootprint_Coalchar::
	.incbin "graphics/pokemon/coalchar/footprint.1bpp"

gMonFrontPic_Fatube::
	.incbin "graphics/pokemon/fatube/front.4bpp.lz"

gMonPalette_Fatube::
	.incbin "graphics/pokemon/fatube/normal.gbapal.lz"

gMonBackPic_Fatube::
	.incbin "graphics/pokemon/fatube/back.4bpp.lz"

gMonShinyPalette_Fatube::
	.incbin "graphics/pokemon/fatube/shiny.gbapal.lz"

gMonIcon_Fatube::
	.incbin "graphics/pokemon/fatube/icon.4bpp"

gMonFootprint_Fatube::
	.incbin "graphics/pokemon/fatube/footprint.1bpp"

gMonFrontPic_Soie::
	.incbin "graphics/pokemon/soie/front.4bpp.lz"

gMonPalette_Soie::
	.incbin "graphics/pokemon/soie/normal.gbapal.lz"

gMonBackPic_Soie::
	.incbin "graphics/pokemon/soie/back.4bpp.lz"

gMonShinyPalette_Soie::
	.incbin "graphics/pokemon/soie/shiny.gbapal.lz"

gMonIcon_Soie::
	.incbin "graphics/pokemon/soie/icon.4bpp"

gMonFootprint_Soie::
	.incbin "graphics/pokemon/soie/footprint.1bpp"

gMonFrontPic_Corongori::
	.incbin "graphics/pokemon/corongori/front.4bpp.lz"

gMonPalette_Corongori::
	.incbin "graphics/pokemon/corongori/normal.gbapal.lz"

gMonBackPic_Corongori::
	.incbin "graphics/pokemon/corongori/back.4bpp.lz"

gMonShinyPalette_Corongori::
	.incbin "graphics/pokemon/corongori/shiny.gbapal.lz"

gMonIcon_Corongori::
	.incbin "graphics/pokemon/corongori/icon.4bpp"

gMonFootprint_Corongori::
	.incbin "graphics/pokemon/corongori/footprint.1bpp"

gMonFrontPic_Tincrab::
	.incbin "graphics/pokemon/tincrab/front.4bpp.lz"

gMonPalette_Tincrab::
	.incbin "graphics/pokemon/tincrab/normal.gbapal.lz"

gMonBackPic_Tincrab::
	.incbin "graphics/pokemon/tincrab/back.4bpp.lz"

gMonShinyPalette_Tincrab::
	.incbin "graphics/pokemon/tincrab/shiny.gbapal.lz"

gMonIcon_Tincrab::
	.incbin "graphics/pokemon/tincrab/icon.4bpp"

gMonFootprint_Tincrab::
	.incbin "graphics/pokemon/tincrab/footprint.1bpp"

gMonFrontPic_Searoket::
	.incbin "graphics/pokemon/searoket/front.4bpp.lz"

gMonPalette_Searoket::
	.incbin "graphics/pokemon/searoket/normal.gbapal.lz"

gMonBackPic_Searoket::
	.incbin "graphics/pokemon/searoket/back.4bpp.lz"

gMonShinyPalette_Searoket::
	.incbin "graphics/pokemon/searoket/shiny.gbapal.lz"

gMonIcon_Searoket::
	.incbin "graphics/pokemon/searoket/icon.4bpp"

gMonFootprint_Searoket::
	.incbin "graphics/pokemon/searoket/footprint.1bpp"

gMonFrontPic_Helixet::
	.incbin "graphics/pokemon/helixet/front.4bpp.lz"

gMonPalette_Helixet::
	.incbin "graphics/pokemon/helixet/normal.gbapal.lz"

gMonBackPic_Helixet::
	.incbin "graphics/pokemon/helixet/back.4bpp.lz"

gMonShinyPalette_Helixet::
	.incbin "graphics/pokemon/helixet/shiny.gbapal.lz"

gMonIcon_Helixet::
	.incbin "graphics/pokemon/helixet/icon.4bpp"

gMonFootprint_Helixet::
	.incbin "graphics/pokemon/helixet/footprint.1bpp"

gMonFrontPic_Icish::
	.incbin "graphics/pokemon/icish/front.4bpp.lz"

gMonPalette_Icish::
	.incbin "graphics/pokemon/icish/normal.gbapal.lz"

gMonBackPic_Icish::
	.incbin "graphics/pokemon/icish/back.4bpp.lz"

gMonShinyPalette_Icish::
	.incbin "graphics/pokemon/icish/shiny.gbapal.lz"

gMonIcon_Icish::
	.incbin "graphics/pokemon/icish/icon.4bpp"

gMonFootprint_Icish::
	.incbin "graphics/pokemon/icish/footprint.1bpp"

gMonFrontPic_Freech::
	.incbin "graphics/pokemon/freech/front.4bpp.lz"

gMonPalette_Freech::
	.incbin "graphics/pokemon/freech/normal.gbapal.lz"

gMonBackPic_Freech::
	.incbin "graphics/pokemon/freech/back.4bpp.lz"

gMonShinyPalette_Freech::
	.incbin "graphics/pokemon/freech/shiny.gbapal.lz"

gMonIcon_Freech::
	.incbin "graphics/pokemon/freech/icon.4bpp"

gMonFootprint_Freech::
	.incbin "graphics/pokemon/freech/footprint.1bpp"

gMonFrontPic_Awhol::
	.incbin "graphics/pokemon/awhol/front.4bpp.lz"

gMonPalette_Awhol::
	.incbin "graphics/pokemon/awhol/normal.gbapal.lz"

gMonBackPic_Awhol::
	.incbin "graphics/pokemon/awhol/back.4bpp.lz"

gMonShinyPalette_Awhol::
	.incbin "graphics/pokemon/awhol/shiny.gbapal.lz"

gMonIcon_Awhol::
	.incbin "graphics/pokemon/awhol/icon.4bpp"

gMonFootprint_Awhol::
	.incbin "graphics/pokemon/awhol/footprint.1bpp"

gMonFrontPic_Whola::
	.incbin "graphics/pokemon/whola/front.4bpp.lz"

gMonPalette_Whola::
	.incbin "graphics/pokemon/whola/normal.gbapal.lz"

gMonBackPic_Whola::
	.incbin "graphics/pokemon/whola/back.4bpp.lz"

gMonShinyPalette_Whola::
	.incbin "graphics/pokemon/whola/shiny.gbapal.lz"

gMonIcon_Whola::
	.incbin "graphics/pokemon/whola/icon.4bpp"

gMonFootprint_Whola::
	.incbin "graphics/pokemon/whola/footprint.1bpp"

gMonFrontPic_Progon::
	.incbin "graphics/pokemon/progon/front.4bpp.lz"

gMonPalette_Progon::
	.incbin "graphics/pokemon/progon/normal.gbapal.lz"

gMonBackPic_Progon::
	.incbin "graphics/pokemon/progon/back.4bpp.lz"

gMonShinyPalette_Progon::
	.incbin "graphics/pokemon/progon/shiny.gbapal.lz"

gMonIcon_Progon::
	.incbin "graphics/pokemon/progon/icon.4bpp"

gMonFootprint_Progon::
	.incbin "graphics/pokemon/progon/footprint.1bpp"

gMonFrontPic_Rubygon::
	.incbin "graphics/pokemon/rubygon/front.4bpp.lz"

gMonPalette_Rubygon::
	.incbin "graphics/pokemon/rubygon/normal.gbapal.lz"

gMonBackPic_Rubygon::
	.incbin "graphics/pokemon/rubygon/back.4bpp.lz"

gMonShinyPalette_Rubygon::
	.incbin "graphics/pokemon/rubygon/shiny.gbapal.lz"

gMonIcon_Rubygon::
	.incbin "graphics/pokemon/rubygon/icon.4bpp"

gMonFootprint_Rubygon::
	.incbin "graphics/pokemon/rubygon/footprint.1bpp"

gMonFrontPic_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/front.4bpp.lz"

gMonPalette_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/normal.gbapal.lz"

gMonBackPic_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/back.4bpp.lz"

gMonShinyPalette_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/shiny.gbapal.lz"

gMonIcon_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/icon.4bpp"

gMonFootprint_Saphiregon::
	.incbin "graphics/pokemon/saphiregon/footprint.1bpp"

gMonFrontPic_Energiz::
	.incbin "graphics/pokemon/energiz/front.4bpp.lz"

gMonPalette_Energiz::
	.incbin "graphics/pokemon/energiz/normal.gbapal.lz"

gMonBackPic_Energiz::
	.incbin "graphics/pokemon/energiz/back.4bpp.lz"

gMonShinyPalette_Energiz::
	.incbin "graphics/pokemon/energiz/shiny.gbapal.lz"

gMonIcon_Energiz::
	.incbin "graphics/pokemon/energiz/icon.4bpp"

gMonFootprint_Energiz::
	.incbin "graphics/pokemon/energiz/footprint.1bpp"

gMonFrontPic_Musclelc::
	.incbin "graphics/pokemon/musclelc/front.4bpp.lz"

gMonPalette_Musclelc::
	.incbin "graphics/pokemon/musclelc/normal.gbapal.lz"

gMonBackPic_Musclelc::
	.incbin "graphics/pokemon/musclelc/back.4bpp.lz"

gMonShinyPalette_Musclelc::
	.incbin "graphics/pokemon/musclelc/shiny.gbapal.lz"

gMonIcon_Musclelc::
	.incbin "graphics/pokemon/musclelc/icon.4bpp"

gMonFootprint_Musclelc::
	.incbin "graphics/pokemon/musclelc/footprint.1bpp"

gMonFrontPic_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/front.4bpp.lz"

gMonPalette_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/normal.gbapal.lz"

gMonBackPic_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/back.4bpp.lz"

gMonShinyPalette_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/shiny.gbapal.lz"

gMonIcon_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/icon.4bpp"

gMonFootprint_Plug_Oink::
	.incbin "graphics/pokemon/plug_oink/footprint.1bpp"

gMonFrontPic_Spig::
	.incbin "graphics/pokemon/spig/front.4bpp.lz"

gMonPalette_Spig::
	.incbin "graphics/pokemon/spig/normal.gbapal.lz"

gMonBackPic_Spig::
	.incbin "graphics/pokemon/spig/back.4bpp.lz"

gMonShinyPalette_Spig::
	.incbin "graphics/pokemon/spig/shiny.gbapal.lz"

gMonIcon_Spig::
	.incbin "graphics/pokemon/spig/icon.4bpp"

gMonFootprint_Spig::
	.incbin "graphics/pokemon/spig/footprint.1bpp"

gMonFrontPic_Llamayama::
	.incbin "graphics/pokemon/llamayama/front.4bpp.lz"

gMonPalette_Llamayama::
	.incbin "graphics/pokemon/llamayama/normal.gbapal.lz"

gMonBackPic_Llamayama::
	.incbin "graphics/pokemon/llamayama/back.4bpp.lz"

gMonShinyPalette_Llamayama::
	.incbin "graphics/pokemon/llamayama/shiny.gbapal.lz"

gMonIcon_Llamayama::
	.incbin "graphics/pokemon/llamayama/icon.4bpp"

gMonFootprint_Llamayama::
	.incbin "graphics/pokemon/llamayama/footprint.1bpp"

gMonFrontPic_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/front.4bpp.lz"

gMonPalette_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/normal.gbapal.lz"

gMonBackPic_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/back.4bpp.lz"

gMonShinyPalette_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/shiny.gbapal.lz"

gMonIcon_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/icon.4bpp"

gMonFootprint_Chimneyama::
	.incbin "graphics/pokemon/chimneyama/footprint.1bpp"

gMonFrontPic_Coldchick::
	.incbin "graphics/pokemon/coldchick/front.4bpp.lz"

gMonPalette_Coldchick::
	.incbin "graphics/pokemon/coldchick/normal.gbapal.lz"

gMonBackPic_Coldchick::
	.incbin "graphics/pokemon/coldchick/back.4bpp.lz"

gMonShinyPalette_Coldchick::
	.incbin "graphics/pokemon/coldchick/shiny.gbapal.lz"

gMonIcon_Coldchick::
	.incbin "graphics/pokemon/coldchick/icon.4bpp"

gMonFootprint_Coldchick::
	.incbin "graphics/pokemon/coldchick/footprint.1bpp"

gMonFrontPic_Freezock::
	.incbin "graphics/pokemon/freezock/front.4bpp.lz"

gMonPalette_Freezock::
	.incbin "graphics/pokemon/freezock/normal.gbapal.lz"

gMonBackPic_Freezock::
	.incbin "graphics/pokemon/freezock/back.4bpp.lz"

gMonShinyPalette_Freezock::
	.incbin "graphics/pokemon/freezock/shiny.gbapal.lz"

gMonIcon_Freezock::
	.incbin "graphics/pokemon/freezock/icon.4bpp"

gMonFootprint_Freezock::
	.incbin "graphics/pokemon/freezock/footprint.1bpp"

gMonFrontPic_Cottoster::
	.incbin "graphics/pokemon/cottoster/front.4bpp.lz"

gMonPalette_Cottoster::
	.incbin "graphics/pokemon/cottoster/normal.gbapal.lz"

gMonBackPic_Cottoster::
	.incbin "graphics/pokemon/cottoster/back.4bpp.lz"

gMonShinyPalette_Cottoster::
	.incbin "graphics/pokemon/cottoster/shiny.gbapal.lz"

gMonIcon_Cottoster::
	.incbin "graphics/pokemon/cottoster/icon.4bpp"

gMonFootprint_Cottoster::
	.incbin "graphics/pokemon/cottoster/footprint.1bpp"

gMonFrontPic_Apinep::
	.incbin "graphics/pokemon/apinep/front.4bpp.lz"

gMonPalette_Apinep::
	.incbin "graphics/pokemon/apinep/normal.gbapal.lz"

gMonBackPic_Apinep::
	.incbin "graphics/pokemon/apinep/back.4bpp.lz"

gMonShinyPalette_Apinep::
	.incbin "graphics/pokemon/apinep/shiny.gbapal.lz"

gMonIcon_Apinep::
	.incbin "graphics/pokemon/apinep/icon.4bpp"

gMonFootprint_Apinep::
	.incbin "graphics/pokemon/apinep/footprint.1bpp"

gMonFrontPic_Pinark::
	.incbin "graphics/pokemon/pinark/front.4bpp.lz"

gMonPalette_Pinark::
	.incbin "graphics/pokemon/pinark/normal.gbapal.lz"

gMonBackPic_Pinark::
	.incbin "graphics/pokemon/pinark/back.4bpp.lz"

gMonShinyPalette_Pinark::
	.incbin "graphics/pokemon/pinark/shiny.gbapal.lz"

gMonIcon_Pinark::
	.incbin "graphics/pokemon/pinark/icon.4bpp"

gMonFootprint_Pinark::
	.incbin "graphics/pokemon/pinark/footprint.1bpp"

gMonFrontPic_Spinwing::
	.incbin "graphics/pokemon/spinwing/front.4bpp.lz"

gMonPalette_Spinwing::
	.incbin "graphics/pokemon/spinwing/normal.gbapal.lz"

gMonBackPic_Spinwing::
	.incbin "graphics/pokemon/spinwing/back.4bpp.lz"

gMonShinyPalette_Spinwing::
	.incbin "graphics/pokemon/spinwing/shiny.gbapal.lz"

gMonIcon_Spinwing::
	.incbin "graphics/pokemon/spinwing/icon.4bpp"

gMonFootprint_Spinwing::
	.incbin "graphics/pokemon/spinwing/footprint.1bpp"

gMonFrontPic_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/front.4bpp.lz"

gMonPalette_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/normal.gbapal.lz"

gMonBackPic_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/back.4bpp.lz"

gMonShinyPalette_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/shiny.gbapal.lz"

gMonIcon_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/icon.4bpp"

gMonFootprint_Bobeguin::
	.incbin "graphics/pokemon/bobeguin/footprint.1bpp"

gMonFrontPic_Clostar::
	.incbin "graphics/pokemon/clostar/front.4bpp.lz"

gMonPalette_Clostar::
	.incbin "graphics/pokemon/clostar/normal.gbapal.lz"

gMonBackPic_Clostar::
	.incbin "graphics/pokemon/clostar/back.4bpp.lz"

gMonShinyPalette_Clostar::
	.incbin "graphics/pokemon/clostar/shiny.gbapal.lz"

gMonIcon_Clostar::
	.incbin "graphics/pokemon/clostar/icon.4bpp"

gMonFootprint_Clostar::
	.incbin "graphics/pokemon/clostar/footprint.1bpp"

gMonFrontPic_Stargo::
	.incbin "graphics/pokemon/stargo/front.4bpp.lz"

gMonPalette_Stargo::
	.incbin "graphics/pokemon/stargo/normal.gbapal.lz"

gMonBackPic_Stargo::
	.incbin "graphics/pokemon/stargo/back.4bpp.lz"

gMonShinyPalette_Stargo::
	.incbin "graphics/pokemon/stargo/shiny.gbapal.lz"

gMonIcon_Stargo::
	.incbin "graphics/pokemon/stargo/icon.4bpp"

gMonFootprint_Stargo::
	.incbin "graphics/pokemon/stargo/footprint.1bpp"

gMonFrontPic_Beavy::
	.incbin "graphics/pokemon/beavy/front.4bpp.lz"

gMonPalette_Beavy::
	.incbin "graphics/pokemon/beavy/normal.gbapal.lz"

gMonBackPic_Beavy::
	.incbin "graphics/pokemon/beavy/back.4bpp.lz"

gMonShinyPalette_Beavy::
	.incbin "graphics/pokemon/beavy/shiny.gbapal.lz"

gMonIcon_Beavy::
	.incbin "graphics/pokemon/beavy/icon.4bpp"

gMonFootprint_Beavy::
	.incbin "graphics/pokemon/beavy/footprint.1bpp"

gMonFrontPic_Tigat::
	.incbin "graphics/pokemon/tigat/front.4bpp.lz"

gMonPalette_Tigat::
	.incbin "graphics/pokemon/tigat/normal.gbapal.lz"

gMonBackPic_Tigat::
	.incbin "graphics/pokemon/tigat/back.4bpp.lz"

gMonShinyPalette_Tigat::
	.incbin "graphics/pokemon/tigat/shiny.gbapal.lz"

gMonIcon_Tigat::
	.incbin "graphics/pokemon/tigat/icon.4bpp"

gMonFootprint_Tigat::
	.incbin "graphics/pokemon/tigat/footprint.1bpp"

gMonFrontPic_Tigator::
	.incbin "graphics/pokemon/tigator/front.4bpp.lz"

gMonPalette_Tigator::
	.incbin "graphics/pokemon/tigator/normal.gbapal.lz"

gMonBackPic_Tigator::
	.incbin "graphics/pokemon/tigator/back.4bpp.lz"

gMonShinyPalette_Tigator::
	.incbin "graphics/pokemon/tigator/shiny.gbapal.lz"

gMonIcon_Tigator::
	.incbin "graphics/pokemon/tigator/icon.4bpp"

gMonFootprint_Tigator::
	.incbin "graphics/pokemon/tigator/footprint.1bpp"

gMonFrontPic_Amede::
	.incbin "graphics/pokemon/amede/front.4bpp.lz"

gMonPalette_Amede::
	.incbin "graphics/pokemon/amede/normal.gbapal.lz"

gMonBackPic_Amede::
	.incbin "graphics/pokemon/amede/back.4bpp.lz"

gMonShinyPalette_Amede::
	.incbin "graphics/pokemon/amede/shiny.gbapal.lz"

gMonIcon_Amede::
	.incbin "graphics/pokemon/amede/icon.4bpp"

gMonFootprint_Amede::
	.incbin "graphics/pokemon/amede/footprint.1bpp"

gMonFrontPic_Amedi::
	.incbin "graphics/pokemon/amedi/front.4bpp.lz"

gMonPalette_Amedi::
	.incbin "graphics/pokemon/amedi/normal.gbapal.lz"

gMonBackPic_Amedi::
	.incbin "graphics/pokemon/amedi/back.4bpp.lz"

gMonShinyPalette_Amedi::
	.incbin "graphics/pokemon/amedi/shiny.gbapal.lz"

gMonIcon_Amedi::
	.incbin "graphics/pokemon/amedi/icon.4bpp"

gMonFootprint_Amedi::
	.incbin "graphics/pokemon/amedi/footprint.1bpp"

gMonFrontPic_Hooley::
	.incbin "graphics/pokemon/hooley/front.4bpp.lz"

gMonPalette_Hooley::
	.incbin "graphics/pokemon/hooley/normal.gbapal.lz"

gMonBackPic_Hooley::
	.incbin "graphics/pokemon/hooley/back.4bpp.lz"

gMonShinyPalette_Hooley::
	.incbin "graphics/pokemon/hooley/shiny.gbapal.lz"

gMonIcon_Hooley::
	.incbin "graphics/pokemon/hooley/icon.4bpp"

gMonFootprint_Hooley::
	.incbin "graphics/pokemon/hooley/footprint.1bpp"

gMonFrontPic_Mindum::
	.incbin "graphics/pokemon/mindum/front.4bpp.lz"

gMonPalette_Mindum::
	.incbin "graphics/pokemon/mindum/normal.gbapal.lz"

gMonBackPic_Mindum::
	.incbin "graphics/pokemon/mindum/back.4bpp.lz"

gMonShinyPalette_Mindum::
	.incbin "graphics/pokemon/mindum/shiny.gbapal.lz"

gMonIcon_Mindum::
	.incbin "graphics/pokemon/mindum/icon.4bpp"

gMonFootprint_Mindum::
	.incbin "graphics/pokemon/mindum/footprint.1bpp"

gMonFrontPic_Minadoom::
	.incbin "graphics/pokemon/minadoom/front.4bpp.lz"

gMonPalette_Minadoom::
	.incbin "graphics/pokemon/minadoom/normal.gbapal.lz"

gMonBackPic_Minadoom::
	.incbin "graphics/pokemon/minadoom/back.4bpp.lz"

gMonShinyPalette_Minadoom::
	.incbin "graphics/pokemon/minadoom/shiny.gbapal.lz"

gMonIcon_Minadoom::
	.incbin "graphics/pokemon/minadoom/icon.4bpp"

gMonFootprint_Minadoom::
	.incbin "graphics/pokemon/minadoom/footprint.1bpp"

gMonFrontPic_Jackan::
	.incbin "graphics/pokemon/jackan/front.4bpp.lz"

gMonPalette_Jackan::
	.incbin "graphics/pokemon/jackan/normal.gbapal.lz"

gMonBackPic_Jackan::
	.incbin "graphics/pokemon/jackan/back.4bpp.lz"

gMonShinyPalette_Jackan::
	.incbin "graphics/pokemon/jackan/shiny.gbapal.lz"

gMonIcon_Jackan::
	.incbin "graphics/pokemon/jackan/icon.4bpp"

gMonFootprint_Jackan::
	.incbin "graphics/pokemon/jackan/footprint.1bpp"

gMonFrontPic_Lotbird::
	.incbin "graphics/pokemon/lotbird/front.4bpp.lz"

gMonPalette_Lotbird::
	.incbin "graphics/pokemon/lotbird/normal.gbapal.lz"

gMonBackPic_Lotbird::
	.incbin "graphics/pokemon/lotbird/back.4bpp.lz"

gMonShinyPalette_Lotbird::
	.incbin "graphics/pokemon/lotbird/shiny.gbapal.lz"

gMonIcon_Lotbird::
	.incbin "graphics/pokemon/lotbird/icon.4bpp"

gMonFootprint_Lotbird::
	.incbin "graphics/pokemon/lotbird/footprint.1bpp"

gMonFrontPic_Boguon::
	.incbin "graphics/pokemon/boguon/front.4bpp.lz"

gMonPalette_Boguon::
	.incbin "graphics/pokemon/boguon/normal.gbapal.lz"

gMonBackPic_Boguon::
	.incbin "graphics/pokemon/boguon/back.4bpp.lz"

gMonShinyPalette_Boguon::
	.incbin "graphics/pokemon/boguon/shiny.gbapal.lz"

gMonIcon_Boguon::
	.incbin "graphics/pokemon/boguon/icon.4bpp"

gMonFootprint_Boguon::
	.incbin "graphics/pokemon/boguon/footprint.1bpp"

gMonFrontPic_Guinette::
	.incbin "graphics/pokemon/guiñette/front.4bpp.lz"

gMonPalette_Guinette::
	.incbin "graphics/pokemon/guiñette/normal.gbapal.lz"

gMonBackPic_Guinette::
	.incbin "graphics/pokemon/guiñette/back.4bpp.lz"

gMonShinyPalette_Guinette::
	.incbin "graphics/pokemon/guiñette/shiny.gbapal.lz"

gMonIcon_Guinette::
	.incbin "graphics/pokemon/guiñette/icon.4bpp"

gMonFootprint_Guinette::
	.incbin "graphics/pokemon/guiñette/footprint.1bpp"

gMonFrontPic_Woopet::
	.incbin "graphics/pokemon/woopet/front.4bpp.lz"

gMonPalette_Woopet::
	.incbin "graphics/pokemon/woopet/normal.gbapal.lz"

gMonBackPic_Woopet::
	.incbin "graphics/pokemon/woopet/back.4bpp.lz"

gMonShinyPalette_Woopet::
	.incbin "graphics/pokemon/woopet/shiny.gbapal.lz"

gMonIcon_Woopet::
	.incbin "graphics/pokemon/woopet/icon.4bpp"

gMonFootprint_Woopet::
	.incbin "graphics/pokemon/woopet/footprint.1bpp"

gMonFrontPic_Fairoot::
	.incbin "graphics/pokemon/fairoot/front.4bpp.lz"

gMonPalette_Fairoot::
	.incbin "graphics/pokemon/fairoot/normal.gbapal.lz"

gMonBackPic_Fairoot::
	.incbin "graphics/pokemon/fairoot/back.4bpp.lz"

gMonShinyPalette_Fairoot::
	.incbin "graphics/pokemon/fairoot/shiny.gbapal.lz"

gMonIcon_Fairoot::
	.incbin "graphics/pokemon/fairoot/icon.4bpp"

gMonFootprint_Fairoot::
	.incbin "graphics/pokemon/fairoot/footprint.1bpp"

gMonFrontPic_Ronslept::
	.incbin "graphics/pokemon/ronslept/front.4bpp.lz"

gMonPalette_Ronslept::
	.incbin "graphics/pokemon/ronslept/normal.gbapal.lz"

gMonBackPic_Ronslept::
	.incbin "graphics/pokemon/ronslept/back.4bpp.lz"

gMonShinyPalette_Ronslept::
	.incbin "graphics/pokemon/ronslept/shiny.gbapal.lz"

gMonIcon_Ronslept::
	.incbin "graphics/pokemon/ronslept/icon.4bpp"

gMonFootprint_Ronslept::
	.incbin "graphics/pokemon/ronslept/footprint.1bpp"

gMonFrontPic_Leirao::
	.incbin "graphics/pokemon/leirao/front.4bpp.lz"

gMonPalette_Leirao::
	.incbin "graphics/pokemon/leirao/normal.gbapal.lz"

gMonBackPic_Leirao::
	.incbin "graphics/pokemon/leirao/back.4bpp.lz"

gMonShinyPalette_Leirao::
	.incbin "graphics/pokemon/leirao/shiny.gbapal.lz"

gMonIcon_Leirao::
	.incbin "graphics/pokemon/leirao/icon.4bpp"

gMonFootprint_Leirao::
	.incbin "graphics/pokemon/leirao/footprint.1bpp"

gMonFrontPic_Dorliron::
	.incbin "graphics/pokemon/dorlirón/front.4bpp.lz"

gMonPalette_Dorliron::
	.incbin "graphics/pokemon/dorlirón/normal.gbapal.lz"

gMonBackPic_Dorliron::
	.incbin "graphics/pokemon/dorlirón/back.4bpp.lz"

gMonShinyPalette_Dorliron::
	.incbin "graphics/pokemon/dorlirón/shiny.gbapal.lz"

gMonIcon_Dorliron::
	.incbin "graphics/pokemon/dorlirón/icon.4bpp"

gMonFootprint_Dorliron::
	.incbin "graphics/pokemon/dorlirón/footprint.1bpp"

gMonFrontPic_Simpleon::
	.incbin "graphics/pokemon/simpleon/front.4bpp.lz"

gMonPalette_Simpleon::
	.incbin "graphics/pokemon/simpleon/normal.gbapal.lz"

gMonBackPic_Simpleon::
	.incbin "graphics/pokemon/simpleon/back.4bpp.lz"

gMonShinyPalette_Simpleon::
	.incbin "graphics/pokemon/simpleon/shiny.gbapal.lz"

gMonIcon_Simpleon::
	.incbin "graphics/pokemon/simpleon/icon.4bpp"

gMonFootprint_Simpleon::
	.incbin "graphics/pokemon/simpleon/footprint.1bpp"

gMonFrontPic_Dobleon::
	.incbin "graphics/pokemon/dobleon/front.4bpp.lz"

gMonPalette_Dobleon::
	.incbin "graphics/pokemon/dobleon/normal.gbapal.lz"

gMonBackPic_Dobleon::
	.incbin "graphics/pokemon/dobleon/back.4bpp.lz"

gMonShinyPalette_Dobleon::
	.incbin "graphics/pokemon/dobleon/shiny.gbapal.lz"

gMonIcon_Dobleon::
	.incbin "graphics/pokemon/dobleon/icon.4bpp"

gMonFootprint_Dobleon::
	.incbin "graphics/pokemon/dobleon/footprint.1bpp"

gMonFrontPic_Liofang::
	.incbin "graphics/pokemon/liofang/front.4bpp.lz"

gMonPalette_Liofang::
	.incbin "graphics/pokemon/liofang/normal.gbapal.lz"

gMonBackPic_Liofang::
	.incbin "graphics/pokemon/liofang/back.4bpp.lz"

gMonShinyPalette_Liofang::
	.incbin "graphics/pokemon/liofang/shiny.gbapal.lz"

gMonIcon_Liofang::
	.incbin "graphics/pokemon/liofang/icon.4bpp"

gMonFootprint_Liofang::
	.incbin "graphics/pokemon/liofang/footprint.1bpp"

gMonFrontPic_Tynigon::
	.incbin "graphics/pokemon/tynigon/front.4bpp.lz"

gMonPalette_Tynigon::
	.incbin "graphics/pokemon/tynigon/normal.gbapal.lz"

gMonBackPic_Tynigon::
	.incbin "graphics/pokemon/tynigon/back.4bpp.lz"

gMonShinyPalette_Tynigon::
	.incbin "graphics/pokemon/tynigon/shiny.gbapal.lz"

gMonIcon_Tynigon::
	.incbin "graphics/pokemon/tynigon/icon.4bpp"

gMonFootprint_Tynigon::
	.incbin "graphics/pokemon/tynigon/footprint.1bpp"

gMonFrontPic_Balagon::
	.incbin "graphics/pokemon/balagon/front.4bpp.lz"

gMonPalette_Balagon::
	.incbin "graphics/pokemon/balagon/normal.gbapal.lz"

gMonBackPic_Balagon::
	.incbin "graphics/pokemon/balagon/back.4bpp.lz"

gMonShinyPalette_Balagon::
	.incbin "graphics/pokemon/balagon/shiny.gbapal.lz"

gMonIcon_Balagon::
	.incbin "graphics/pokemon/balagon/icon.4bpp"

gMonFootprint_Balagon::
	.incbin "graphics/pokemon/balagon/footprint.1bpp"

gMonFrontPic_Iguagon::
	.incbin "graphics/pokemon/iguagon/front.4bpp.lz"

gMonPalette_Iguagon::
	.incbin "graphics/pokemon/iguagon/normal.gbapal.lz"

gMonBackPic_Iguagon::
	.incbin "graphics/pokemon/iguagon/back.4bpp.lz"

gMonShinyPalette_Iguagon::
	.incbin "graphics/pokemon/iguagon/shiny.gbapal.lz"

gMonIcon_Iguagon::
	.incbin "graphics/pokemon/iguagon/icon.4bpp"

gMonFootprint_Iguagon::
	.incbin "graphics/pokemon/iguagon/footprint.1bpp"

gMonFrontPic_Berchi::
	.incbin "graphics/pokemon/berchi/front.4bpp.lz"

gMonPalette_Berchi::
	.incbin "graphics/pokemon/berchi/normal.gbapal.lz"

gMonBackPic_Berchi::
	.incbin "graphics/pokemon/berchi/back.4bpp.lz"

gMonShinyPalette_Berchi::
	.incbin "graphics/pokemon/berchi/shiny.gbapal.lz"

gMonIcon_Berchi::
	.incbin "graphics/pokemon/berchi/icon.4bpp"

gMonFootprint_Berchi::
	.incbin "graphics/pokemon/berchi/footprint.1bpp"

gMonFrontPic_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/front.4bpp.lz"

gMonPalette_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/normal.gbapal.lz"

gMonBackPic_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/back.4bpp.lz"

gMonShinyPalette_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/shiny.gbapal.lz"

gMonIcon_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/icon.4bpp"

gMonFootprint_Mejiyonson::
	.incbin "graphics/pokemon/mejiyonson/footprint.1bpp"

gMonFrontPic_Loapa::
	.incbin "graphics/pokemon/loapa/front.4bpp.lz"

gMonPalette_Loapa::
	.incbin "graphics/pokemon/loapa/normal.gbapal.lz"

gMonBackPic_Loapa::
	.incbin "graphics/pokemon/loapa/back.4bpp.lz"

gMonShinyPalette_Loapa::
	.incbin "graphics/pokemon/loapa/shiny.gbapal.lz"

gMonIcon_Loapa::
	.incbin "graphics/pokemon/loapa/icon.4bpp"

gMonFootprint_Loapa::
	.incbin "graphics/pokemon/loapa/footprint.1bpp"

gMonFrontPic_Agoir::
	.incbin "graphics/pokemon/agoir/front.4bpp.lz"

gMonPalette_Agoir::
	.incbin "graphics/pokemon/agoir/normal.gbapal.lz"

gMonBackPic_Agoir::
	.incbin "graphics/pokemon/agoir/back.4bpp.lz"

gMonShinyPalette_Agoir::
	.incbin "graphics/pokemon/agoir/shiny.gbapal.lz"

gMonIcon_Agoir::
	.incbin "graphics/pokemon/agoir/icon.4bpp"

gMonFootprint_Agoir::
	.incbin "graphics/pokemon/agoir/footprint.1bpp"

gMonFrontPic_Catalon::
	.incbin "graphics/pokemon/catalon/front.4bpp.lz"

gMonPalette_Catalon::
	.incbin "graphics/pokemon/catalon/normal.gbapal.lz"

gMonBackPic_Catalon::
	.incbin "graphics/pokemon/catalon/back.4bpp.lz"

gMonShinyPalette_Catalon::
	.incbin "graphics/pokemon/catalon/shiny.gbapal.lz"

gMonIcon_Catalon::
	.incbin "graphics/pokemon/catalon/icon.4bpp"

gMonFootprint_Catalon::
	.incbin "graphics/pokemon/catalon/footprint.1bpp"

gMonFrontPic_Mazalon::
	.incbin "graphics/pokemon/mazalon/front.4bpp.lz"

gMonPalette_Mazalon::
	.incbin "graphics/pokemon/mazalon/normal.gbapal.lz"

gMonBackPic_Mazalon::
	.incbin "graphics/pokemon/mazalon/back.4bpp.lz"

gMonShinyPalette_Mazalon::
	.incbin "graphics/pokemon/mazalon/shiny.gbapal.lz"

gMonIcon_Mazalon::
	.incbin "graphics/pokemon/mazalon/icon.4bpp"

gMonFootprint_Mazalon::
	.incbin "graphics/pokemon/mazalon/footprint.1bpp"

gMonFrontPic_Onike::
	.incbin "graphics/pokemon/onike/front.4bpp.lz"

gMonPalette_Onike::
	.incbin "graphics/pokemon/onike/normal.gbapal.lz"

gMonBackPic_Onike::
	.incbin "graphics/pokemon/onike/back.4bpp.lz"

gMonShinyPalette_Onike::
	.incbin "graphics/pokemon/onike/shiny.gbapal.lz"

gMonIcon_Onike::
	.incbin "graphics/pokemon/onike/icon.4bpp"

gMonFootprint_Onike::
	.incbin "graphics/pokemon/onike/footprint.1bpp"

gMonFrontPic_Copycatte::
	.incbin "graphics/pokemon/copycatte/front.4bpp.lz"

gMonPalette_Copycatte::
	.incbin "graphics/pokemon/copycatte/normal.gbapal.lz"

gMonBackPic_Copycatte::
	.incbin "graphics/pokemon/copycatte/back.4bpp.lz"

gMonShinyPalette_Copycatte::
	.incbin "graphics/pokemon/copycatte/shiny.gbapal.lz"

gMonIcon_Copycatte::
	.incbin "graphics/pokemon/copycatte/icon.4bpp"

gMonFootprint_Copycatte::
	.incbin "graphics/pokemon/copycatte/footprint.1bpp"

gMonFrontPic_Monkoor::
	.incbin "graphics/pokemon/monkoor/front.4bpp.lz"

gMonPalette_Monkoor::
	.incbin "graphics/pokemon/monkoor/normal.gbapal.lz"

gMonBackPic_Monkoor::
	.incbin "graphics/pokemon/monkoor/back.4bpp.lz"

gMonShinyPalette_Monkoor::
	.incbin "graphics/pokemon/monkoor/shiny.gbapal.lz"

gMonIcon_Monkoor::
	.incbin "graphics/pokemon/monkoor/icon.4bpp"

gMonFootprint_Monkoor::
	.incbin "graphics/pokemon/monkoor/footprint.1bpp"

gMonFrontPic_Opail::
	.incbin "graphics/pokemon/opail/front.4bpp.lz"

gMonPalette_Opail::
	.incbin "graphics/pokemon/opail/normal.gbapal.lz"

gMonBackPic_Opail::
	.incbin "graphics/pokemon/opail/back.4bpp.lz"

gMonShinyPalette_Opail::
	.incbin "graphics/pokemon/opail/shiny.gbapal.lz"

gMonIcon_Opail::
	.incbin "graphics/pokemon/opail/icon.4bpp"

gMonFootprint_Opail::
	.incbin "graphics/pokemon/opail/footprint.1bpp"

gMonFrontPic_Hompalon::
	.incbin "graphics/pokemon/hompalon/front.4bpp.lz"

gMonPalette_Hompalon::
	.incbin "graphics/pokemon/hompalon/normal.gbapal.lz"

gMonBackPic_Hompalon::
	.incbin "graphics/pokemon/hompalon/back.4bpp.lz"

gMonShinyPalette_Hompalon::
	.incbin "graphics/pokemon/hompalon/shiny.gbapal.lz"

gMonIcon_Hompalon::
	.incbin "graphics/pokemon/hompalon/icon.4bpp"

gMonFootprint_Hompalon::
	.incbin "graphics/pokemon/hompalon/footprint.1bpp"

gMonFrontPic_Gemmal::
	.incbin "graphics/pokemon/gemmal/front.4bpp.lz"

gMonPalette_Gemmal::
	.incbin "graphics/pokemon/gemmal/normal.gbapal.lz"

gMonBackPic_Gemmal::
	.incbin "graphics/pokemon/gemmal/back.4bpp.lz"

gMonShinyPalette_Gemmal::
	.incbin "graphics/pokemon/gemmal/shiny.gbapal.lz"

gMonIcon_Gemmal::
	.incbin "graphics/pokemon/gemmal/icon.4bpp"

gMonFootprint_Gemmal::
	.incbin "graphics/pokemon/gemmal/footprint.1bpp"

gMonFrontPic_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/front.4bpp.lz"

gMonPalette_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/normal.gbapal.lz"

gMonBackPic_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/back.4bpp.lz"

gMonShinyPalette_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/shiny.gbapal.lz"

gMonIcon_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/icon.4bpp"

gMonFootprint_Kotokabe::
	.incbin "graphics/pokemon/kotokabe/footprint.1bpp"

gMonFrontPic_Armay::
	.incbin "graphics/pokemon/armay/front.4bpp.lz"

gMonPalette_Armay::
	.incbin "graphics/pokemon/armay/normal.gbapal.lz"

gMonBackPic_Armay::
	.incbin "graphics/pokemon/armay/back.4bpp.lz"

gMonShinyPalette_Armay::
	.incbin "graphics/pokemon/armay/shiny.gbapal.lz"

gMonIcon_Armay::
	.incbin "graphics/pokemon/armay/icon.4bpp"

gMonFootprint_Armay::
	.incbin "graphics/pokemon/armay/footprint.1bpp"

gMonFrontPic_Armstorm::
	.incbin "graphics/pokemon/armstorm/front.4bpp.lz"

gMonPalette_Armstorm::
	.incbin "graphics/pokemon/armstorm/normal.gbapal.lz"

gMonBackPic_Armstorm::
	.incbin "graphics/pokemon/armstorm/back.4bpp.lz"

gMonShinyPalette_Armstorm::
	.incbin "graphics/pokemon/armstorm/shiny.gbapal.lz"

gMonIcon_Armstorm::
	.incbin "graphics/pokemon/armstorm/icon.4bpp"

gMonFootprint_Armstorm::
	.incbin "graphics/pokemon/armstorm/footprint.1bpp"

gMonFrontPic_Torido::
	.incbin "graphics/pokemon/torido/front.4bpp.lz"

gMonPalette_Torido::
	.incbin "graphics/pokemon/torido/normal.gbapal.lz"

gMonBackPic_Torido::
	.incbin "graphics/pokemon/torido/back.4bpp.lz"

gMonShinyPalette_Torido::
	.incbin "graphics/pokemon/torido/shiny.gbapal.lz"

gMonIcon_Torido::
	.incbin "graphics/pokemon/torido/icon.4bpp"

gMonFootprint_Torido::
	.incbin "graphics/pokemon/torido/footprint.1bpp"

gMonFrontPic_Dotori::
	.incbin "graphics/pokemon/dotori/front.4bpp.lz"

gMonPalette_Dotori::
	.incbin "graphics/pokemon/dotori/normal.gbapal.lz"

gMonBackPic_Dotori::
	.incbin "graphics/pokemon/dotori/back.4bpp.lz"

gMonShinyPalette_Dotori::
	.incbin "graphics/pokemon/dotori/shiny.gbapal.lz"

gMonIcon_Dotori::
	.incbin "graphics/pokemon/dotori/icon.4bpp"

gMonFootprint_Dotori::
	.incbin "graphics/pokemon/dotori/footprint.1bpp"

gMonFrontPic_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/front.4bpp.lz"

gMonPalette_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/normal.gbapal.lz"

gMonBackPic_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/back.4bpp.lz"

gMonShinyPalette_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/shiny.gbapal.lz"

gMonIcon_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/icon.4bpp"

gMonFootprint_Enyendrode::
	.incbin "graphics/pokemon/enyendrode/footprint.1bpp"

gMonFrontPic_Mongostre::
	.incbin "graphics/pokemon/mongostre/front.4bpp.lz"

gMonPalette_Mongostre::
	.incbin "graphics/pokemon/mongostre/normal.gbapal.lz"

gMonBackPic_Mongostre::
	.incbin "graphics/pokemon/mongostre/back.4bpp.lz"

gMonShinyPalette_Mongostre::
	.incbin "graphics/pokemon/mongostre/shiny.gbapal.lz"

gMonIcon_Mongostre::
	.incbin "graphics/pokemon/mongostre/icon.4bpp"

gMonFootprint_Mongostre::
	.incbin "graphics/pokemon/mongostre/footprint.1bpp"

gMonFrontPic_Hamet::
	.incbin "graphics/pokemon/hamet/front.4bpp.lz"

gMonPalette_Hamet::
	.incbin "graphics/pokemon/hamet/normal.gbapal.lz"

gMonBackPic_Hamet::
	.incbin "graphics/pokemon/hamet/back.4bpp.lz"

gMonShinyPalette_Hamet::
	.incbin "graphics/pokemon/hamet/shiny.gbapal.lz"

gMonIcon_Hamet::
	.incbin "graphics/pokemon/hamet/icon.4bpp"

gMonFootprint_Hamet::
	.incbin "graphics/pokemon/hamet/footprint.1bpp"

gMonFrontPic_Ratelo::
	.incbin "graphics/pokemon/ratelo/front.4bpp.lz"

gMonPalette_Ratelo::
	.incbin "graphics/pokemon/ratelo/normal.gbapal.lz"

gMonBackPic_Ratelo::
	.incbin "graphics/pokemon/ratelo/back.4bpp.lz"

gMonShinyPalette_Ratelo::
	.incbin "graphics/pokemon/ratelo/shiny.gbapal.lz"

gMonIcon_Ratelo::
	.incbin "graphics/pokemon/ratelo/icon.4bpp"

gMonFootprint_Ratelo::
	.incbin "graphics/pokemon/ratelo/footprint.1bpp"

gMonFrontPic_Psimouse::
	.incbin "graphics/pokemon/psimouse/front.4bpp.lz"

gMonPalette_Psimouse::
	.incbin "graphics/pokemon/psimouse/normal.gbapal.lz"

gMonBackPic_Psimouse::
	.incbin "graphics/pokemon/psimouse/back.4bpp.lz"

gMonShinyPalette_Psimouse::
	.incbin "graphics/pokemon/psimouse/shiny.gbapal.lz"

gMonIcon_Psimouse::
	.incbin "graphics/pokemon/psimouse/icon.4bpp"

gMonFootprint_Psimouse::
	.incbin "graphics/pokemon/psimouse/footprint.1bpp"

gMonFrontPic_Dristal::
	.incbin "graphics/pokemon/dristal/front.4bpp.lz"

gMonPalette_Dristal::
	.incbin "graphics/pokemon/dristal/normal.gbapal.lz"

gMonBackPic_Dristal::
	.incbin "graphics/pokemon/dristal/back.4bpp.lz"

gMonShinyPalette_Dristal::
	.incbin "graphics/pokemon/dristal/shiny.gbapal.lz"

gMonIcon_Dristal::
	.incbin "graphics/pokemon/dristal/icon.4bpp"

gMonFootprint_Dristal::
	.incbin "graphics/pokemon/dristal/footprint.1bpp"

gMonFrontPic_Feegon::
	.incbin "graphics/pokemon/feégon/front.4bpp.lz"

gMonPalette_Feegon::
	.incbin "graphics/pokemon/feégon/normal.gbapal.lz"

gMonBackPic_Feegon::
	.incbin "graphics/pokemon/feégon/back.4bpp.lz"

gMonShinyPalette_Feegon::
	.incbin "graphics/pokemon/feégon/shiny.gbapal.lz"

gMonIcon_Feegon::
	.incbin "graphics/pokemon/feégon/icon.4bpp"

gMonFootprint_Feegon::
	.incbin "graphics/pokemon/feégon/footprint.1bpp"

gMonFrontPic_Drahago::
	.incbin "graphics/pokemon/drahago/front.4bpp.lz"

gMonPalette_Drahago::
	.incbin "graphics/pokemon/drahago/normal.gbapal.lz"

gMonBackPic_Drahago::
	.incbin "graphics/pokemon/drahago/back.4bpp.lz"

gMonShinyPalette_Drahago::
	.incbin "graphics/pokemon/drahago/shiny.gbapal.lz"

gMonIcon_Drahago::
	.incbin "graphics/pokemon/drahago/icon.4bpp"

gMonFootprint_Drahago::
	.incbin "graphics/pokemon/drahago/footprint.1bpp"

gMonFrontPic_Tenry::
	.incbin "graphics/pokemon/tenry/front.4bpp.lz"

gMonPalette_Tenry::
	.incbin "graphics/pokemon/tenry/normal.gbapal.lz"

gMonBackPic_Tenry::
	.incbin "graphics/pokemon/tenry/back.4bpp.lz"

gMonShinyPalette_Tenry::
	.incbin "graphics/pokemon/tenry/shiny.gbapal.lz"

gMonIcon_Tenry::
	.incbin "graphics/pokemon/tenry/icon.4bpp"

gMonFootprint_Tenry::
	.incbin "graphics/pokemon/tenry/footprint.1bpp"

gMonFrontPic_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/front.4bpp.lz"

gMonPalette_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/normal.gbapal.lz"

gMonBackPic_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/back.4bpp.lz"

gMonShinyPalette_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/shiny.gbapal.lz"

gMonIcon_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/icon.4bpp"

gMonFootprint_Wrestoro::
	.incbin "graphics/pokemon/wrestoro/footprint.1bpp"

gMonFrontPic_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/front.4bpp.lz"

gMonPalette_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/normal.gbapal.lz"

gMonBackPic_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/back.4bpp.lz"

gMonShinyPalette_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/shiny.gbapal.lz"

gMonIcon_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/icon.4bpp"

gMonFootprint_Wrestmilk::
	.incbin "graphics/pokemon/wrestmilk/footprint.1bpp"

gMonFrontPic_Molebas::
	.incbin "graphics/pokemon/molebas/front.4bpp.lz"

gMonPalette_Molebas::
	.incbin "graphics/pokemon/molebas/normal.gbapal.lz"

gMonBackPic_Molebas::
	.incbin "graphics/pokemon/molebas/back.4bpp.lz"

gMonShinyPalette_Molebas::
	.incbin "graphics/pokemon/molebas/shiny.gbapal.lz"

gMonIcon_Molebas::
	.incbin "graphics/pokemon/molebas/icon.4bpp"

gMonFootprint_Molebas::
	.incbin "graphics/pokemon/molebas/footprint.1bpp"

gMonFrontPic_Dugobas::
	.incbin "graphics/pokemon/dugobas/front.4bpp.lz"

gMonPalette_Dugobas::
	.incbin "graphics/pokemon/dugobas/normal.gbapal.lz"

gMonBackPic_Dugobas::
	.incbin "graphics/pokemon/dugobas/back.4bpp.lz"

gMonShinyPalette_Dugobas::
	.incbin "graphics/pokemon/dugobas/shiny.gbapal.lz"

gMonIcon_Dugobas::
	.incbin "graphics/pokemon/dugobas/icon.4bpp"

gMonFootprint_Dugobas::
	.incbin "graphics/pokemon/dugobas/footprint.1bpp"

gMonFrontPic_Lapibas::
	.incbin "graphics/pokemon/lapibas/front.4bpp.lz"

gMonPalette_Lapibas::
	.incbin "graphics/pokemon/lapibas/normal.gbapal.lz"

gMonBackPic_Lapibas::
	.incbin "graphics/pokemon/lapibas/back.4bpp.lz"

gMonShinyPalette_Lapibas::
	.incbin "graphics/pokemon/lapibas/shiny.gbapal.lz"

gMonIcon_Lapibas::
	.incbin "graphics/pokemon/lapibas/icon.4bpp"

gMonFootprint_Lapibas::
	.incbin "graphics/pokemon/lapibas/footprint.1bpp"

gMonFrontPic_Kaomare::
	.incbin "graphics/pokemon/kaomare/front.4bpp.lz"

gMonPalette_Kaomare::
	.incbin "graphics/pokemon/kaomare/normal.gbapal.lz"

gMonBackPic_Kaomare::
	.incbin "graphics/pokemon/kaomare/back.4bpp.lz"

gMonShinyPalette_Kaomare::
	.incbin "graphics/pokemon/kaomare/shiny.gbapal.lz"

gMonIcon_Kaomare::
	.incbin "graphics/pokemon/kaomare/icon.4bpp"

gMonFootprint_Kaomare::
	.incbin "graphics/pokemon/kaomare/footprint.1bpp"

gMonFrontPic_Kaosune::
	.incbin "graphics/pokemon/kaosune/front.4bpp.lz"

gMonPalette_Kaosune::
	.incbin "graphics/pokemon/kaosune/normal.gbapal.lz"

gMonBackPic_Kaosune::
	.incbin "graphics/pokemon/kaosune/back.4bpp.lz"

gMonShinyPalette_Kaosune::
	.incbin "graphics/pokemon/kaosune/shiny.gbapal.lz"

gMonIcon_Kaosune::
	.incbin "graphics/pokemon/kaosune/icon.4bpp"

gMonFootprint_Kaosune::
	.incbin "graphics/pokemon/kaosune/footprint.1bpp"

gMonFrontPic_Peezgal::
	.incbin "graphics/pokemon/peezgal/front.4bpp.lz"

gMonPalette_Peezgal::
	.incbin "graphics/pokemon/peezgal/normal.gbapal.lz"

gMonBackPic_Peezgal::
	.incbin "graphics/pokemon/peezgal/back.4bpp.lz"

gMonShinyPalette_Peezgal::
	.incbin "graphics/pokemon/peezgal/shiny.gbapal.lz"

gMonIcon_Peezgal::
	.incbin "graphics/pokemon/peezgal/icon.4bpp"

gMonFootprint_Peezgal::
	.incbin "graphics/pokemon/peezgal/footprint.1bpp"

gMonFrontPic_Ordkip::
	.incbin "graphics/pokemon/ordkip/front.4bpp.lz"

gMonPalette_Ordkip::
	.incbin "graphics/pokemon/ordkip/normal.gbapal.lz"

gMonBackPic_Ordkip::
	.incbin "graphics/pokemon/ordkip/back.4bpp.lz"

gMonShinyPalette_Ordkip::
	.incbin "graphics/pokemon/ordkip/shiny.gbapal.lz"

gMonIcon_Ordkip::
	.incbin "graphics/pokemon/ordkip/icon.4bpp"

gMonFootprint_Ordkip::
	.incbin "graphics/pokemon/ordkip/footprint.1bpp"

gMonFrontPic_Tanord::
	.incbin "graphics/pokemon/tanord/front.4bpp.lz"

gMonPalette_Tanord::
	.incbin "graphics/pokemon/tanord/normal.gbapal.lz"

gMonBackPic_Tanord::
	.incbin "graphics/pokemon/tanord/back.4bpp.lz"

gMonShinyPalette_Tanord::
	.incbin "graphics/pokemon/tanord/shiny.gbapal.lz"

gMonIcon_Tanord::
	.incbin "graphics/pokemon/tanord/icon.4bpp"

gMonFootprint_Tanord::
	.incbin "graphics/pokemon/tanord/footprint.1bpp"

gMonFrontPic_Karendi::
	.incbin "graphics/pokemon/karendi/front.4bpp.lz"

gMonPalette_Karendi::
	.incbin "graphics/pokemon/karendi/normal.gbapal.lz"

gMonBackPic_Karendi::
	.incbin "graphics/pokemon/karendi/back.4bpp.lz"

gMonShinyPalette_Karendi::
	.incbin "graphics/pokemon/karendi/shiny.gbapal.lz"

gMonIcon_Karendi::
	.incbin "graphics/pokemon/karendi/icon.4bpp"

gMonFootprint_Karendi::
	.incbin "graphics/pokemon/karendi/footprint.1bpp"

gMonFrontPic_Garotao::
	.incbin "graphics/pokemon/garotao/front.4bpp.lz"

gMonPalette_Garotao::
	.incbin "graphics/pokemon/garotao/normal.gbapal.lz"

gMonBackPic_Garotao::
	.incbin "graphics/pokemon/garotao/back.4bpp.lz"

gMonShinyPalette_Garotao::
	.incbin "graphics/pokemon/garotao/shiny.gbapal.lz"

gMonIcon_Garotao::
	.incbin "graphics/pokemon/garotao/icon.4bpp"

gMonFootprint_Garotao::
	.incbin "graphics/pokemon/garotao/footprint.1bpp"

gMonFrontPic_Gritespec::
	.incbin "graphics/pokemon/gritespec/front.4bpp.lz"

gMonPalette_Gritespec::
	.incbin "graphics/pokemon/gritespec/normal.gbapal.lz"

gMonBackPic_Gritespec::
	.incbin "graphics/pokemon/gritespec/back.4bpp.lz"

gMonShinyPalette_Gritespec::
	.incbin "graphics/pokemon/gritespec/shiny.gbapal.lz"

gMonIcon_Gritespec::
	.incbin "graphics/pokemon/gritespec/icon.4bpp"

gMonFootprint_Gritespec::
	.incbin "graphics/pokemon/gritespec/footprint.1bpp"

